# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModSetupWithTree.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 690)
        MainWindow.setMaximumSize(QtCore.QSize(680, 690))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MainFrame = QtGui.QFrame(self.centralwidget)
        self.MainFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainFrame.setObjectName(_fromUtf8("MainFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.MainFrame)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frameStackedWidget = QtGui.QFrame(self.MainFrame)
        self.frameStackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameStackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.frameStackedWidget.setObjectName(_fromUtf8("frameStackedWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameStackedWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.frameStackedWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pcDetails = QtGui.QWidget()
        self.pcDetails.setObjectName(_fromUtf8("pcDetails"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pcDetails)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.framePc = QtGui.QFrame(self.pcDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePc.sizePolicy().hasHeightForWidth())
        self.framePc.setSizePolicy(sizePolicy)
        self.framePc.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.framePc.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePc.setObjectName(_fromUtf8("framePc"))
        self.frame_5 = QtGui.QFrame(self.framePc)
        self.frame_5.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.framePcAddressDetails = QtGui.QFrame(self.frame_5)
        self.framePcAddressDetails.setGeometry(QtCore.QRect(20, 30, 371, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcAddressDetails.sizePolicy().hasHeightForWidth())
        self.framePcAddressDetails.setSizePolicy(sizePolicy)
        self.framePcAddressDetails.setFrameShape(QtGui.QFrame.Box)
        self.framePcAddressDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcAddressDetails.setObjectName(_fromUtf8("framePcAddressDetails"))
        self.gridLayout_7 = QtGui.QGridLayout(self.framePcAddressDetails)
        self.gridLayout_7.setContentsMargins(10, -1, 12, -1)
        self.gridLayout_7.setHorizontalSpacing(60)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelPcPhysicalAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcPhysicalAddress.setObjectName(_fromUtf8("labelPcPhysicalAddress"))
        self.gridLayout_7.addWidget(self.labelPcPhysicalAddress, 1, 0, 1, 1)
        self.labelPcIpAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcIpAddress.setObjectName(_fromUtf8("labelPcIpAddress"))
        self.gridLayout_7.addWidget(self.labelPcIpAddress, 2, 0, 1, 1)
        self.textBrowserPcDefaultGateway = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcDefaultGateway.setObjectName(_fromUtf8("textBrowserPcDefaultGateway"))
        self.gridLayout_7.addWidget(self.textBrowserPcDefaultGateway, 4, 1, 1, 1)
        self.labelPcDefaultGateway = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcDefaultGateway.setObjectName(_fromUtf8("labelPcDefaultGateway"))
        self.gridLayout_7.addWidget(self.labelPcDefaultGateway, 4, 0, 1, 1)
        self.textBrowserPcSubnetMask = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcSubnetMask.setObjectName(_fromUtf8("textBrowserPcSubnetMask"))
        self.gridLayout_7.addWidget(self.textBrowserPcSubnetMask, 3, 1, 1, 1)
        self.textBrowserPcIpAddress = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcIpAddress.setObjectName(_fromUtf8("textBrowserPcIpAddress"))
        self.gridLayout_7.addWidget(self.textBrowserPcIpAddress, 2, 1, 1, 1)
        self.labelPcSubnetMask = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcSubnetMask.setObjectName(_fromUtf8("labelPcSubnetMask"))
        self.gridLayout_7.addWidget(self.labelPcSubnetMask, 3, 0, 1, 1)
        self.textBrowserPcPhysicalAddress = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcPhysicalAddress.setObjectName(_fromUtf8("textBrowserPcPhysicalAddress"))
        self.gridLayout_7.addWidget(self.textBrowserPcPhysicalAddress, 1, 1, 1, 1)
        self.gridLayout_7.setColumnMinimumWidth(0, 100)
        self.pushButtonPc = QtGui.QPushButton(self.frame_5)
        self.pushButtonPc.setGeometry(QtCore.QRect(260, 240, 121, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPc.sizePolicy().hasHeightForWidth())
        self.pushButtonPc.setSizePolicy(sizePolicy)
        self.pushButtonPc.setObjectName(_fromUtf8("pushButtonPc"))
        self.tcpIpDetailsLabel = QtGui.QLabel(self.framePc)
        self.tcpIpDetailsLabel.setGeometry(QtCore.QRect(150, 10, 81, 21))
        self.tcpIpDetailsLabel.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tcpIpDetailsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpIpDetailsLabel.setObjectName(_fromUtf8("tcpIpDetailsLabel"))
        self.gridLayout_4.addWidget(self.framePc, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pcDetails)
        self.localModems = QtGui.QWidget()
        self.localModems.setObjectName(_fromUtf8("localModems"))
        self.gridLayout_5 = QtGui.QGridLayout(self.localModems)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frameLocalDev = QtGui.QFrame(self.localModems)
        self.frameLocalDev.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLocalDev.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLocalDev.setObjectName(_fromUtf8("frameLocalDev"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frameLocalDev)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabLocalDevDetails = QtGui.QTabWidget(self.frameLocalDev)
        self.tabLocalDevDetails.setEnabled(True)
        self.tabLocalDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabLocalDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabLocalDevDetails.setIconSize(QtCore.QSize(16, 16))
        self.tabLocalDevDetails.setTabsClosable(False)
        self.tabLocalDevDetails.setObjectName(_fromUtf8("tabLocalDevDetails"))
        self.localDevNetworkDetails = QtGui.QWidget()
        self.localDevNetworkDetails.setObjectName(_fromUtf8("localDevNetworkDetails"))
        self.frame_2 = QtGui.QFrame(self.localDevNetworkDetails)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.frame_2.setToolTip(_fromUtf8(""))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.listWidget = QtGui.QListWidget(self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(20, 400, 351, 81))
        self.listWidget.setFrameShape(QtGui.QFrame.Box)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(29, 390, 81, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(30, 500, 131, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.listWidget_2 = QtGui.QListWidget(self.frame_2)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 510, 351, 81))
        self.listWidget_2.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 50, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.Eth0Local = QtGui.QGridLayout(self.frame_3)
        self.Eth0Local.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local.setHorizontalSpacing(60)
        self.Eth0Local.setVerticalSpacing(6)
        self.Eth0Local.setObjectName(_fromUtf8("Eth0Local"))
        self.labelLocalEth0IpAddress = QtGui.QLabel(self.frame_3)
        self.labelLocalEth0IpAddress.setObjectName(_fromUtf8("labelLocalEth0IpAddress"))
        self.Eth0Local.addWidget(self.labelLocalEth0IpAddress, 0, 0, 1, 1)
        self.textBrowser_6 = QtGui.QTextBrowser(self.frame_3)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.Eth0Local.addWidget(self.textBrowser_6, 0, 1, 1, 1)
        self.labelLocalEth0MacAddress = QtGui.QLabel(self.frame_3)
        self.labelLocalEth0MacAddress.setObjectName(_fromUtf8("labelLocalEth0MacAddress"))
        self.Eth0Local.addWidget(self.labelLocalEth0MacAddress, 1, 0, 1, 1)
        self.textBrowser_5 = QtGui.QTextBrowser(self.frame_3)
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.Eth0Local.addWidget(self.textBrowser_5, 1, 1, 1, 1)
        self.labelLocalEth0 = QtGui.QLabel(self.frame_2)
        self.labelLocalEth0.setGeometry(QtCore.QRect(30, 40, 41, 21))
        self.labelLocalEth0.setScaledContents(False)
        self.labelLocalEth0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalEth0.setObjectName(_fromUtf8("labelLocalEth0"))
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(20, 160, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.Eth0Local_2 = QtGui.QGridLayout(self.frame_4)
        self.Eth0Local_2.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_2.setHorizontalSpacing(60)
        self.Eth0Local_2.setObjectName(_fromUtf8("Eth0Local_2"))
        self.label_6 = QtGui.QLabel(self.frame_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.Eth0Local_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.textBrowser_7 = QtGui.QTextBrowser(self.frame_4)
        self.textBrowser_7.setObjectName(_fromUtf8("textBrowser_7"))
        self.Eth0Local_2.addWidget(self.textBrowser_7, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Eth0Local_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.textBrowser_8 = QtGui.QTextBrowser(self.frame_4)
        self.textBrowser_8.setObjectName(_fromUtf8("textBrowser_8"))
        self.Eth0Local_2.addWidget(self.textBrowser_8, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(30, 150, 41, 21))
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(30, 260, 41, 21))
        self.label_15.setScaledContents(False)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.frame_17 = QtGui.QFrame(self.frame_2)
        self.frame_17.setGeometry(QtCore.QRect(20, 270, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setFrameShape(QtGui.QFrame.Box)
        self.frame_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_17.setLineWidth(1)
        self.frame_17.setObjectName(_fromUtf8("frame_17"))
        self.Eth0Local_15 = QtGui.QGridLayout(self.frame_17)
        self.Eth0Local_15.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_15.setHorizontalSpacing(60)
        self.Eth0Local_15.setObjectName(_fromUtf8("Eth0Local_15"))
        self.label_41 = QtGui.QLabel(self.frame_17)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.Eth0Local_15.addWidget(self.label_41, 0, 0, 1, 1)
        self.textBrowser_25 = QtGui.QTextBrowser(self.frame_17)
        self.textBrowser_25.setObjectName(_fromUtf8("textBrowser_25"))
        self.Eth0Local_15.addWidget(self.textBrowser_25, 0, 1, 1, 1)
        self.label_54 = QtGui.QLabel(self.frame_17)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.Eth0Local_15.addWidget(self.label_54, 1, 0, 1, 1)
        self.textBrowser_28 = QtGui.QTextBrowser(self.frame_17)
        self.textBrowser_28.setObjectName(_fromUtf8("textBrowser_28"))
        self.Eth0Local_15.addWidget(self.textBrowser_28, 1, 1, 1, 1)
        self.listWidget.raise_()
        self.label_11.raise_()
        self.listWidget_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.label_14.raise_()
        self.label_12.raise_()
        self.labelLocalEth0.raise_()
        self.frame_17.raise_()
        self.label_15.raise_()
        self.label_7 = QtGui.QLabel(self.localDevNetworkDetails)
        self.label_7.setGeometry(QtCore.QRect(150, 10, 111, 21))
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabLocalDevDetails.addTab(self.localDevNetworkDetails, _fromUtf8(""))
        self.localDevSoftwareDetails = QtGui.QWidget()
        self.localDevSoftwareDetails.setObjectName(_fromUtf8("localDevSoftwareDetails"))
        self.frame = QtGui.QFrame(self.localDevSoftwareDetails)
        self.frame.setGeometry(QtCore.QRect(10, 20, 411, 621))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_10 = QtGui.QFrame(self.frame)
        self.frame_10.setGeometry(QtCore.QRect(20, 50, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setAutoFillBackground(False)
        self.frame_10.setFrameShape(QtGui.QFrame.Box)
        self.frame_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_10.setLineWidth(1)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.Eth0Local_7 = QtGui.QGridLayout(self.frame_10)
        self.Eth0Local_7.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_7.setHorizontalSpacing(60)
        self.Eth0Local_7.setObjectName(_fromUtf8("Eth0Local_7"))
        self.label_37 = QtGui.QLabel(self.frame_10)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.Eth0Local_7.addWidget(self.label_37, 0, 0, 1, 1)
        self.textBrowser_26 = QtGui.QTextBrowser(self.frame_10)
        self.textBrowser_26.setObjectName(_fromUtf8("textBrowser_26"))
        self.Eth0Local_7.addWidget(self.textBrowser_26, 0, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.frame_10)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.Eth0Local_7.addWidget(self.label_38, 1, 0, 1, 1)
        self.textBrowser_27 = QtGui.QTextBrowser(self.frame_10)
        self.textBrowser_27.setObjectName(_fromUtf8("textBrowser_27"))
        self.Eth0Local_7.addWidget(self.textBrowser_27, 1, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.frame)
        self.label_39.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.label_39.setScaledContents(False)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.frame_11 = QtGui.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(20, 160, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setAutoFillBackground(False)
        self.frame_11.setFrameShape(QtGui.QFrame.Box)
        self.frame_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_11.setLineWidth(1)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.Eth0Local_9 = QtGui.QGridLayout(self.frame_11)
        self.Eth0Local_9.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_9.setHorizontalSpacing(60)
        self.Eth0Local_9.setObjectName(_fromUtf8("Eth0Local_9"))
        self.label_42 = QtGui.QLabel(self.frame_11)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.Eth0Local_9.addWidget(self.label_42, 0, 0, 1, 1)
        self.textBrowser_30 = QtGui.QTextBrowser(self.frame_11)
        self.textBrowser_30.setObjectName(_fromUtf8("textBrowser_30"))
        self.Eth0Local_9.addWidget(self.textBrowser_30, 0, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.frame_11)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.Eth0Local_9.addWidget(self.label_43, 1, 0, 1, 1)
        self.textBrowser_31 = QtGui.QTextBrowser(self.frame_11)
        self.textBrowser_31.setObjectName(_fromUtf8("textBrowser_31"))
        self.Eth0Local_9.addWidget(self.textBrowser_31, 1, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.frame)
        self.label_44.setGeometry(QtCore.QRect(30, 150, 111, 21))
        self.label_44.setScaledContents(False)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.frame_12 = QtGui.QFrame(self.frame)
        self.frame_12.setGeometry(QtCore.QRect(20, 270, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setAutoFillBackground(False)
        self.frame_12.setFrameShape(QtGui.QFrame.Box)
        self.frame_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_12.setLineWidth(1)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.Eth0Local_10 = QtGui.QGridLayout(self.frame_12)
        self.Eth0Local_10.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_10.setHorizontalSpacing(60)
        self.Eth0Local_10.setObjectName(_fromUtf8("Eth0Local_10"))
        self.label_45 = QtGui.QLabel(self.frame_12)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.Eth0Local_10.addWidget(self.label_45, 0, 0, 1, 1)
        self.textBrowser_32 = QtGui.QTextBrowser(self.frame_12)
        self.textBrowser_32.setObjectName(_fromUtf8("textBrowser_32"))
        self.Eth0Local_10.addWidget(self.textBrowser_32, 0, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.frame_12)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.Eth0Local_10.addWidget(self.label_46, 1, 0, 1, 1)
        self.textBrowser_33 = QtGui.QTextBrowser(self.frame_12)
        self.textBrowser_33.setObjectName(_fromUtf8("textBrowser_33"))
        self.Eth0Local_10.addWidget(self.textBrowser_33, 1, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.frame)
        self.label_47.setGeometry(QtCore.QRect(30, 260, 91, 21))
        self.label_47.setScaledContents(False)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.frame_13 = QtGui.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(20, 380, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setAutoFillBackground(False)
        self.frame_13.setFrameShape(QtGui.QFrame.Box)
        self.frame_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_13.setLineWidth(1)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.Eth0Local_11 = QtGui.QGridLayout(self.frame_13)
        self.Eth0Local_11.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_11.setHorizontalSpacing(60)
        self.Eth0Local_11.setObjectName(_fromUtf8("Eth0Local_11"))
        self.label_48 = QtGui.QLabel(self.frame_13)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.Eth0Local_11.addWidget(self.label_48, 0, 0, 1, 1)
        self.textBrowser_34 = QtGui.QTextBrowser(self.frame_13)
        self.textBrowser_34.setObjectName(_fromUtf8("textBrowser_34"))
        self.Eth0Local_11.addWidget(self.textBrowser_34, 0, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.frame_13)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.Eth0Local_11.addWidget(self.label_49, 1, 0, 1, 1)
        self.textBrowser_35 = QtGui.QTextBrowser(self.frame_13)
        self.textBrowser_35.setObjectName(_fromUtf8("textBrowser_35"))
        self.Eth0Local_11.addWidget(self.textBrowser_35, 1, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.frame)
        self.label_50.setGeometry(QtCore.QRect(30, 370, 81, 21))
        self.label_50.setScaledContents(False)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.label_30 = QtGui.QLabel(self.localDevSoftwareDetails)
        self.label_30.setGeometry(QtCore.QRect(120, 10, 191, 21))
        self.label_30.setScaledContents(False)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tabLocalDevDetails.addTab(self.localDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabLocalDevDetails, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frameLocalDev, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.localModems)
        self.remoteModems = QtGui.QWidget()
        self.remoteModems.setObjectName(_fromUtf8("remoteModems"))
        self.gridLayout_6 = QtGui.QGridLayout(self.remoteModems)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frameRemoteDev = QtGui.QFrame(self.remoteModems)
        self.frameRemoteDev.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRemoteDev.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRemoteDev.setObjectName(_fromUtf8("frameRemoteDev"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frameRemoteDev)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabRemoteDevDetails = QtGui.QTabWidget(self.frameRemoteDev)
        self.tabRemoteDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabRemoteDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabRemoteDevDetails.setTabsClosable(False)
        self.tabRemoteDevDetails.setObjectName(_fromUtf8("tabRemoteDevDetails"))
        self.remoteDevNetworkDetails = QtGui.QWidget()
        self.remoteDevNetworkDetails.setObjectName(_fromUtf8("remoteDevNetworkDetails"))
        self.frame_6 = QtGui.QFrame(self.remoteDevNetworkDetails)
        self.frame_6.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.frame_6.setToolTip(_fromUtf8(""))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.listWidget_5 = QtGui.QListWidget(self.frame_6)
        self.listWidget_5.setGeometry(QtCore.QRect(20, 390, 351, 81))
        self.listWidget_5.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.label_31 = QtGui.QLabel(self.frame_6)
        self.label_31.setGeometry(QtCore.QRect(29, 390, 81, 20))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.frame_6)
        self.label_32.setGeometry(QtCore.QRect(30, 500, 131, 21))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.listWidget_6 = QtGui.QListWidget(self.frame_6)
        self.listWidget_6.setGeometry(QtCore.QRect(20, 510, 351, 81))
        self.listWidget_6.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_6.setObjectName(_fromUtf8("listWidget_6"))
        self.frame_14 = QtGui.QFrame(self.frame_6)
        self.frame_14.setGeometry(QtCore.QRect(20, 50, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setAutoFillBackground(False)
        self.frame_14.setFrameShape(QtGui.QFrame.Box)
        self.frame_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_14.setLineWidth(1)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.Eth0Local_12 = QtGui.QGridLayout(self.frame_14)
        self.Eth0Local_12.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_12.setHorizontalSpacing(60)
        self.Eth0Local_12.setVerticalSpacing(6)
        self.Eth0Local_12.setObjectName(_fromUtf8("Eth0Local_12"))
        self.label_33 = QtGui.QLabel(self.frame_14)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.Eth0Local_12.addWidget(self.label_33, 0, 0, 1, 1)
        self.textBrowser_19 = QtGui.QTextBrowser(self.frame_14)
        self.textBrowser_19.setObjectName(_fromUtf8("textBrowser_19"))
        self.Eth0Local_12.addWidget(self.textBrowser_19, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.frame_14)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.Eth0Local_12.addWidget(self.label_34, 1, 0, 1, 1)
        self.textBrowser_20 = QtGui.QTextBrowser(self.frame_14)
        self.textBrowser_20.setObjectName(_fromUtf8("textBrowser_20"))
        self.Eth0Local_12.addWidget(self.textBrowser_20, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(30, 40, 41, 21))
        self.label_35.setScaledContents(False)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.frame_15 = QtGui.QFrame(self.frame_6)
        self.frame_15.setGeometry(QtCore.QRect(20, 160, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtGui.QFrame.Box)
        self.frame_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_15.setLineWidth(1)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.Eth0Local_13 = QtGui.QGridLayout(self.frame_15)
        self.Eth0Local_13.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_13.setHorizontalSpacing(60)
        self.Eth0Local_13.setObjectName(_fromUtf8("Eth0Local_13"))
        self.label_36 = QtGui.QLabel(self.frame_15)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.Eth0Local_13.addWidget(self.label_36, 0, 0, 1, 1)
        self.textBrowser_21 = QtGui.QTextBrowser(self.frame_15)
        self.textBrowser_21.setObjectName(_fromUtf8("textBrowser_21"))
        self.Eth0Local_13.addWidget(self.textBrowser_21, 0, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.frame_15)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.Eth0Local_13.addWidget(self.label_51, 1, 0, 1, 1)
        self.textBrowser_22 = QtGui.QTextBrowser(self.frame_15)
        self.textBrowser_22.setObjectName(_fromUtf8("textBrowser_22"))
        self.Eth0Local_13.addWidget(self.textBrowser_22, 1, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.frame_6)
        self.label_52.setGeometry(QtCore.QRect(30, 150, 41, 21))
        self.label_52.setScaledContents(False)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_55 = QtGui.QLabel(self.frame_6)
        self.label_55.setGeometry(QtCore.QRect(30, 260, 41, 21))
        self.label_55.setScaledContents(False)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.frame_16 = QtGui.QFrame(self.frame_6)
        self.frame_16.setGeometry(QtCore.QRect(20, 270, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtGui.QFrame.Box)
        self.frame_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_16.setLineWidth(1)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.Eth0Local_14 = QtGui.QGridLayout(self.frame_16)
        self.Eth0Local_14.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_14.setHorizontalSpacing(60)
        self.Eth0Local_14.setObjectName(_fromUtf8("Eth0Local_14"))
        self.label_40 = QtGui.QLabel(self.frame_16)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.Eth0Local_14.addWidget(self.label_40, 0, 0, 1, 1)
        self.textBrowser_23 = QtGui.QTextBrowser(self.frame_16)
        self.textBrowser_23.setObjectName(_fromUtf8("textBrowser_23"))
        self.Eth0Local_14.addWidget(self.textBrowser_23, 0, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.frame_16)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.Eth0Local_14.addWidget(self.label_53, 1, 0, 1, 1)
        self.textBrowser_24 = QtGui.QTextBrowser(self.frame_16)
        self.textBrowser_24.setObjectName(_fromUtf8("textBrowser_24"))
        self.Eth0Local_14.addWidget(self.textBrowser_24, 1, 1, 1, 1)
        self.listWidget_5.raise_()
        self.label_31.raise_()
        self.listWidget_6.raise_()
        self.frame_14.raise_()
        self.label_35.raise_()
        self.frame_15.raise_()
        self.label_52.raise_()
        self.label_32.raise_()
        self.frame_16.raise_()
        self.label_55.raise_()
        self.label_56 = QtGui.QLabel(self.remoteDevNetworkDetails)
        self.label_56.setGeometry(QtCore.QRect(130, 10, 151, 21))
        self.label_56.setScaledContents(False)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.tabRemoteDevDetails.addTab(self.remoteDevNetworkDetails, _fromUtf8(""))
        self.remoteDevSoftwareDetails = QtGui.QWidget()
        self.remoteDevSoftwareDetails.setObjectName(_fromUtf8("remoteDevSoftwareDetails"))
        self.tabRemoteDevDetails.addTab(self.remoteDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabRemoteDevDetails, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frameRemoteDev, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.remoteModems)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_2.addWidget(self.frameStackedWidget, 0, 1, 1, 1)
        self.frameTree = QtGui.QFrame(self.MainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTree.sizePolicy().hasHeightForWidth())
        self.frameTree.setSizePolicy(sizePolicy)
        self.frameTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frameTree.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTree.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTree.setObjectName(_fromUtf8("frameTree"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameTree)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.frameTree)
        self.treeWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item_1.setFont(0, font)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setMinimumSectionSize(30)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frameTree, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.MainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabLocalDevDetails.setCurrentIndex(0)
        self.tabRemoteDevDetails.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelPcPhysicalAddress.setText(_translate("MainWindow", "Physical Address", None))
        self.labelPcIpAddress.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowserPcDefaultGateway.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.1</span></p></body></html>", None))
        self.labelPcDefaultGateway.setText(_translate("MainWindow", "Default Gateway", None))
        self.textBrowserPcSubnetMask.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.textBrowserPcIpAddress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.labelPcSubnetMask.setText(_translate("MainWindow", "Subnet Maske", None))
        self.textBrowserPcPhysicalAddress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.pushButtonPc.setText(_translate("MainWindow", "PushButton", None))
        self.tcpIpDetailsLabel.setText(_translate("MainWindow", "TCP/IP Details", None))
        self.label_11.setText(_translate("MainWindow", "Route Table", None))
        self.label_12.setText(_translate("MainWindow", "Backup Route Table", None))
        self.labelLocalEth0IpAddress.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.labelLocalEth0MacAddress.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.labelLocalEth0.setText(_translate("MainWindow", "Eth0", None))
        self.label_6.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "Fifo0", None))
        self.label_15.setText(_translate("MainWindow", "Fifo1", None))
        self.label_41.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_25.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_54.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_28.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "Local Device Details", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.label_37.setText(_translate("MainWindow", "Version", None))
        self.textBrowser_26.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_38.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowser_27.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_39.setText(_translate("MainWindow", "Default Software", None))
        self.label_42.setText(_translate("MainWindow", "Version", None))
        self.textBrowser_30.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_43.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowser_31.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_44.setText(_translate("MainWindow", "Update Software", None))
        self.label_45.setText(_translate("MainWindow", "Version", None))
        self.textBrowser_32.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_46.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowser_33.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_47.setText(_translate("MainWindow", "DSP Software", None))
        self.label_48.setText(_translate("MainWindow", "Version", None))
        self.textBrowser_34.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_49.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowser_35.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.label_50.setText(_translate("MainWindow", "DSP Config", None))
        self.label_30.setText(_translate("MainWindow", "Local Device Software Setails", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.label_31.setText(_translate("MainWindow", "Route Table", None))
        self.label_32.setText(_translate("MainWindow", "Backup Route Table", None))
        self.label_33.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "Eth0", None))
        self.label_36.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_51.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_52.setText(_translate("MainWindow", "Fifo0", None))
        self.label_55.setText(_translate("MainWindow", "Fifo1", None))
        self.label_40.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_23.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_53.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_24.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_56.setText(_translate("MainWindow", "Remote Device Details", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Network Devices", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "PC", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "TopSide Modem 2", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Subsea Modem 2.1", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Subsea Modem 2.2", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "TopSide Modem 1", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Subsea Modem 1.1", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Subsea Modem 1.2", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

