# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModSetupWithTree.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 690)
        MainWindow.setMaximumSize(QtCore.QSize(680, 690))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MainFrame = QtGui.QFrame(self.centralwidget)
        self.MainFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainFrame.setObjectName(_fromUtf8("MainFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.MainFrame)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frameStackedWidget = QtGui.QFrame(self.MainFrame)
        self.frameStackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameStackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.frameStackedWidget.setObjectName(_fromUtf8("frameStackedWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameStackedWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.frameStackedWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pcDetails = QtGui.QWidget()
        self.pcDetails.setObjectName(_fromUtf8("pcDetails"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pcDetails)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.framePcMain = QtGui.QFrame(self.pcDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcMain.sizePolicy().hasHeightForWidth())
        self.framePcMain.setSizePolicy(sizePolicy)
        self.framePcMain.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.framePcMain.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcMain.setObjectName(_fromUtf8("framePcMain"))
        self.framePcDetails = QtGui.QFrame(self.framePcMain)
        self.framePcDetails.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.framePcDetails.setFrameShape(QtGui.QFrame.Box)
        self.framePcDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcDetails.setObjectName(_fromUtf8("framePcDetails"))
        self.framePcAddressDetails = QtGui.QFrame(self.framePcDetails)
        self.framePcAddressDetails.setGeometry(QtCore.QRect(20, 30, 371, 191))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcAddressDetails.sizePolicy().hasHeightForWidth())
        self.framePcAddressDetails.setSizePolicy(sizePolicy)
        self.framePcAddressDetails.setFrameShape(QtGui.QFrame.Box)
        self.framePcAddressDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcAddressDetails.setObjectName(_fromUtf8("framePcAddressDetails"))
        self.gridLayout_7 = QtGui.QGridLayout(self.framePcAddressDetails)
        self.gridLayout_7.setContentsMargins(10, -1, 12, -1)
        self.gridLayout_7.setHorizontalSpacing(60)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelPcPhysicalAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcPhysicalAddress.setObjectName(_fromUtf8("labelPcPhysicalAddress"))
        self.gridLayout_7.addWidget(self.labelPcPhysicalAddress, 1, 0, 1, 1)
        self.labelPcIpAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcIpAddress.setObjectName(_fromUtf8("labelPcIpAddress"))
        self.gridLayout_7.addWidget(self.labelPcIpAddress, 2, 0, 1, 1)
        self.textBrowserPcDefaultGateway = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcDefaultGateway.setObjectName(_fromUtf8("textBrowserPcDefaultGateway"))
        self.gridLayout_7.addWidget(self.textBrowserPcDefaultGateway, 4, 1, 1, 1)
        self.labelPcDefaultGateway = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcDefaultGateway.setObjectName(_fromUtf8("labelPcDefaultGateway"))
        self.gridLayout_7.addWidget(self.labelPcDefaultGateway, 4, 0, 1, 1)
        self.textBrowserPcSubnetMask = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcSubnetMask.setObjectName(_fromUtf8("textBrowserPcSubnetMask"))
        self.gridLayout_7.addWidget(self.textBrowserPcSubnetMask, 3, 1, 1, 1)
        self.textBrowserPcIpAddress = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcIpAddress.setObjectName(_fromUtf8("textBrowserPcIpAddress"))
        self.gridLayout_7.addWidget(self.textBrowserPcIpAddress, 2, 1, 1, 1)
        self.labelPcSubnetMask = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcSubnetMask.setObjectName(_fromUtf8("labelPcSubnetMask"))
        self.gridLayout_7.addWidget(self.labelPcSubnetMask, 3, 0, 1, 1)
        self.textBrowserPcPhysicalAddress = QtGui.QTextBrowser(self.framePcAddressDetails)
        self.textBrowserPcPhysicalAddress.setObjectName(_fromUtf8("textBrowserPcPhysicalAddress"))
        self.gridLayout_7.addWidget(self.textBrowserPcPhysicalAddress, 1, 1, 1, 1)
        self.gridLayout_7.setColumnMinimumWidth(0, 100)
        self.pushButtonPc = QtGui.QPushButton(self.framePcDetails)
        self.pushButtonPc.setGeometry(QtCore.QRect(260, 240, 121, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPc.sizePolicy().hasHeightForWidth())
        self.pushButtonPc.setSizePolicy(sizePolicy)
        self.pushButtonPc.setObjectName(_fromUtf8("pushButtonPc"))
        self.tcpIpDetailsLabel = QtGui.QLabel(self.framePcMain)
        self.tcpIpDetailsLabel.setGeometry(QtCore.QRect(150, 10, 81, 21))
        self.tcpIpDetailsLabel.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tcpIpDetailsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpIpDetailsLabel.setObjectName(_fromUtf8("tcpIpDetailsLabel"))
        self.gridLayout_4.addWidget(self.framePcMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pcDetails)
        self.localModems = QtGui.QWidget()
        self.localModems.setObjectName(_fromUtf8("localModems"))
        self.gridLayout_5 = QtGui.QGridLayout(self.localModems)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frameLocalMain = QtGui.QFrame(self.localModems)
        self.frameLocalMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLocalMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLocalMain.setObjectName(_fromUtf8("frameLocalMain"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frameLocalMain)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabLocalDevDetails = QtGui.QTabWidget(self.frameLocalMain)
        self.tabLocalDevDetails.setEnabled(True)
        self.tabLocalDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabLocalDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabLocalDevDetails.setIconSize(QtCore.QSize(16, 16))
        self.tabLocalDevDetails.setTabsClosable(False)
        self.tabLocalDevDetails.setObjectName(_fromUtf8("tabLocalDevDetails"))
        self.localDevNetworkDetails = QtGui.QWidget()
        self.localDevNetworkDetails.setObjectName(_fromUtf8("localDevNetworkDetails"))
        self.frameLocalDev = QtGui.QFrame(self.localDevNetworkDetails)
        self.frameLocalDev.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.frameLocalDev.setToolTip(_fromUtf8(""))
        self.frameLocalDev.setAccessibleDescription(_fromUtf8(""))
        self.frameLocalDev.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDev.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDev.setObjectName(_fromUtf8("frameLocalDev"))
        self.listWidgetLocalRouteTab = QtGui.QListWidget(self.frameLocalDev)
        self.listWidgetLocalRouteTab.setGeometry(QtCore.QRect(20, 400, 351, 81))
        self.listWidgetLocalRouteTab.setFrameShape(QtGui.QFrame.Box)
        self.listWidgetLocalRouteTab.setObjectName(_fromUtf8("listWidgetLocalRouteTab"))
        self.labelLocalRouteTable = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalRouteTable.setGeometry(QtCore.QRect(29, 390, 81, 20))
        self.labelLocalRouteTable.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalRouteTable.setObjectName(_fromUtf8("labelLocalRouteTable"))
        self.labelLocalBackupRouteTable = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalBackupRouteTable.setGeometry(QtCore.QRect(30, 500, 131, 21))
        self.labelLocalBackupRouteTable.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalBackupRouteTable.setObjectName(_fromUtf8("labelLocalBackupRouteTable"))
        self.listWidgetLocalBackupRoutTab = QtGui.QListWidget(self.frameLocalDev)
        self.listWidgetLocalBackupRoutTab.setGeometry(QtCore.QRect(20, 510, 351, 81))
        self.listWidgetLocalBackupRoutTab.setFrameShape(QtGui.QFrame.Box)
        self.listWidgetLocalBackupRoutTab.setObjectName(_fromUtf8("listWidgetLocalBackupRoutTab"))
        self.frameLocalEth0 = QtGui.QFrame(self.frameLocalDev)
        self.frameLocalEth0.setGeometry(QtCore.QRect(20, 50, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalEth0.sizePolicy().hasHeightForWidth())
        self.frameLocalEth0.setSizePolicy(sizePolicy)
        self.frameLocalEth0.setAutoFillBackground(False)
        self.frameLocalEth0.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalEth0.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalEth0.setLineWidth(1)
        self.frameLocalEth0.setObjectName(_fromUtf8("frameLocalEth0"))
        self.Eth0Local = QtGui.QGridLayout(self.frameLocalEth0)
        self.Eth0Local.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local.setHorizontalSpacing(60)
        self.Eth0Local.setVerticalSpacing(6)
        self.Eth0Local.setObjectName(_fromUtf8("Eth0Local"))
        self.labelLocalEth0Ip = QtGui.QLabel(self.frameLocalEth0)
        self.labelLocalEth0Ip.setObjectName(_fromUtf8("labelLocalEth0Ip"))
        self.Eth0Local.addWidget(self.labelLocalEth0Ip, 0, 0, 1, 1)
        self.textBrowserLocalEth0Ip = QtGui.QTextBrowser(self.frameLocalEth0)
        self.textBrowserLocalEth0Ip.setObjectName(_fromUtf8("textBrowserLocalEth0Ip"))
        self.Eth0Local.addWidget(self.textBrowserLocalEth0Ip, 0, 1, 1, 1)
        self.labelLocalEth0Mac = QtGui.QLabel(self.frameLocalEth0)
        self.labelLocalEth0Mac.setObjectName(_fromUtf8("labelLocalEth0Mac"))
        self.Eth0Local.addWidget(self.labelLocalEth0Mac, 1, 0, 1, 1)
        self.textBrowserLocalEth0Mac = QtGui.QTextBrowser(self.frameLocalEth0)
        self.textBrowserLocalEth0Mac.setObjectName(_fromUtf8("textBrowserLocalEth0Mac"))
        self.Eth0Local.addWidget(self.textBrowserLocalEth0Mac, 1, 1, 1, 1)
        self.labelLocalEth0 = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalEth0.setGeometry(QtCore.QRect(30, 40, 41, 21))
        self.labelLocalEth0.setScaledContents(False)
        self.labelLocalEth0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalEth0.setObjectName(_fromUtf8("labelLocalEth0"))
        self.frameLocalFifo0 = QtGui.QFrame(self.frameLocalDev)
        self.frameLocalFifo0.setGeometry(QtCore.QRect(20, 160, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalFifo0.sizePolicy().hasHeightForWidth())
        self.frameLocalFifo0.setSizePolicy(sizePolicy)
        self.frameLocalFifo0.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalFifo0.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalFifo0.setLineWidth(1)
        self.frameLocalFifo0.setObjectName(_fromUtf8("frameLocalFifo0"))
        self.Eth0Local_2 = QtGui.QGridLayout(self.frameLocalFifo0)
        self.Eth0Local_2.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_2.setHorizontalSpacing(60)
        self.Eth0Local_2.setObjectName(_fromUtf8("Eth0Local_2"))
        self.labelLocalFifo0Ip = QtGui.QLabel(self.frameLocalFifo0)
        self.labelLocalFifo0Ip.setObjectName(_fromUtf8("labelLocalFifo0Ip"))
        self.Eth0Local_2.addWidget(self.labelLocalFifo0Ip, 0, 0, 1, 1)
        self.textBrowserLocalFifo0Ip = QtGui.QTextBrowser(self.frameLocalFifo0)
        self.textBrowserLocalFifo0Ip.setObjectName(_fromUtf8("textBrowserLocalFifo0Ip"))
        self.Eth0Local_2.addWidget(self.textBrowserLocalFifo0Ip, 0, 1, 1, 1)
        self.labelLocalFifo0Mac = QtGui.QLabel(self.frameLocalFifo0)
        self.labelLocalFifo0Mac.setObjectName(_fromUtf8("labelLocalFifo0Mac"))
        self.Eth0Local_2.addWidget(self.labelLocalFifo0Mac, 1, 0, 1, 1)
        self.textBrowserLocalFifo0Mac = QtGui.QTextBrowser(self.frameLocalFifo0)
        self.textBrowserLocalFifo0Mac.setObjectName(_fromUtf8("textBrowserLocalFifo0Mac"))
        self.Eth0Local_2.addWidget(self.textBrowserLocalFifo0Mac, 1, 1, 1, 1)
        self.labelLocalFifo0 = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalFifo0.setGeometry(QtCore.QRect(30, 150, 41, 21))
        self.labelLocalFifo0.setScaledContents(False)
        self.labelLocalFifo0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalFifo0.setObjectName(_fromUtf8("labelLocalFifo0"))
        self.labelLocalFifo1 = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalFifo1.setGeometry(QtCore.QRect(30, 260, 41, 21))
        self.labelLocalFifo1.setScaledContents(False)
        self.labelLocalFifo1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalFifo1.setObjectName(_fromUtf8("labelLocalFifo1"))
        self.frameLocalFifo1 = QtGui.QFrame(self.frameLocalDev)
        self.frameLocalFifo1.setGeometry(QtCore.QRect(20, 270, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalFifo1.sizePolicy().hasHeightForWidth())
        self.frameLocalFifo1.setSizePolicy(sizePolicy)
        self.frameLocalFifo1.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalFifo1.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalFifo1.setLineWidth(1)
        self.frameLocalFifo1.setObjectName(_fromUtf8("frameLocalFifo1"))
        self.Eth0Local_15 = QtGui.QGridLayout(self.frameLocalFifo1)
        self.Eth0Local_15.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_15.setHorizontalSpacing(60)
        self.Eth0Local_15.setObjectName(_fromUtf8("Eth0Local_15"))
        self.labelLocalFifo1Ip = QtGui.QLabel(self.frameLocalFifo1)
        self.labelLocalFifo1Ip.setObjectName(_fromUtf8("labelLocalFifo1Ip"))
        self.Eth0Local_15.addWidget(self.labelLocalFifo1Ip, 0, 0, 1, 1)
        self.textBrowserLocalFifo1Ip = QtGui.QTextBrowser(self.frameLocalFifo1)
        self.textBrowserLocalFifo1Ip.setObjectName(_fromUtf8("textBrowserLocalFifo1Ip"))
        self.Eth0Local_15.addWidget(self.textBrowserLocalFifo1Ip, 0, 1, 1, 1)
        self.labelLocalFifo1Mac = QtGui.QLabel(self.frameLocalFifo1)
        self.labelLocalFifo1Mac.setObjectName(_fromUtf8("labelLocalFifo1Mac"))
        self.Eth0Local_15.addWidget(self.labelLocalFifo1Mac, 1, 0, 1, 1)
        self.textBrowserLocalFifo1Mac = QtGui.QTextBrowser(self.frameLocalFifo1)
        self.textBrowserLocalFifo1Mac.setObjectName(_fromUtf8("textBrowserLocalFifo1Mac"))
        self.Eth0Local_15.addWidget(self.textBrowserLocalFifo1Mac, 1, 1, 1, 1)
        self.listWidgetLocalRouteTab.raise_()
        self.labelLocalRouteTable.raise_()
        self.listWidgetLocalBackupRoutTab.raise_()
        self.frameLocalEth0.raise_()
        self.frameLocalFifo0.raise_()
        self.labelLocalFifo0.raise_()
        self.labelLocalBackupRouteTable.raise_()
        self.labelLocalEth0.raise_()
        self.frameLocalFifo1.raise_()
        self.labelLocalFifo1.raise_()
        self.labelLocalDeviceDetails = QtGui.QLabel(self.localDevNetworkDetails)
        self.labelLocalDeviceDetails.setGeometry(QtCore.QRect(150, 10, 111, 21))
        self.labelLocalDeviceDetails.setScaledContents(False)
        self.labelLocalDeviceDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDeviceDetails.setObjectName(_fromUtf8("labelLocalDeviceDetails"))
        self.tabLocalDevDetails.addTab(self.localDevNetworkDetails, _fromUtf8(""))
        self.localDevSoftwareDetails = QtGui.QWidget()
        self.localDevSoftwareDetails.setObjectName(_fromUtf8("localDevSoftwareDetails"))
        self.frameLocalSoftware = QtGui.QFrame(self.localDevSoftwareDetails)
        self.frameLocalSoftware.setGeometry(QtCore.QRect(10, 20, 411, 621))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalSoftware.setSizePolicy(sizePolicy)
        self.frameLocalSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalSoftware.setObjectName(_fromUtf8("frameLocalSoftware"))
        self.frameLocalDefSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDefSoftware.setGeometry(QtCore.QRect(20, 50, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDefSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDefSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDefSoftware.setAutoFillBackground(False)
        self.frameLocalDefSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDefSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDefSoftware.setLineWidth(1)
        self.frameLocalDefSoftware.setObjectName(_fromUtf8("frameLocalDefSoftware"))
        self.Eth0Local_7 = QtGui.QGridLayout(self.frameLocalDefSoftware)
        self.Eth0Local_7.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_7.setHorizontalSpacing(60)
        self.Eth0Local_7.setObjectName(_fromUtf8("Eth0Local_7"))
        self.labelLocalDefSoftVersion = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftVersion.setObjectName(_fromUtf8("labelLocalDefSoftVersion"))
        self.Eth0Local_7.addWidget(self.labelLocalDefSoftVersion, 0, 0, 1, 1)
        self.textBrowserLocalDefSoftVersion = QtGui.QTextBrowser(self.frameLocalDefSoftware)
        self.textBrowserLocalDefSoftVersion.setObjectName(_fromUtf8("textBrowserLocalDefSoftVersion"))
        self.Eth0Local_7.addWidget(self.textBrowserLocalDefSoftVersion, 0, 1, 1, 1)
        self.labelLocalDefSoftCrc = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftCrc.setObjectName(_fromUtf8("labelLocalDefSoftCrc"))
        self.Eth0Local_7.addWidget(self.labelLocalDefSoftCrc, 1, 0, 1, 1)
        self.textBrowserLocalDefSoftCrc = QtGui.QTextBrowser(self.frameLocalDefSoftware)
        self.textBrowserLocalDefSoftCrc.setObjectName(_fromUtf8("textBrowserLocalDefSoftCrc"))
        self.Eth0Local_7.addWidget(self.textBrowserLocalDefSoftCrc, 1, 1, 1, 1)
        self.labelLocalDefaultSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDefaultSoftware.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.labelLocalDefaultSoftware.setScaledContents(False)
        self.labelLocalDefaultSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDefaultSoftware.setObjectName(_fromUtf8("labelLocalDefaultSoftware"))
        self.frameLocalUpdSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalUpdSoftware.setGeometry(QtCore.QRect(20, 160, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalUpdSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalUpdSoftware.setSizePolicy(sizePolicy)
        self.frameLocalUpdSoftware.setAutoFillBackground(False)
        self.frameLocalUpdSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalUpdSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalUpdSoftware.setLineWidth(1)
        self.frameLocalUpdSoftware.setObjectName(_fromUtf8("frameLocalUpdSoftware"))
        self.Eth0Local_9 = QtGui.QGridLayout(self.frameLocalUpdSoftware)
        self.Eth0Local_9.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_9.setHorizontalSpacing(60)
        self.Eth0Local_9.setObjectName(_fromUtf8("Eth0Local_9"))
        self.labelLocalUpdSoftVersion = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftVersion.setObjectName(_fromUtf8("labelLocalUpdSoftVersion"))
        self.Eth0Local_9.addWidget(self.labelLocalUpdSoftVersion, 0, 0, 1, 1)
        self.textBrowserLocalUpdSoftVersion = QtGui.QTextBrowser(self.frameLocalUpdSoftware)
        self.textBrowserLocalUpdSoftVersion.setObjectName(_fromUtf8("textBrowserLocalUpdSoftVersion"))
        self.Eth0Local_9.addWidget(self.textBrowserLocalUpdSoftVersion, 0, 1, 1, 1)
        self.labelLocalUpdSoftCrc = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftCrc.setObjectName(_fromUtf8("labelLocalUpdSoftCrc"))
        self.Eth0Local_9.addWidget(self.labelLocalUpdSoftCrc, 1, 0, 1, 1)
        self.textBrowserLocalUpdSoftCrc = QtGui.QTextBrowser(self.frameLocalUpdSoftware)
        self.textBrowserLocalUpdSoftCrc.setObjectName(_fromUtf8("textBrowserLocalUpdSoftCrc"))
        self.Eth0Local_9.addWidget(self.textBrowserLocalUpdSoftCrc, 1, 1, 1, 1)
        self.labelLocalUpdateSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalUpdateSoftware.setGeometry(QtCore.QRect(30, 150, 111, 21))
        self.labelLocalUpdateSoftware.setScaledContents(False)
        self.labelLocalUpdateSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalUpdateSoftware.setObjectName(_fromUtf8("labelLocalUpdateSoftware"))
        self.frameLocalDspSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspSoftware.setGeometry(QtCore.QRect(20, 270, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDspSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDspSoftware.setAutoFillBackground(False)
        self.frameLocalDspSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspSoftware.setLineWidth(1)
        self.frameLocalDspSoftware.setObjectName(_fromUtf8("frameLocalDspSoftware"))
        self.Eth0Local_10 = QtGui.QGridLayout(self.frameLocalDspSoftware)
        self.Eth0Local_10.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_10.setHorizontalSpacing(60)
        self.Eth0Local_10.setObjectName(_fromUtf8("Eth0Local_10"))
        self.labelLocalDspSoftVersion = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftVersion.setObjectName(_fromUtf8("labelLocalDspSoftVersion"))
        self.Eth0Local_10.addWidget(self.labelLocalDspSoftVersion, 0, 0, 1, 1)
        self.textBrowserLocalDspSoftVersion = QtGui.QTextBrowser(self.frameLocalDspSoftware)
        self.textBrowserLocalDspSoftVersion.setObjectName(_fromUtf8("textBrowserLocalDspSoftVersion"))
        self.Eth0Local_10.addWidget(self.textBrowserLocalDspSoftVersion, 0, 1, 1, 1)
        self.labelLocalDspSoftCrc = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftCrc.setObjectName(_fromUtf8("labelLocalDspSoftCrc"))
        self.Eth0Local_10.addWidget(self.labelLocalDspSoftCrc, 1, 0, 1, 1)
        self.textBrowserLocalDspSoftCrc = QtGui.QTextBrowser(self.frameLocalDspSoftware)
        self.textBrowserLocalDspSoftCrc.setObjectName(_fromUtf8("textBrowserLocalDspSoftCrc"))
        self.Eth0Local_10.addWidget(self.textBrowserLocalDspSoftCrc, 1, 1, 1, 1)
        self.labelLocalDspSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspSoftware.setGeometry(QtCore.QRect(30, 260, 91, 21))
        self.labelLocalDspSoftware.setScaledContents(False)
        self.labelLocalDspSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspSoftware.setObjectName(_fromUtf8("labelLocalDspSoftware"))
        self.frameLocalDspConfig = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspConfig.setGeometry(QtCore.QRect(20, 380, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspConfig.sizePolicy().hasHeightForWidth())
        self.frameLocalDspConfig.setSizePolicy(sizePolicy)
        self.frameLocalDspConfig.setAutoFillBackground(False)
        self.frameLocalDspConfig.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspConfig.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspConfig.setLineWidth(1)
        self.frameLocalDspConfig.setObjectName(_fromUtf8("frameLocalDspConfig"))
        self.Eth0Local_11 = QtGui.QGridLayout(self.frameLocalDspConfig)
        self.Eth0Local_11.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_11.setHorizontalSpacing(60)
        self.Eth0Local_11.setObjectName(_fromUtf8("Eth0Local_11"))
        self.labelLocalDspConfVersion = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfVersion.setObjectName(_fromUtf8("labelLocalDspConfVersion"))
        self.Eth0Local_11.addWidget(self.labelLocalDspConfVersion, 0, 0, 1, 1)
        self.textBrowserLocalDspConfVersion = QtGui.QTextBrowser(self.frameLocalDspConfig)
        self.textBrowserLocalDspConfVersion.setObjectName(_fromUtf8("textBrowserLocalDspConfVersion"))
        self.Eth0Local_11.addWidget(self.textBrowserLocalDspConfVersion, 0, 1, 1, 1)
        self.labelLocalDspConfCrc = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfCrc.setObjectName(_fromUtf8("labelLocalDspConfCrc"))
        self.Eth0Local_11.addWidget(self.labelLocalDspConfCrc, 1, 0, 1, 1)
        self.textBrowserLocalDspConfCrc = QtGui.QTextBrowser(self.frameLocalDspConfig)
        self.textBrowserLocalDspConfCrc.setObjectName(_fromUtf8("textBrowserLocalDspConfCrc"))
        self.Eth0Local_11.addWidget(self.textBrowserLocalDspConfCrc, 1, 1, 1, 1)
        self.labelLocalDspConfig = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspConfig.setGeometry(QtCore.QRect(30, 370, 81, 21))
        self.labelLocalDspConfig.setScaledContents(False)
        self.labelLocalDspConfig.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspConfig.setObjectName(_fromUtf8("labelLocalDspConfig"))
        self.labelLocalDevSoftwareDetails = QtGui.QLabel(self.localDevSoftwareDetails)
        self.labelLocalDevSoftwareDetails.setGeometry(QtCore.QRect(120, 10, 191, 21))
        self.labelLocalDevSoftwareDetails.setScaledContents(False)
        self.labelLocalDevSoftwareDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDevSoftwareDetails.setObjectName(_fromUtf8("labelLocalDevSoftwareDetails"))
        self.tabLocalDevDetails.addTab(self.localDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabLocalDevDetails, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frameLocalMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.localModems)
        self.remoteModems = QtGui.QWidget()
        self.remoteModems.setObjectName(_fromUtf8("remoteModems"))
        self.gridLayout_6 = QtGui.QGridLayout(self.remoteModems)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frameRemoteDev = QtGui.QFrame(self.remoteModems)
        self.frameRemoteDev.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRemoteDev.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRemoteDev.setObjectName(_fromUtf8("frameRemoteDev"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frameRemoteDev)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabRemoteDevDetails = QtGui.QTabWidget(self.frameRemoteDev)
        self.tabRemoteDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabRemoteDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabRemoteDevDetails.setTabsClosable(False)
        self.tabRemoteDevDetails.setObjectName(_fromUtf8("tabRemoteDevDetails"))
        self.remoteDevNetworkDetails = QtGui.QWidget()
        self.remoteDevNetworkDetails.setObjectName(_fromUtf8("remoteDevNetworkDetails"))
        self.frame_6 = QtGui.QFrame(self.remoteDevNetworkDetails)
        self.frame_6.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.frame_6.setToolTip(_fromUtf8(""))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.listWidget_5 = QtGui.QListWidget(self.frame_6)
        self.listWidget_5.setGeometry(QtCore.QRect(20, 390, 351, 81))
        self.listWidget_5.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.label_31 = QtGui.QLabel(self.frame_6)
        self.label_31.setGeometry(QtCore.QRect(29, 390, 81, 20))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.frame_6)
        self.label_32.setGeometry(QtCore.QRect(30, 500, 131, 21))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.listWidget_6 = QtGui.QListWidget(self.frame_6)
        self.listWidget_6.setGeometry(QtCore.QRect(20, 510, 351, 81))
        self.listWidget_6.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_6.setObjectName(_fromUtf8("listWidget_6"))
        self.frame_14 = QtGui.QFrame(self.frame_6)
        self.frame_14.setGeometry(QtCore.QRect(20, 50, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setAutoFillBackground(False)
        self.frame_14.setFrameShape(QtGui.QFrame.Box)
        self.frame_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_14.setLineWidth(1)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.Eth0Local_12 = QtGui.QGridLayout(self.frame_14)
        self.Eth0Local_12.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_12.setHorizontalSpacing(60)
        self.Eth0Local_12.setVerticalSpacing(6)
        self.Eth0Local_12.setObjectName(_fromUtf8("Eth0Local_12"))
        self.label_33 = QtGui.QLabel(self.frame_14)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.Eth0Local_12.addWidget(self.label_33, 0, 0, 1, 1)
        self.textBrowser_19 = QtGui.QTextBrowser(self.frame_14)
        self.textBrowser_19.setObjectName(_fromUtf8("textBrowser_19"))
        self.Eth0Local_12.addWidget(self.textBrowser_19, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.frame_14)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.Eth0Local_12.addWidget(self.label_34, 1, 0, 1, 1)
        self.textBrowser_20 = QtGui.QTextBrowser(self.frame_14)
        self.textBrowser_20.setObjectName(_fromUtf8("textBrowser_20"))
        self.Eth0Local_12.addWidget(self.textBrowser_20, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(30, 40, 41, 21))
        self.label_35.setScaledContents(False)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.frame_15 = QtGui.QFrame(self.frame_6)
        self.frame_15.setGeometry(QtCore.QRect(20, 160, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtGui.QFrame.Box)
        self.frame_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_15.setLineWidth(1)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.Eth0Local_13 = QtGui.QGridLayout(self.frame_15)
        self.Eth0Local_13.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_13.setHorizontalSpacing(60)
        self.Eth0Local_13.setObjectName(_fromUtf8("Eth0Local_13"))
        self.label_36 = QtGui.QLabel(self.frame_15)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.Eth0Local_13.addWidget(self.label_36, 0, 0, 1, 1)
        self.textBrowser_21 = QtGui.QTextBrowser(self.frame_15)
        self.textBrowser_21.setObjectName(_fromUtf8("textBrowser_21"))
        self.Eth0Local_13.addWidget(self.textBrowser_21, 0, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.frame_15)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.Eth0Local_13.addWidget(self.label_51, 1, 0, 1, 1)
        self.textBrowser_22 = QtGui.QTextBrowser(self.frame_15)
        self.textBrowser_22.setObjectName(_fromUtf8("textBrowser_22"))
        self.Eth0Local_13.addWidget(self.textBrowser_22, 1, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.frame_6)
        self.label_52.setGeometry(QtCore.QRect(30, 150, 41, 21))
        self.label_52.setScaledContents(False)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_55 = QtGui.QLabel(self.frame_6)
        self.label_55.setGeometry(QtCore.QRect(30, 260, 41, 21))
        self.label_55.setScaledContents(False)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.frame_16 = QtGui.QFrame(self.frame_6)
        self.frame_16.setGeometry(QtCore.QRect(20, 270, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtGui.QFrame.Box)
        self.frame_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_16.setLineWidth(1)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.Eth0Local_14 = QtGui.QGridLayout(self.frame_16)
        self.Eth0Local_14.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_14.setHorizontalSpacing(60)
        self.Eth0Local_14.setObjectName(_fromUtf8("Eth0Local_14"))
        self.label_40 = QtGui.QLabel(self.frame_16)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.Eth0Local_14.addWidget(self.label_40, 0, 0, 1, 1)
        self.textBrowser_23 = QtGui.QTextBrowser(self.frame_16)
        self.textBrowser_23.setObjectName(_fromUtf8("textBrowser_23"))
        self.Eth0Local_14.addWidget(self.textBrowser_23, 0, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.frame_16)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.Eth0Local_14.addWidget(self.label_53, 1, 0, 1, 1)
        self.textBrowser_24 = QtGui.QTextBrowser(self.frame_16)
        self.textBrowser_24.setObjectName(_fromUtf8("textBrowser_24"))
        self.Eth0Local_14.addWidget(self.textBrowser_24, 1, 1, 1, 1)
        self.listWidget_5.raise_()
        self.label_31.raise_()
        self.listWidget_6.raise_()
        self.frame_14.raise_()
        self.label_35.raise_()
        self.frame_15.raise_()
        self.label_52.raise_()
        self.label_32.raise_()
        self.frame_16.raise_()
        self.label_55.raise_()
        self.label_56 = QtGui.QLabel(self.remoteDevNetworkDetails)
        self.label_56.setGeometry(QtCore.QRect(130, 10, 151, 21))
        self.label_56.setScaledContents(False)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.tabRemoteDevDetails.addTab(self.remoteDevNetworkDetails, _fromUtf8(""))
        self.remoteDevSoftwareDetails = QtGui.QWidget()
        self.remoteDevSoftwareDetails.setObjectName(_fromUtf8("remoteDevSoftwareDetails"))
        self.tabRemoteDevDetails.addTab(self.remoteDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabRemoteDevDetails, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frameRemoteDev, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.remoteModems)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_2.addWidget(self.frameStackedWidget, 0, 1, 1, 1)
        self.frameTree = QtGui.QFrame(self.MainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTree.sizePolicy().hasHeightForWidth())
        self.frameTree.setSizePolicy(sizePolicy)
        self.frameTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frameTree.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTree.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTree.setObjectName(_fromUtf8("frameTree"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameTree)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.frameTree)
        self.treeWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item_1.setFont(0, font)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setMinimumSectionSize(30)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frameTree, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.MainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabLocalDevDetails.setCurrentIndex(0)
        self.tabRemoteDevDetails.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelPcPhysicalAddress.setText(_translate("MainWindow", "Physical Address", None))
        self.labelPcIpAddress.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowserPcDefaultGateway.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.1</span></p></body></html>", None))
        self.labelPcDefaultGateway.setText(_translate("MainWindow", "Default Gateway", None))
        self.textBrowserPcSubnetMask.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.textBrowserPcIpAddress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.labelPcSubnetMask.setText(_translate("MainWindow", "Subnet Mask", None))
        self.textBrowserPcPhysicalAddress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.pushButtonPc.setText(_translate("MainWindow", "PushButton", None))
        self.tcpIpDetailsLabel.setText(_translate("MainWindow", "TCP/IP Details", None))
        self.labelLocalRouteTable.setText(_translate("MainWindow", "Route Table", None))
        self.labelLocalBackupRouteTable.setText(_translate("MainWindow", "Backup Route Table", None))
        self.labelLocalEth0Ip.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowserLocalEth0Ip.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.labelLocalEth0Mac.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowserLocalEth0Mac.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.labelLocalEth0.setText(_translate("MainWindow", "Eth0", None))
        self.labelLocalFifo0Ip.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowserLocalFifo0Ip.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.labelLocalFifo0Mac.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowserLocalFifo0Mac.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.labelLocalFifo0.setText(_translate("MainWindow", "Fifo0", None))
        self.labelLocalFifo1.setText(_translate("MainWindow", "Fifo1", None))
        self.labelLocalFifo1Ip.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowserLocalFifo1Ip.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.labelLocalFifo1Mac.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowserLocalFifo1Mac.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.labelLocalDeviceDetails.setText(_translate("MainWindow", "Local Device Details", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.labelLocalDefSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.textBrowserLocalDefSoftVersion.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalDefSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowserLocalDefSoftCrc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalDefaultSoftware.setText(_translate("MainWindow", "Default Software", None))
        self.labelLocalUpdSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.textBrowserLocalUpdSoftVersion.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalUpdSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowserLocalUpdSoftCrc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalUpdateSoftware.setText(_translate("MainWindow", "Update Software", None))
        self.labelLocalDspSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.textBrowserLocalDspSoftVersion.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalDspSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowserLocalDspSoftCrc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalDspSoftware.setText(_translate("MainWindow", "DSP Software", None))
        self.labelLocalDspConfVersion.setText(_translate("MainWindow", "Version", None))
        self.textBrowserLocalDspConfVersion.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalDspConfCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.textBrowserLocalDspConfCrc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\'; font-size:13pt;\"><br /></p></body></html>", None))
        self.labelLocalDspConfig.setText(_translate("MainWindow", "DSP Config", None))
        self.labelLocalDevSoftwareDetails.setText(_translate("MainWindow", "Local Device Software Setails", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.label_31.setText(_translate("MainWindow", "Route Table", None))
        self.label_32.setText(_translate("MainWindow", "Backup Route Table", None))
        self.label_33.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "Eth0", None))
        self.label_36.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_51.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_52.setText(_translate("MainWindow", "Fifo0", None))
        self.label_55.setText(_translate("MainWindow", "Fifo1", None))
        self.label_40.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_23.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_53.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_24.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_56.setText(_translate("MainWindow", "Remote Device Details", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Network Devices", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "PC", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "TopSide Modem 2", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "Subsea Modem 2.1", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Subsea Modem 2.2", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "TopSide Modem 1", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Subsea Modem 1.1", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Subsea Modem 1.2", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

