# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModSetupWithTreeV02.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(678, 616)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.MainFrame = QtGui.QFrame(self.centralwidget)
        self.MainFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainFrame.setObjectName(_fromUtf8("MainFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.MainFrame)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frameStackedWidget = QtGui.QFrame(self.MainFrame)
        self.frameStackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameStackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.frameStackedWidget.setObjectName(_fromUtf8("frameStackedWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameStackedWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.frameStackedWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pcDetails = QtGui.QWidget()
        self.pcDetails.setObjectName(_fromUtf8("pcDetails"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pcDetails)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.framePcMain = QtGui.QFrame(self.pcDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcMain.sizePolicy().hasHeightForWidth())
        self.framePcMain.setSizePolicy(sizePolicy)
        self.framePcMain.setStyleSheet(_fromUtf8("background-color:rgb(255, 255, 255)"))
        self.framePcMain.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcMain.setObjectName(_fromUtf8("framePcMain"))
        self.framePcDetails = QtGui.QFrame(self.framePcMain)
        self.framePcDetails.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.framePcDetails.setFrameShape(QtGui.QFrame.Box)
        self.framePcDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcDetails.setObjectName(_fromUtf8("framePcDetails"))
        self.framePcAddressDetails = QtGui.QFrame(self.framePcDetails)
        self.framePcAddressDetails.setGeometry(QtCore.QRect(20, 30, 371, 141))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcAddressDetails.sizePolicy().hasHeightForWidth())
        self.framePcAddressDetails.setSizePolicy(sizePolicy)
        self.framePcAddressDetails.setFrameShape(QtGui.QFrame.Box)
        self.framePcAddressDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcAddressDetails.setObjectName(_fromUtf8("framePcAddressDetails"))
        self.gridLayout_16 = QtGui.QGridLayout(self.framePcAddressDetails)
        self.gridLayout_16.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_16.setHorizontalSpacing(80)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.labelPcPhysicalAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcPhysicalAddress.setObjectName(_fromUtf8("labelPcPhysicalAddress"))
        self.gridLayout_16.addWidget(self.labelPcPhysicalAddress, 0, 0, 1, 1)
        self.labelPcSubnetMask = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcSubnetMask.setObjectName(_fromUtf8("labelPcSubnetMask"))
        self.gridLayout_16.addWidget(self.labelPcSubnetMask, 2, 0, 1, 1)
        self.labelPcIpAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcIpAddress.setObjectName(_fromUtf8("labelPcIpAddress"))
        self.gridLayout_16.addWidget(self.labelPcIpAddress, 1, 0, 1, 1)
        self.lineEditPcPhysicalAddress = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcPhysicalAddress.setEnabled(True)
        self.lineEditPcPhysicalAddress.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditPcPhysicalAddress.setText(_fromUtf8(""))
        self.lineEditPcPhysicalAddress.setReadOnly(True)
        self.lineEditPcPhysicalAddress.setObjectName(_fromUtf8("lineEditPcPhysicalAddress"))
        self.gridLayout_16.addWidget(self.lineEditPcPhysicalAddress, 0, 1, 1, 1)
        self.lineEditPcDefaultGateway = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcDefaultGateway.setReadOnly(True)
        self.lineEditPcDefaultGateway.setObjectName(_fromUtf8("lineEditPcDefaultGateway"))
        self.gridLayout_16.addWidget(self.lineEditPcDefaultGateway, 3, 1, 1, 1)
        self.labelPcDefaultGateway = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcDefaultGateway.setObjectName(_fromUtf8("labelPcDefaultGateway"))
        self.gridLayout_16.addWidget(self.labelPcDefaultGateway, 3, 0, 1, 1)
        self.lineEditPcSubnetMask = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcSubnetMask.setReadOnly(True)
        self.lineEditPcSubnetMask.setObjectName(_fromUtf8("lineEditPcSubnetMask"))
        self.gridLayout_16.addWidget(self.lineEditPcSubnetMask, 2, 1, 1, 1)
        self.lineEditPcIpAddress = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcIpAddress.setText(_fromUtf8(""))
        self.lineEditPcIpAddress.setReadOnly(True)
        self.lineEditPcIpAddress.setObjectName(_fromUtf8("lineEditPcIpAddress"))
        self.gridLayout_16.addWidget(self.lineEditPcIpAddress, 1, 1, 1, 1)
        self.pushButtonPc = QtGui.QPushButton(self.framePcDetails)
        self.pushButtonPc.setGeometry(QtCore.QRect(290, 200, 91, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPc.sizePolicy().hasHeightForWidth())
        self.pushButtonPc.setSizePolicy(sizePolicy)
        self.pushButtonPc.setObjectName(_fromUtf8("pushButtonPc"))
        self.tcpIpDetailsLabel = QtGui.QLabel(self.framePcDetails)
        self.tcpIpDetailsLabel.setGeometry(QtCore.QRect(150, 20, 81, 21))
        self.tcpIpDetailsLabel.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tcpIpDetailsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpIpDetailsLabel.setObjectName(_fromUtf8("tcpIpDetailsLabel"))
        self.gridLayout_4.addWidget(self.framePcMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pcDetails)
        self.localModems = QtGui.QWidget()
        self.localModems.setObjectName(_fromUtf8("localModems"))
        self.gridLayout_5 = QtGui.QGridLayout(self.localModems)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frameLocalMain = QtGui.QFrame(self.localModems)
        self.frameLocalMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLocalMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLocalMain.setObjectName(_fromUtf8("frameLocalMain"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frameLocalMain)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabLocalDevDetails = QtGui.QTabWidget(self.frameLocalMain)
        self.tabLocalDevDetails.setEnabled(True)
        self.tabLocalDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabLocalDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabLocalDevDetails.setIconSize(QtCore.QSize(16, 16))
        self.tabLocalDevDetails.setTabsClosable(False)
        self.tabLocalDevDetails.setObjectName(_fromUtf8("tabLocalDevDetails"))
        self.localDevNetworkDetails = QtGui.QWidget()
        self.localDevNetworkDetails.setObjectName(_fromUtf8("localDevNetworkDetails"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.localDevNetworkDetails)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frameLocalDev = QtGui.QFrame(self.localDevNetworkDetails)
        self.frameLocalDev.setToolTip(_fromUtf8(""))
        self.frameLocalDev.setAccessibleDescription(_fromUtf8(""))
        self.frameLocalDev.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDev.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDev.setLineWidth(1)
        self.frameLocalDev.setObjectName(_fromUtf8("frameLocalDev"))
        self.labelLocalRouteTable_2 = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalRouteTable_2.setGeometry(QtCore.QRect(30, 200, 71, 20))
        self.labelLocalRouteTable_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalRouteTable_2.setObjectName(_fromUtf8("labelLocalRouteTable_2"))
        self.labelLocalBackupRouteTable_2 = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalBackupRouteTable_2.setGeometry(QtCore.QRect(30, 330, 111, 16))
        self.labelLocalBackupRouteTable_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalBackupRouteTable_2.setObjectName(_fromUtf8("labelLocalBackupRouteTable_2"))
        self.textEditLocalBackRoute_2 = QtGui.QTextEdit(self.frameLocalDev)
        self.textEditLocalBackRoute_2.setGeometry(QtCore.QRect(18, 340, 321, 101))
        self.textEditLocalBackRoute_2.setFrameShape(QtGui.QFrame.Box)
        self.textEditLocalBackRoute_2.setReadOnly(True)
        self.textEditLocalBackRoute_2.setAcceptRichText(True)
        self.textEditLocalBackRoute_2.setObjectName(_fromUtf8("textEditLocalBackRoute_2"))
        self.textEditLocalRoute_2 = QtGui.QTextEdit(self.frameLocalDev)
        self.textEditLocalRoute_2.setGeometry(QtCore.QRect(18, 210, 321, 101))
        self.textEditLocalRoute_2.setFrameShape(QtGui.QFrame.Box)
        self.textEditLocalRoute_2.setReadOnly(True)
        self.textEditLocalRoute_2.setAcceptRichText(True)
        self.textEditLocalRoute_2.setObjectName(_fromUtf8("textEditLocalRoute_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.frameLocalDev)
        self.layoutWidget_2.setGeometry(QtCore.QRect(16, 30, 301, 161))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout_12.setHorizontalSpacing(50)
        self.gridLayout_12.setVerticalSpacing(6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.labelLocalEth0Ip_2 = QtGui.QLabel(self.layoutWidget_2)
        self.labelLocalEth0Ip_2.setObjectName(_fromUtf8("labelLocalEth0Ip_2"))
        self.gridLayout_12.addWidget(self.labelLocalEth0Ip_2, 0, 0, 1, 1)
        self.lineEditLocalEth0Ip_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditLocalEth0Ip_2.setText(_fromUtf8(""))
        self.lineEditLocalEth0Ip_2.setReadOnly(True)
        self.lineEditLocalEth0Ip_2.setObjectName(_fromUtf8("lineEditLocalEth0Ip_2"))
        self.gridLayout_12.addWidget(self.lineEditLocalEth0Ip_2, 0, 1, 1, 1)
        self.labelLocalEth0Mac_2 = QtGui.QLabel(self.layoutWidget_2)
        self.labelLocalEth0Mac_2.setObjectName(_fromUtf8("labelLocalEth0Mac_2"))
        self.gridLayout_12.addWidget(self.labelLocalEth0Mac_2, 1, 0, 1, 1)
        self.lineEditLocalEth0MacAddress_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditLocalEth0MacAddress_2.setReadOnly(True)
        self.lineEditLocalEth0MacAddress_2.setObjectName(_fromUtf8("lineEditLocalEth0MacAddress_2"))
        self.gridLayout_12.addWidget(self.lineEditLocalEth0MacAddress_2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_12)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout_13.setHorizontalSpacing(50)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.labelLocalFifo0Ip_2 = QtGui.QLabel(self.layoutWidget_2)
        self.labelLocalFifo0Ip_2.setObjectName(_fromUtf8("labelLocalFifo0Ip_2"))
        self.gridLayout_13.addWidget(self.labelLocalFifo0Ip_2, 0, 0, 1, 1)
        self.lineEditFifo0IpAddress_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditFifo0IpAddress_2.setReadOnly(True)
        self.lineEditFifo0IpAddress_2.setObjectName(_fromUtf8("lineEditFifo0IpAddress_2"))
        self.gridLayout_13.addWidget(self.lineEditFifo0IpAddress_2, 0, 1, 1, 1)
        self.labelLocalFifo0Mac_2 = QtGui.QLabel(self.layoutWidget_2)
        self.labelLocalFifo0Mac_2.setObjectName(_fromUtf8("labelLocalFifo0Mac_2"))
        self.gridLayout_13.addWidget(self.labelLocalFifo0Mac_2, 1, 0, 1, 1)
        self.lineEditLocalFifo0MacAddress_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditLocalFifo0MacAddress_2.setReadOnly(True)
        self.lineEditLocalFifo0MacAddress_2.setObjectName(_fromUtf8("lineEditLocalFifo0MacAddress_2"))
        self.gridLayout_13.addWidget(self.lineEditLocalFifo0MacAddress_2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_13)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout_14.setHorizontalSpacing(50)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.labelLocalFifo1Ip_2 = QtGui.QLabel(self.layoutWidget_2)
        self.labelLocalFifo1Ip_2.setObjectName(_fromUtf8("labelLocalFifo1Ip_2"))
        self.gridLayout_14.addWidget(self.labelLocalFifo1Ip_2, 0, 0, 1, 1)
        self.lineEditFifo1IpAddress_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditFifo1IpAddress_2.setReadOnly(True)
        self.lineEditFifo1IpAddress_2.setObjectName(_fromUtf8("lineEditFifo1IpAddress_2"))
        self.gridLayout_14.addWidget(self.lineEditFifo1IpAddress_2, 0, 1, 1, 1)
        self.labelLocalFifo1Mac_2 = QtGui.QLabel(self.layoutWidget_2)
        self.labelLocalFifo1Mac_2.setObjectName(_fromUtf8("labelLocalFifo1Mac_2"))
        self.gridLayout_14.addWidget(self.labelLocalFifo1Mac_2, 1, 0, 1, 1)
        self.lineEditLocalFifo1MacAddress_2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditLocalFifo1MacAddress_2.setReadOnly(True)
        self.lineEditLocalFifo1MacAddress_2.setObjectName(_fromUtf8("lineEditLocalFifo1MacAddress_2"))
        self.gridLayout_14.addWidget(self.lineEditLocalFifo1MacAddress_2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_14)
        self.labelLocalDeviceDetails = QtGui.QLabel(self.frameLocalDev)
        self.labelLocalDeviceDetails.setGeometry(QtCore.QRect(130, 0, 111, 21))
        self.labelLocalDeviceDetails.setScaledContents(False)
        self.labelLocalDeviceDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDeviceDetails.setObjectName(_fromUtf8("labelLocalDeviceDetails"))
        self.widget = QtGui.QWidget(self.frameLocalDev)
        self.widget.setGeometry(QtCore.QRect(18, 460, 381, 54))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.widget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 1, 3, 1, 1)
        self.textEditLocalBackRoute_2.raise_()
        self.textEditLocalRoute_2.raise_()
        self.layoutWidget_2.raise_()
        self.labelLocalRouteTable_2.raise_()
        self.labelLocalBackupRouteTable_2.raise_()
        self.labelLocalDeviceDetails.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.verticalLayout_5.addWidget(self.frameLocalDev)
        self.tabLocalDevDetails.addTab(self.localDevNetworkDetails, _fromUtf8(""))
        self.localDevSoftwareDetails = QtGui.QWidget()
        self.localDevSoftwareDetails.setObjectName(_fromUtf8("localDevSoftwareDetails"))
        self.frameLocalSoftware = QtGui.QFrame(self.localDevSoftwareDetails)
        self.frameLocalSoftware.setGeometry(QtCore.QRect(10, 20, 411, 621))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalSoftware.setSizePolicy(sizePolicy)
        self.frameLocalSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalSoftware.setObjectName(_fromUtf8("frameLocalSoftware"))
        self.frameLocalDefSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDefSoftware.setGeometry(QtCore.QRect(20, 30, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDefSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDefSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDefSoftware.setAutoFillBackground(False)
        self.frameLocalDefSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDefSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDefSoftware.setLineWidth(1)
        self.frameLocalDefSoftware.setObjectName(_fromUtf8("frameLocalDefSoftware"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frameLocalDefSoftware)
        self.gridLayout_20.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_20.setHorizontalSpacing(80)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.labelLocalDefSoftVersion = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftVersion.setObjectName(_fromUtf8("labelLocalDefSoftVersion"))
        self.gridLayout_20.addWidget(self.labelLocalDefSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalDefSoftVersion = QtGui.QLineEdit(self.frameLocalDefSoftware)
        self.lineEditLocalDefSoftVersion.setObjectName(_fromUtf8("lineEditLocalDefSoftVersion"))
        self.gridLayout_20.addWidget(self.lineEditLocalDefSoftVersion, 0, 1, 1, 1)
        self.labelLocalDefSoftCrc = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftCrc.setObjectName(_fromUtf8("labelLocalDefSoftCrc"))
        self.gridLayout_20.addWidget(self.labelLocalDefSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalDefSoftCrc = QtGui.QLineEdit(self.frameLocalDefSoftware)
        self.lineEditLocalDefSoftCrc.setObjectName(_fromUtf8("lineEditLocalDefSoftCrc"))
        self.gridLayout_20.addWidget(self.lineEditLocalDefSoftCrc, 1, 1, 1, 1)
        self.labelLocalDefaultSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDefaultSoftware.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.labelLocalDefaultSoftware.setScaledContents(False)
        self.labelLocalDefaultSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDefaultSoftware.setObjectName(_fromUtf8("labelLocalDefaultSoftware"))
        self.frameLocalUpdSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalUpdSoftware.setGeometry(QtCore.QRect(20, 130, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalUpdSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalUpdSoftware.setSizePolicy(sizePolicy)
        self.frameLocalUpdSoftware.setAutoFillBackground(False)
        self.frameLocalUpdSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalUpdSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalUpdSoftware.setLineWidth(1)
        self.frameLocalUpdSoftware.setObjectName(_fromUtf8("frameLocalUpdSoftware"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frameLocalUpdSoftware)
        self.gridLayout_21.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_21.setHorizontalSpacing(80)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.labelLocalUpdSoftVersion = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftVersion.setObjectName(_fromUtf8("labelLocalUpdSoftVersion"))
        self.gridLayout_21.addWidget(self.labelLocalUpdSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalUpdSoftVersion = QtGui.QLineEdit(self.frameLocalUpdSoftware)
        self.lineEditLocalUpdSoftVersion.setObjectName(_fromUtf8("lineEditLocalUpdSoftVersion"))
        self.gridLayout_21.addWidget(self.lineEditLocalUpdSoftVersion, 0, 1, 1, 1)
        self.labelLocalUpdSoftCrc = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftCrc.setObjectName(_fromUtf8("labelLocalUpdSoftCrc"))
        self.gridLayout_21.addWidget(self.labelLocalUpdSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalUpdSoftCrc = QtGui.QLineEdit(self.frameLocalUpdSoftware)
        self.lineEditLocalUpdSoftCrc.setObjectName(_fromUtf8("lineEditLocalUpdSoftCrc"))
        self.gridLayout_21.addWidget(self.lineEditLocalUpdSoftCrc, 1, 1, 1, 1)
        self.labelLocalUpdateSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalUpdateSoftware.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.labelLocalUpdateSoftware.setScaledContents(False)
        self.labelLocalUpdateSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalUpdateSoftware.setObjectName(_fromUtf8("labelLocalUpdateSoftware"))
        self.frameLocalDspSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspSoftware.setGeometry(QtCore.QRect(20, 230, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDspSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDspSoftware.setAutoFillBackground(False)
        self.frameLocalDspSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspSoftware.setLineWidth(1)
        self.frameLocalDspSoftware.setObjectName(_fromUtf8("frameLocalDspSoftware"))
        self.gridLayout_22 = QtGui.QGridLayout(self.frameLocalDspSoftware)
        self.gridLayout_22.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_22.setHorizontalSpacing(80)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.labelLocalDspSoftVersion = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftVersion.setObjectName(_fromUtf8("labelLocalDspSoftVersion"))
        self.gridLayout_22.addWidget(self.labelLocalDspSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalDspSoftVersion = QtGui.QLineEdit(self.frameLocalDspSoftware)
        self.lineEditLocalDspSoftVersion.setObjectName(_fromUtf8("lineEditLocalDspSoftVersion"))
        self.gridLayout_22.addWidget(self.lineEditLocalDspSoftVersion, 0, 1, 1, 1)
        self.labelLocalDspSoftCrc = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftCrc.setObjectName(_fromUtf8("labelLocalDspSoftCrc"))
        self.gridLayout_22.addWidget(self.labelLocalDspSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalDspSoftCrc = QtGui.QLineEdit(self.frameLocalDspSoftware)
        self.lineEditLocalDspSoftCrc.setObjectName(_fromUtf8("lineEditLocalDspSoftCrc"))
        self.gridLayout_22.addWidget(self.lineEditLocalDspSoftCrc, 1, 1, 1, 1)
        self.labelLocalDspSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspSoftware.setGeometry(QtCore.QRect(30, 220, 81, 21))
        self.labelLocalDspSoftware.setScaledContents(False)
        self.labelLocalDspSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspSoftware.setObjectName(_fromUtf8("labelLocalDspSoftware"))
        self.frameLocalDspConfig = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspConfig.setGeometry(QtCore.QRect(20, 330, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspConfig.sizePolicy().hasHeightForWidth())
        self.frameLocalDspConfig.setSizePolicy(sizePolicy)
        self.frameLocalDspConfig.setAutoFillBackground(False)
        self.frameLocalDspConfig.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspConfig.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspConfig.setLineWidth(1)
        self.frameLocalDspConfig.setObjectName(_fromUtf8("frameLocalDspConfig"))
        self.gridLayout_23 = QtGui.QGridLayout(self.frameLocalDspConfig)
        self.gridLayout_23.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_23.setHorizontalSpacing(80)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.labelLocalDspConfVersion = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfVersion.setObjectName(_fromUtf8("labelLocalDspConfVersion"))
        self.gridLayout_23.addWidget(self.labelLocalDspConfVersion, 0, 0, 1, 1)
        self.lineEditLocalDspConfVersion = QtGui.QLineEdit(self.frameLocalDspConfig)
        self.lineEditLocalDspConfVersion.setObjectName(_fromUtf8("lineEditLocalDspConfVersion"))
        self.gridLayout_23.addWidget(self.lineEditLocalDspConfVersion, 0, 1, 1, 1)
        self.labelLocalDspConfCrc = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfCrc.setObjectName(_fromUtf8("labelLocalDspConfCrc"))
        self.gridLayout_23.addWidget(self.labelLocalDspConfCrc, 1, 0, 1, 1)
        self.lineEditLocalDspConfCrc = QtGui.QLineEdit(self.frameLocalDspConfig)
        self.lineEditLocalDspConfCrc.setObjectName(_fromUtf8("lineEditLocalDspConfCrc"))
        self.gridLayout_23.addWidget(self.lineEditLocalDspConfCrc, 1, 1, 1, 1)
        self.labelLocalDspConfig = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspConfig.setGeometry(QtCore.QRect(30, 320, 71, 21))
        self.labelLocalDspConfig.setScaledContents(False)
        self.labelLocalDspConfig.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspConfig.setObjectName(_fromUtf8("labelLocalDspConfig"))
        self.labelLocalDevSoftwareDetails = QtGui.QLabel(self.localDevSoftwareDetails)
        self.labelLocalDevSoftwareDetails.setGeometry(QtCore.QRect(120, 10, 191, 21))
        self.labelLocalDevSoftwareDetails.setScaledContents(False)
        self.labelLocalDevSoftwareDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDevSoftwareDetails.setObjectName(_fromUtf8("labelLocalDevSoftwareDetails"))
        self.tabLocalDevDetails.addTab(self.localDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabLocalDevDetails, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frameLocalMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.localModems)
        self.remoteModems = QtGui.QWidget()
        self.remoteModems.setObjectName(_fromUtf8("remoteModems"))
        self.gridLayout_6 = QtGui.QGridLayout(self.remoteModems)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frameRemoteDev = QtGui.QFrame(self.remoteModems)
        self.frameRemoteDev.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRemoteDev.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRemoteDev.setObjectName(_fromUtf8("frameRemoteDev"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frameRemoteDev)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabRemoteDevDetails = QtGui.QTabWidget(self.frameRemoteDev)
        self.tabRemoteDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabRemoteDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabRemoteDevDetails.setTabsClosable(False)
        self.tabRemoteDevDetails.setObjectName(_fromUtf8("tabRemoteDevDetails"))
        self.remoteDevNetworkDetails = QtGui.QWidget()
        self.remoteDevNetworkDetails.setObjectName(_fromUtf8("remoteDevNetworkDetails"))
        self.frame_6 = QtGui.QFrame(self.remoteDevNetworkDetails)
        self.frame_6.setGeometry(QtCore.QRect(10, 20, 411, 611))
        self.frame_6.setToolTip(_fromUtf8(""))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.listWidget_5 = QtGui.QListWidget(self.frame_6)
        self.listWidget_5.setGeometry(QtCore.QRect(20, 390, 351, 81))
        self.listWidget_5.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.label_31 = QtGui.QLabel(self.frame_6)
        self.label_31.setGeometry(QtCore.QRect(29, 390, 81, 20))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.frame_6)
        self.label_32.setGeometry(QtCore.QRect(30, 500, 131, 21))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.listWidget_6 = QtGui.QListWidget(self.frame_6)
        self.listWidget_6.setGeometry(QtCore.QRect(20, 510, 351, 81))
        self.listWidget_6.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_6.setObjectName(_fromUtf8("listWidget_6"))
        self.frame_14 = QtGui.QFrame(self.frame_6)
        self.frame_14.setGeometry(QtCore.QRect(20, 50, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setAutoFillBackground(False)
        self.frame_14.setFrameShape(QtGui.QFrame.Box)
        self.frame_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_14.setLineWidth(1)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.Eth0Local_12 = QtGui.QGridLayout(self.frame_14)
        self.Eth0Local_12.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_12.setHorizontalSpacing(60)
        self.Eth0Local_12.setVerticalSpacing(6)
        self.Eth0Local_12.setObjectName(_fromUtf8("Eth0Local_12"))
        self.label_33 = QtGui.QLabel(self.frame_14)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.Eth0Local_12.addWidget(self.label_33, 0, 0, 1, 1)
        self.textBrowser_19 = QtGui.QTextBrowser(self.frame_14)
        self.textBrowser_19.setObjectName(_fromUtf8("textBrowser_19"))
        self.Eth0Local_12.addWidget(self.textBrowser_19, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.frame_14)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.Eth0Local_12.addWidget(self.label_34, 1, 0, 1, 1)
        self.textBrowser_20 = QtGui.QTextBrowser(self.frame_14)
        self.textBrowser_20.setObjectName(_fromUtf8("textBrowser_20"))
        self.Eth0Local_12.addWidget(self.textBrowser_20, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(30, 40, 41, 21))
        self.label_35.setScaledContents(False)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.frame_15 = QtGui.QFrame(self.frame_6)
        self.frame_15.setGeometry(QtCore.QRect(20, 160, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtGui.QFrame.Box)
        self.frame_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_15.setLineWidth(1)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.Eth0Local_13 = QtGui.QGridLayout(self.frame_15)
        self.Eth0Local_13.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_13.setHorizontalSpacing(60)
        self.Eth0Local_13.setObjectName(_fromUtf8("Eth0Local_13"))
        self.label_36 = QtGui.QLabel(self.frame_15)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.Eth0Local_13.addWidget(self.label_36, 0, 0, 1, 1)
        self.textBrowser_21 = QtGui.QTextBrowser(self.frame_15)
        self.textBrowser_21.setObjectName(_fromUtf8("textBrowser_21"))
        self.Eth0Local_13.addWidget(self.textBrowser_21, 0, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.frame_15)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.Eth0Local_13.addWidget(self.label_51, 1, 0, 1, 1)
        self.textBrowser_22 = QtGui.QTextBrowser(self.frame_15)
        self.textBrowser_22.setObjectName(_fromUtf8("textBrowser_22"))
        self.Eth0Local_13.addWidget(self.textBrowser_22, 1, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.frame_6)
        self.label_52.setGeometry(QtCore.QRect(30, 150, 41, 21))
        self.label_52.setScaledContents(False)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_55 = QtGui.QLabel(self.frame_6)
        self.label_55.setGeometry(QtCore.QRect(30, 260, 41, 21))
        self.label_55.setScaledContents(False)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.frame_16 = QtGui.QFrame(self.frame_6)
        self.frame_16.setGeometry(QtCore.QRect(20, 270, 351, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setFrameShape(QtGui.QFrame.Box)
        self.frame_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_16.setLineWidth(1)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.Eth0Local_14 = QtGui.QGridLayout(self.frame_16)
        self.Eth0Local_14.setContentsMargins(10, -1, 12, -1)
        self.Eth0Local_14.setHorizontalSpacing(60)
        self.Eth0Local_14.setObjectName(_fromUtf8("Eth0Local_14"))
        self.label_40 = QtGui.QLabel(self.frame_16)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.Eth0Local_14.addWidget(self.label_40, 0, 0, 1, 1)
        self.textBrowser_23 = QtGui.QTextBrowser(self.frame_16)
        self.textBrowser_23.setObjectName(_fromUtf8("textBrowser_23"))
        self.Eth0Local_14.addWidget(self.textBrowser_23, 0, 1, 1, 1)
        self.label_53 = QtGui.QLabel(self.frame_16)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.Eth0Local_14.addWidget(self.label_53, 1, 0, 1, 1)
        self.textBrowser_24 = QtGui.QTextBrowser(self.frame_16)
        self.textBrowser_24.setObjectName(_fromUtf8("textBrowser_24"))
        self.Eth0Local_14.addWidget(self.textBrowser_24, 1, 1, 1, 1)
        self.listWidget_5.raise_()
        self.label_31.raise_()
        self.listWidget_6.raise_()
        self.frame_14.raise_()
        self.label_35.raise_()
        self.frame_15.raise_()
        self.label_52.raise_()
        self.label_32.raise_()
        self.frame_16.raise_()
        self.label_55.raise_()
        self.label_56 = QtGui.QLabel(self.remoteDevNetworkDetails)
        self.label_56.setGeometry(QtCore.QRect(130, 10, 151, 21))
        self.label_56.setScaledContents(False)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.tabRemoteDevDetails.addTab(self.remoteDevNetworkDetails, _fromUtf8(""))
        self.remoteDevSoftwareDetails = QtGui.QWidget()
        self.remoteDevSoftwareDetails.setObjectName(_fromUtf8("remoteDevSoftwareDetails"))
        self.tabRemoteDevDetails.addTab(self.remoteDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabRemoteDevDetails, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frameRemoteDev, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.remoteModems)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_2.addWidget(self.frameStackedWidget, 0, 1, 1, 1)
        self.frameTree = QtGui.QFrame(self.MainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTree.sizePolicy().hasHeightForWidth())
        self.frameTree.setSizePolicy(sizePolicy)
        self.frameTree.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frameTree.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTree.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTree.setObjectName(_fromUtf8("frameTree"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameTree)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.frameTree)
        self.treeWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item_1.setFont(0, font)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setMinimumSectionSize(300)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frameTree, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.MainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabLocalDevDetails.setCurrentIndex(0)
        self.tabRemoteDevDetails.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelPcPhysicalAddress.setText(_translate("MainWindow", "Physical Address", None))
        self.labelPcSubnetMask.setText(_translate("MainWindow", "Subnet Mask", None))
        self.labelPcIpAddress.setText(_translate("MainWindow", "IP Address", None))
        self.labelPcDefaultGateway.setText(_translate("MainWindow", "Default Gateway", None))
        self.pushButtonPc.setText(_translate("MainWindow", "Scan Local", None))
        self.tcpIpDetailsLabel.setText(_translate("MainWindow", "TCP/IP Details", None))
        self.labelLocalRouteTable_2.setText(_translate("MainWindow", "Route Table", None))
        self.labelLocalBackupRouteTable_2.setText(_translate("MainWindow", "Backup Route Table", None))
        self.textEditLocalBackRoute_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.textEditLocalRoute_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.labelLocalEth0Ip_2.setText(_translate("MainWindow", "Eth0 IP Address     ", None))
        self.labelLocalEth0Mac_2.setText(_translate("MainWindow", "Eth0 MAC Address", None))
        self.labelLocalFifo0Ip_2.setText(_translate("MainWindow", "Fifo0 IP Address", None))
        self.labelLocalFifo0Mac_2.setText(_translate("MainWindow", "Fifo0 MAC Address", None))
        self.labelLocalFifo1Ip_2.setText(_translate("MainWindow", "Fifo1 IP Address", None))
        self.labelLocalFifo1Mac_2.setText(_translate("MainWindow", "Fifo1 MAC Address", None))
        self.labelLocalDeviceDetails.setText(_translate("MainWindow", "Local Device Details", None))
        self.label.setText(_translate("MainWindow", "Config .XML File", None))
        self.pushButton.setText(_translate("MainWindow", "...", None))
        self.pushButton_3.setText(_translate("MainWindow", "Apply", None))
        self.label_2.setText(_translate("MainWindow", "Config .FTP File", None))
        self.pushButton_2.setText(_translate("MainWindow", "...", None))
        self.pushButton_4.setText(_translate("MainWindow", "Apply", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.labelLocalDefSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDefSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDefaultSoftware.setText(_translate("MainWindow", "Default Software", None))
        self.labelLocalUpdSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalUpdSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalUpdateSoftware.setText(_translate("MainWindow", "Update Software", None))
        self.labelLocalDspSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspSoftware.setText(_translate("MainWindow", "DSP Software", None))
        self.labelLocalDspConfVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspConfCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspConfig.setText(_translate("MainWindow", "DSP Config", None))
        self.labelLocalDevSoftwareDetails.setText(_translate("MainWindow", "Local Device Software Setails", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.label_31.setText(_translate("MainWindow", "Route Table", None))
        self.label_32.setText(_translate("MainWindow", "Backup Route Table", None))
        self.label_33.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "Eth0", None))
        self.label_36.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_51.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_52.setText(_translate("MainWindow", "Fifo0", None))
        self.label_55.setText(_translate("MainWindow", "Fifo1", None))
        self.label_40.setText(_translate("MainWindow", "IP Address", None))
        self.textBrowser_23.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">192.168.123.234</span></p></body></html>", None))
        self.label_53.setText(_translate("MainWindow", "MAC Address", None))
        self.textBrowser_24.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\'; font-size:13pt;\">255.255.255.255.234</span></p></body></html>", None))
        self.label_56.setText(_translate("MainWindow", "Remote Device Details", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Network Devices", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "PC", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "TopSide Modem 2", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "dev1 00:01:02:03:04:05:06 192:168:125:100", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Subsea Modem 2.2", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "TopSide Modem 1", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Subsea Modem 1.1", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Subsea Modem 1.2", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

