# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treegui_v02.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(917, 737)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.MainFrame = QtGui.QFrame(self.centralwidget)
        self.MainFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainFrame.setObjectName(_fromUtf8("MainFrame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.MainFrame)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.splitter = QtGui.QSplitter(self.MainFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frameTree = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTree.sizePolicy().hasHeightForWidth())
        self.frameTree.setSizePolicy(sizePolicy)
        self.frameTree.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameTree.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameTree.setFrameShadow(QtGui.QFrame.Raised)
        self.frameTree.setObjectName(_fromUtf8("frameTree"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameTree)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.frameTree)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setFrameShape(QtGui.QFrame.Box)
        self.treeWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setAutoScroll(True)
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.treeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item_1.setFont(0, font)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setMinimumSectionSize(300)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.frameStackedWidget = QtGui.QFrame(self.splitter)
        self.frameStackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameStackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.frameStackedWidget.setObjectName(_fromUtf8("frameStackedWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameStackedWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.frameStackedWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pcDetails = QtGui.QWidget()
        self.pcDetails.setObjectName(_fromUtf8("pcDetails"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pcDetails)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.framePcMain = QtGui.QFrame(self.pcDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcMain.sizePolicy().hasHeightForWidth())
        self.framePcMain.setSizePolicy(sizePolicy)
        self.framePcMain.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.framePcMain.setFrameShape(QtGui.QFrame.Box)
        self.framePcMain.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcMain.setObjectName(_fromUtf8("framePcMain"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.framePcMain)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.framePcDetails = QtGui.QFrame(self.framePcMain)
        self.framePcDetails.setMinimumSize(QtCore.QSize(0, 25))
        self.framePcDetails.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.framePcDetails.setFrameShape(QtGui.QFrame.NoFrame)
        self.framePcDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcDetails.setObjectName(_fromUtf8("framePcDetails"))
        self.framePcAddressDetails = QtGui.QFrame(self.framePcDetails)
        self.framePcAddressDetails.setGeometry(QtCore.QRect(10, 20, 381, 261))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcAddressDetails.sizePolicy().hasHeightForWidth())
        self.framePcAddressDetails.setSizePolicy(sizePolicy)
        self.framePcAddressDetails.setFrameShape(QtGui.QFrame.Panel)
        self.framePcAddressDetails.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcAddressDetails.setObjectName(_fromUtf8("framePcAddressDetails"))
        self.gridLayout_11 = QtGui.QGridLayout(self.framePcAddressDetails)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, 10, 5)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButtonRefreshPcIp = QtGui.QPushButton(self.framePcAddressDetails)
        self.pushButtonRefreshPcIp.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRefreshPcIp.setObjectName(_fromUtf8("pushButtonRefreshPcIp"))
        self.horizontalLayout_4.addWidget(self.pushButtonRefreshPcIp)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButtonCancelPcIp = QtGui.QPushButton(self.framePcAddressDetails)
        self.pushButtonCancelPcIp.setEnabled(True)
        self.pushButtonCancelPcIp.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButtonCancelPcIp.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonCancelPcIp.setAutoDefault(False)
        self.pushButtonCancelPcIp.setDefault(False)
        self.pushButtonCancelPcIp.setFlat(False)
        self.pushButtonCancelPcIp.setObjectName(_fromUtf8("pushButtonCancelPcIp"))
        self.horizontalLayout_4.addWidget(self.pushButtonCancelPcIp)
        self.pushButtonApplyPcIp = QtGui.QPushButton(self.framePcAddressDetails)
        self.pushButtonApplyPcIp.setEnabled(False)
        self.pushButtonApplyPcIp.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonApplyPcIp.setAutoDefault(False)
        self.pushButtonApplyPcIp.setDefault(False)
        self.pushButtonApplyPcIp.setObjectName(_fromUtf8("pushButtonApplyPcIp"))
        self.horizontalLayout_4.addWidget(self.pushButtonApplyPcIp)
        self.gridLayout_11.addLayout(self.horizontalLayout_4, 9, 1, 1, 1)
        self.tcpIpDetailsLabel = QtGui.QLabel(self.framePcAddressDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tcpIpDetailsLabel.sizePolicy().hasHeightForWidth())
        self.tcpIpDetailsLabel.setSizePolicy(sizePolicy)
        self.tcpIpDetailsLabel.setMinimumSize(QtCore.QSize(0, 23))
        self.tcpIpDetailsLabel.setMaximumSize(QtCore.QSize(16777215, 23))
        self.tcpIpDetailsLabel.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.tcpIpDetailsLabel.setIndent(10)
        self.tcpIpDetailsLabel.setObjectName(_fromUtf8("tcpIpDetailsLabel"))
        self.gridLayout_11.addWidget(self.tcpIpDetailsLabel, 0, 0, 2, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 8, 1, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setContentsMargins(10, -1, 20, -1)
        self.gridLayout_10.setHorizontalSpacing(80)
        self.gridLayout_10.setVerticalSpacing(15)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.lineEditPcPhysicalAddress = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcPhysicalAddress.setEnabled(True)
        self.lineEditPcPhysicalAddress.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditPcPhysicalAddress.setStyleSheet(_fromUtf8(""))
        self.lineEditPcPhysicalAddress.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditPcPhysicalAddress.setText(_fromUtf8(""))
        self.lineEditPcPhysicalAddress.setReadOnly(True)
        self.lineEditPcPhysicalAddress.setObjectName(_fromUtf8("lineEditPcPhysicalAddress"))
        self.gridLayout_10.addWidget(self.lineEditPcPhysicalAddress, 0, 1, 1, 1)
        self.labelPcSubnetMask = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcSubnetMask.setObjectName(_fromUtf8("labelPcSubnetMask"))
        self.gridLayout_10.addWidget(self.labelPcSubnetMask, 2, 0, 1, 1)
        self.lineEditPcSubnetMask = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcSubnetMask.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditPcSubnetMask.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditPcSubnetMask.setReadOnly(False)
        self.lineEditPcSubnetMask.setObjectName(_fromUtf8("lineEditPcSubnetMask"))
        self.gridLayout_10.addWidget(self.lineEditPcSubnetMask, 2, 1, 1, 1)
        self.lineEditPcDefaultGateway = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcDefaultGateway.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditPcDefaultGateway.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditPcDefaultGateway.setReadOnly(False)
        self.lineEditPcDefaultGateway.setObjectName(_fromUtf8("lineEditPcDefaultGateway"))
        self.gridLayout_10.addWidget(self.lineEditPcDefaultGateway, 3, 1, 1, 1)
        self.labelPcIpAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcIpAddress.setObjectName(_fromUtf8("labelPcIpAddress"))
        self.gridLayout_10.addWidget(self.labelPcIpAddress, 1, 0, 1, 1)
        self.lineEditPcIpAddress = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcIpAddress.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditPcIpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditPcIpAddress.setText(_fromUtf8(""))
        self.lineEditPcIpAddress.setReadOnly(False)
        self.lineEditPcIpAddress.setObjectName(_fromUtf8("lineEditPcIpAddress"))
        self.gridLayout_10.addWidget(self.lineEditPcIpAddress, 1, 1, 1, 1)
        self.labelPcDefaultGateway = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcDefaultGateway.setObjectName(_fromUtf8("labelPcDefaultGateway"))
        self.gridLayout_10.addWidget(self.labelPcDefaultGateway, 3, 0, 1, 1)
        self.labelPcPhysicalAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcPhysicalAddress.setObjectName(_fromUtf8("labelPcPhysicalAddress"))
        self.gridLayout_10.addWidget(self.labelPcPhysicalAddress, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 7, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 34, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_11.addItem(spacerItem2, 2, 0, 1, 2)
        self.pushButtonPc = QtGui.QPushButton(self.framePcDetails)
        self.pushButtonPc.setGeometry(QtCore.QRect(400, 20, 130, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPc.sizePolicy().hasHeightForWidth())
        self.pushButtonPc.setSizePolicy(sizePolicy)
        self.pushButtonPc.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonPc.setDefault(False)
        self.pushButtonPc.setObjectName(_fromUtf8("pushButtonPc"))
        self.pushButtonPc.raise_()
        self.framePcAddressDetails.raise_()
        self.horizontalLayout.addWidget(self.framePcDetails)
        self.gridLayout_4.addWidget(self.framePcMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pcDetails)
        self.localModems = QtGui.QWidget()
        self.localModems.setObjectName(_fromUtf8("localModems"))
        self.gridLayout_5 = QtGui.QGridLayout(self.localModems)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frameLocalMain = QtGui.QFrame(self.localModems)
        self.frameLocalMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLocalMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLocalMain.setObjectName(_fromUtf8("frameLocalMain"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frameLocalMain)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setHorizontalSpacing(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabLocalDevDetails = QtGui.QTabWidget(self.frameLocalMain)
        self.tabLocalDevDetails.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabLocalDevDetails.sizePolicy().hasHeightForWidth())
        self.tabLocalDevDetails.setSizePolicy(sizePolicy)
        self.tabLocalDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(237, 233, 255);\n"
"background-color: rgb(240, 240, 240);"))
        self.tabLocalDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabLocalDevDetails.setIconSize(QtCore.QSize(16, 16))
        self.tabLocalDevDetails.setTabsClosable(False)
        self.tabLocalDevDetails.setObjectName(_fromUtf8("tabLocalDevDetails"))
        self.localDevNetworkDetails = QtGui.QWidget()
        self.localDevNetworkDetails.setObjectName(_fromUtf8("localDevNetworkDetails"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.localDevNetworkDetails)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frameLocalDev = QtGui.QFrame(self.localDevNetworkDetails)
        self.frameLocalDev.setToolTip(_fromUtf8(""))
        self.frameLocalDev.setAccessibleDescription(_fromUtf8(""))
        self.frameLocalDev.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.frameLocalDev.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLocalDev.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDev.setLineWidth(1)
        self.frameLocalDev.setObjectName(_fromUtf8("frameLocalDev"))
        self.frame = QtGui.QFrame(self.frameLocalDev)
        self.frame.setGeometry(QtCore.QRect(21, 30, 381, 271))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, 20, 9)
        self.gridLayout.setHorizontalSpacing(80)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelLocalFifo0Mac = QtGui.QLabel(self.frame)
        self.labelLocalFifo0Mac.setObjectName(_fromUtf8("labelLocalFifo0Mac"))
        self.gridLayout.addWidget(self.labelLocalFifo0Mac, 3, 0, 1, 1)
        self.labelLocalFifo1Mac = QtGui.QLabel(self.frame)
        self.labelLocalFifo1Mac.setObjectName(_fromUtf8("labelLocalFifo1Mac"))
        self.gridLayout.addWidget(self.labelLocalFifo1Mac, 5, 0, 1, 1)
        self.labelLocalEth0Ip = QtGui.QLabel(self.frame)
        self.labelLocalEth0Ip.setObjectName(_fromUtf8("labelLocalEth0Ip"))
        self.gridLayout.addWidget(self.labelLocalEth0Ip, 0, 0, 1, 1)
        self.labelLocalFifo0Ip = QtGui.QLabel(self.frame)
        self.labelLocalFifo0Ip.setObjectName(_fromUtf8("labelLocalFifo0Ip"))
        self.gridLayout.addWidget(self.labelLocalFifo0Ip, 2, 0, 1, 1)
        self.labelLocalFifo1Ip = QtGui.QLabel(self.frame)
        self.labelLocalFifo1Ip.setObjectName(_fromUtf8("labelLocalFifo1Ip"))
        self.gridLayout.addWidget(self.labelLocalFifo1Ip, 4, 0, 1, 1)
        self.lineEditLocalFifo1MacAddress = QtGui.QLineEdit(self.frame)
        self.lineEditLocalFifo1MacAddress.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditLocalFifo1MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalFifo1MacAddress.setReadOnly(True)
        self.lineEditLocalFifo1MacAddress.setObjectName(_fromUtf8("lineEditLocalFifo1MacAddress"))
        self.gridLayout.addWidget(self.lineEditLocalFifo1MacAddress, 5, 1, 1, 1)
        self.lineEditLocalEth0MacAddress = QtGui.QLineEdit(self.frame)
        self.lineEditLocalEth0MacAddress.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditLocalEth0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalEth0MacAddress.setReadOnly(True)
        self.lineEditLocalEth0MacAddress.setObjectName(_fromUtf8("lineEditLocalEth0MacAddress"))
        self.gridLayout.addWidget(self.lineEditLocalEth0MacAddress, 1, 1, 1, 1)
        self.lineEditLocalEth0Ip = QtGui.QLineEdit(self.frame)
        self.lineEditLocalEth0Ip.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditLocalEth0Ip.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalEth0Ip.setText(_fromUtf8(""))
        self.lineEditLocalEth0Ip.setReadOnly(True)
        self.lineEditLocalEth0Ip.setObjectName(_fromUtf8("lineEditLocalEth0Ip"))
        self.gridLayout.addWidget(self.lineEditLocalEth0Ip, 0, 1, 1, 1)
        self.lineEditFifo1IpAddress = QtGui.QLineEdit(self.frame)
        self.lineEditFifo1IpAddress.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditFifo1IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditFifo1IpAddress.setReadOnly(True)
        self.lineEditFifo1IpAddress.setObjectName(_fromUtf8("lineEditFifo1IpAddress"))
        self.gridLayout.addWidget(self.lineEditFifo1IpAddress, 4, 1, 1, 1)
        self.lineEditLocalFifo0MacAddress = QtGui.QLineEdit(self.frame)
        self.lineEditLocalFifo0MacAddress.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditLocalFifo0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalFifo0MacAddress.setReadOnly(True)
        self.lineEditLocalFifo0MacAddress.setObjectName(_fromUtf8("lineEditLocalFifo0MacAddress"))
        self.gridLayout.addWidget(self.lineEditLocalFifo0MacAddress, 3, 1, 1, 1)
        self.lineEditFifo0IpAddress = QtGui.QLineEdit(self.frame)
        self.lineEditFifo0IpAddress.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditFifo0IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditFifo0IpAddress.setReadOnly(True)
        self.lineEditFifo0IpAddress.setObjectName(_fromUtf8("lineEditFifo0IpAddress"))
        self.gridLayout.addWidget(self.lineEditFifo0IpAddress, 2, 1, 1, 1)
        self.labelLocalEth0Mac = QtGui.QLabel(self.frame)
        self.labelLocalEth0Mac.setObjectName(_fromUtf8("labelLocalEth0Mac"))
        self.gridLayout.addWidget(self.labelLocalEth0Mac, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.labelLocalDeviceDetails = QtGui.QLabel(self.frame)
        self.labelLocalDeviceDetails.setMinimumSize(QtCore.QSize(0, 0))
        self.labelLocalDeviceDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLocalDeviceDetails.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelLocalDeviceDetails.setScaledContents(False)
        self.labelLocalDeviceDetails.setIndent(10)
        self.labelLocalDeviceDetails.setObjectName(_fromUtf8("labelLocalDeviceDetails"))
        self.gridLayout_7.addWidget(self.labelLocalDeviceDetails, 0, 0, 1, 1)
        self.pushButtonScanRemote = QtGui.QPushButton(self.frameLocalDev)
        self.pushButtonScanRemote.setGeometry(QtCore.QRect(411, 30, 130, 31))
        self.pushButtonScanRemote.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButtonScanRemote.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonScanRemote.setObjectName(_fromUtf8("pushButtonScanRemote"))
        self.frame_2 = QtGui.QFrame(self.frameLocalDev)
        self.frame_2.setGeometry(QtCore.QRect(20, 402, 381, 101))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelLocalBackupRouteTable = QtGui.QLabel(self.frame_2)
        self.labelLocalBackupRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelLocalBackupRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelLocalBackupRouteTable.setIndent(10)
        self.labelLocalBackupRouteTable.setObjectName(_fromUtf8("labelLocalBackupRouteTable"))
        self.verticalLayout_5.addWidget(self.labelLocalBackupRouteTable)
        self.textEditLocalBackRoute = QtGui.QTextEdit(self.frame_2)
        self.textEditLocalBackRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditLocalBackRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditLocalBackRoute.setReadOnly(True)
        self.textEditLocalBackRoute.setAcceptRichText(True)
        self.textEditLocalBackRoute.setObjectName(_fromUtf8("textEditLocalBackRoute"))
        self.verticalLayout_5.addWidget(self.textEditLocalBackRoute)
        self.frame_3 = QtGui.QFrame(self.frameLocalDev)
        self.frame_3.setGeometry(QtCore.QRect(20, 300, 381, 101))
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelLocalRouteTable = QtGui.QLabel(self.frame_3)
        self.labelLocalRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelLocalRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelLocalRouteTable.setTextFormat(QtCore.Qt.AutoText)
        self.labelLocalRouteTable.setIndent(10)
        self.labelLocalRouteTable.setObjectName(_fromUtf8("labelLocalRouteTable"))
        self.verticalLayout_3.addWidget(self.labelLocalRouteTable)
        self.textEditLocalRoute = QtGui.QTextEdit(self.frame_3)
        self.textEditLocalRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditLocalRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditLocalRoute.setReadOnly(True)
        self.textEditLocalRoute.setAcceptRichText(True)
        self.textEditLocalRoute.setObjectName(_fromUtf8("textEditLocalRoute"))
        self.verticalLayout_3.addWidget(self.textEditLocalRoute)
        self.pushButtonReset = QtGui.QPushButton(self.frameLocalDev)
        self.pushButtonReset.setGeometry(QtCore.QRect(410, 70, 131, 31))
        self.pushButtonReset.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.layoutWidget = QtGui.QWidget(self.frameLocalDev)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 540, 451, 111))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditLocalXmlBrowse = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditLocalXmlBrowse.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditLocalXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalXmlBrowse.setText(_fromUtf8(""))
        self.lineEditLocalXmlBrowse.setObjectName(_fromUtf8("lineEditLocalXmlBrowse"))
        self.gridLayout_2.addWidget(self.lineEditLocalXmlBrowse, 0, 1, 1, 1)
        self.pushButtonLocalXmlBrowse = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLocalXmlBrowse.sizePolicy().hasHeightForWidth())
        self.pushButtonLocalXmlBrowse.setSizePolicy(sizePolicy)
        self.pushButtonLocalXmlBrowse.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonLocalXmlBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonLocalXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalXmlBrowse.setObjectName(_fromUtf8("pushButtonLocalXmlBrowse"))
        self.gridLayout_2.addWidget(self.pushButtonLocalXmlBrowse, 0, 2, 1, 1)
        self.pushButtonLocalXmlApply = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLocalXmlApply.sizePolicy().hasHeightForWidth())
        self.pushButtonLocalXmlApply.setSizePolicy(sizePolicy)
        self.pushButtonLocalXmlApply.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonLocalXmlApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonLocalXmlApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalXmlApply.setObjectName(_fromUtf8("pushButtonLocalXmlApply"))
        self.gridLayout_2.addWidget(self.pushButtonLocalXmlApply, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditLocalFtpBrowse = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditLocalFtpBrowse.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEditLocalFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalFtpBrowse.setObjectName(_fromUtf8("lineEditLocalFtpBrowse"))
        self.gridLayout_2.addWidget(self.lineEditLocalFtpBrowse, 1, 1, 1, 1)
        self.pushButtonLocalFtpBrowse = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonLocalFtpBrowse.setMinimumSize(QtCore.QSize(30, 28))
        self.pushButtonLocalFtpBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonLocalFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalFtpBrowse.setObjectName(_fromUtf8("pushButtonLocalFtpBrowse"))
        self.gridLayout_2.addWidget(self.pushButtonLocalFtpBrowse, 1, 2, 1, 1)
        self.pushButtonLocalFtpApply = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonLocalFtpApply.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonLocalFtpApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonLocalFtpApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalFtpApply.setObjectName(_fromUtf8("pushButtonLocalFtpApply"))
        self.gridLayout_2.addWidget(self.pushButtonLocalFtpApply, 1, 3, 1, 1)
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.pushButtonScanRemote.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.pushButtonReset.raise_()
        self.verticalLayout_2.addWidget(self.frameLocalDev)
        self.tabLocalDevDetails.addTab(self.localDevNetworkDetails, _fromUtf8(""))
        self.localDevSoftwareDetails = QtGui.QWidget()
        self.localDevSoftwareDetails.setObjectName(_fromUtf8("localDevSoftwareDetails"))
        self.frameLocalSoftware = QtGui.QFrame(self.localDevSoftwareDetails)
        self.frameLocalSoftware.setGeometry(QtCore.QRect(10, 20, 411, 621))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalSoftware.setSizePolicy(sizePolicy)
        self.frameLocalSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalSoftware.setObjectName(_fromUtf8("frameLocalSoftware"))
        self.frameLocalDefSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDefSoftware.setGeometry(QtCore.QRect(20, 30, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDefSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDefSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDefSoftware.setAutoFillBackground(False)
        self.frameLocalDefSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDefSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDefSoftware.setLineWidth(1)
        self.frameLocalDefSoftware.setObjectName(_fromUtf8("frameLocalDefSoftware"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frameLocalDefSoftware)
        self.gridLayout_20.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_20.setHorizontalSpacing(80)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.labelLocalDefSoftVersion = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftVersion.setObjectName(_fromUtf8("labelLocalDefSoftVersion"))
        self.gridLayout_20.addWidget(self.labelLocalDefSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalDefSoftVersion = QtGui.QLineEdit(self.frameLocalDefSoftware)
        self.lineEditLocalDefSoftVersion.setObjectName(_fromUtf8("lineEditLocalDefSoftVersion"))
        self.gridLayout_20.addWidget(self.lineEditLocalDefSoftVersion, 0, 1, 1, 1)
        self.labelLocalDefSoftCrc = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftCrc.setObjectName(_fromUtf8("labelLocalDefSoftCrc"))
        self.gridLayout_20.addWidget(self.labelLocalDefSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalDefSoftCrc = QtGui.QLineEdit(self.frameLocalDefSoftware)
        self.lineEditLocalDefSoftCrc.setObjectName(_fromUtf8("lineEditLocalDefSoftCrc"))
        self.gridLayout_20.addWidget(self.lineEditLocalDefSoftCrc, 1, 1, 1, 1)
        self.labelLocalDefaultSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDefaultSoftware.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.labelLocalDefaultSoftware.setScaledContents(False)
        self.labelLocalDefaultSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDefaultSoftware.setObjectName(_fromUtf8("labelLocalDefaultSoftware"))
        self.frameLocalUpdSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalUpdSoftware.setGeometry(QtCore.QRect(20, 130, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalUpdSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalUpdSoftware.setSizePolicy(sizePolicy)
        self.frameLocalUpdSoftware.setAutoFillBackground(False)
        self.frameLocalUpdSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalUpdSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalUpdSoftware.setLineWidth(1)
        self.frameLocalUpdSoftware.setObjectName(_fromUtf8("frameLocalUpdSoftware"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frameLocalUpdSoftware)
        self.gridLayout_21.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_21.setHorizontalSpacing(80)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.labelLocalUpdSoftVersion = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftVersion.setObjectName(_fromUtf8("labelLocalUpdSoftVersion"))
        self.gridLayout_21.addWidget(self.labelLocalUpdSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalUpdSoftVersion = QtGui.QLineEdit(self.frameLocalUpdSoftware)
        self.lineEditLocalUpdSoftVersion.setObjectName(_fromUtf8("lineEditLocalUpdSoftVersion"))
        self.gridLayout_21.addWidget(self.lineEditLocalUpdSoftVersion, 0, 1, 1, 1)
        self.labelLocalUpdSoftCrc = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftCrc.setObjectName(_fromUtf8("labelLocalUpdSoftCrc"))
        self.gridLayout_21.addWidget(self.labelLocalUpdSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalUpdSoftCrc = QtGui.QLineEdit(self.frameLocalUpdSoftware)
        self.lineEditLocalUpdSoftCrc.setObjectName(_fromUtf8("lineEditLocalUpdSoftCrc"))
        self.gridLayout_21.addWidget(self.lineEditLocalUpdSoftCrc, 1, 1, 1, 1)
        self.labelLocalUpdateSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalUpdateSoftware.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.labelLocalUpdateSoftware.setScaledContents(False)
        self.labelLocalUpdateSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalUpdateSoftware.setObjectName(_fromUtf8("labelLocalUpdateSoftware"))
        self.frameLocalDspSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspSoftware.setGeometry(QtCore.QRect(20, 230, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDspSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDspSoftware.setAutoFillBackground(False)
        self.frameLocalDspSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspSoftware.setLineWidth(1)
        self.frameLocalDspSoftware.setObjectName(_fromUtf8("frameLocalDspSoftware"))
        self.gridLayout_22 = QtGui.QGridLayout(self.frameLocalDspSoftware)
        self.gridLayout_22.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_22.setHorizontalSpacing(80)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.labelLocalDspSoftVersion = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftVersion.setObjectName(_fromUtf8("labelLocalDspSoftVersion"))
        self.gridLayout_22.addWidget(self.labelLocalDspSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalDspSoftVersion = QtGui.QLineEdit(self.frameLocalDspSoftware)
        self.lineEditLocalDspSoftVersion.setObjectName(_fromUtf8("lineEditLocalDspSoftVersion"))
        self.gridLayout_22.addWidget(self.lineEditLocalDspSoftVersion, 0, 1, 1, 1)
        self.labelLocalDspSoftCrc = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftCrc.setObjectName(_fromUtf8("labelLocalDspSoftCrc"))
        self.gridLayout_22.addWidget(self.labelLocalDspSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalDspSoftCrc = QtGui.QLineEdit(self.frameLocalDspSoftware)
        self.lineEditLocalDspSoftCrc.setObjectName(_fromUtf8("lineEditLocalDspSoftCrc"))
        self.gridLayout_22.addWidget(self.lineEditLocalDspSoftCrc, 1, 1, 1, 1)
        self.labelLocalDspSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspSoftware.setGeometry(QtCore.QRect(30, 220, 81, 21))
        self.labelLocalDspSoftware.setScaledContents(False)
        self.labelLocalDspSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspSoftware.setObjectName(_fromUtf8("labelLocalDspSoftware"))
        self.frameLocalDspConfig = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspConfig.setGeometry(QtCore.QRect(20, 330, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspConfig.sizePolicy().hasHeightForWidth())
        self.frameLocalDspConfig.setSizePolicy(sizePolicy)
        self.frameLocalDspConfig.setAutoFillBackground(False)
        self.frameLocalDspConfig.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspConfig.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspConfig.setLineWidth(1)
        self.frameLocalDspConfig.setObjectName(_fromUtf8("frameLocalDspConfig"))
        self.gridLayout_23 = QtGui.QGridLayout(self.frameLocalDspConfig)
        self.gridLayout_23.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_23.setHorizontalSpacing(80)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.labelLocalDspConfVersion = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfVersion.setObjectName(_fromUtf8("labelLocalDspConfVersion"))
        self.gridLayout_23.addWidget(self.labelLocalDspConfVersion, 0, 0, 1, 1)
        self.lineEditLocalDspConfVersion = QtGui.QLineEdit(self.frameLocalDspConfig)
        self.lineEditLocalDspConfVersion.setObjectName(_fromUtf8("lineEditLocalDspConfVersion"))
        self.gridLayout_23.addWidget(self.lineEditLocalDspConfVersion, 0, 1, 1, 1)
        self.labelLocalDspConfCrc = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfCrc.setObjectName(_fromUtf8("labelLocalDspConfCrc"))
        self.gridLayout_23.addWidget(self.labelLocalDspConfCrc, 1, 0, 1, 1)
        self.lineEditLocalDspConfCrc = QtGui.QLineEdit(self.frameLocalDspConfig)
        self.lineEditLocalDspConfCrc.setObjectName(_fromUtf8("lineEditLocalDspConfCrc"))
        self.gridLayout_23.addWidget(self.lineEditLocalDspConfCrc, 1, 1, 1, 1)
        self.labelLocalDspConfig = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspConfig.setGeometry(QtCore.QRect(30, 320, 71, 21))
        self.labelLocalDspConfig.setScaledContents(False)
        self.labelLocalDspConfig.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspConfig.setObjectName(_fromUtf8("labelLocalDspConfig"))
        self.labelLocalDevSoftwareDetails = QtGui.QLabel(self.localDevSoftwareDetails)
        self.labelLocalDevSoftwareDetails.setGeometry(QtCore.QRect(120, 10, 191, 21))
        self.labelLocalDevSoftwareDetails.setScaledContents(False)
        self.labelLocalDevSoftwareDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDevSoftwareDetails.setObjectName(_fromUtf8("labelLocalDevSoftwareDetails"))
        self.tabLocalDevDetails.addTab(self.localDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabLocalDevDetails, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frameLocalMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.localModems)
        self.remoteModems = QtGui.QWidget()
        self.remoteModems.setObjectName(_fromUtf8("remoteModems"))
        self.gridLayout_16 = QtGui.QGridLayout(self.remoteModems)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.frameRemoteMain = QtGui.QFrame(self.remoteModems)
        self.frameRemoteMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRemoteMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRemoteMain.setObjectName(_fromUtf8("frameRemoteMain"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frameRemoteMain)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setHorizontalSpacing(6)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tabRemoteDevDetails = QtGui.QTabWidget(self.frameRemoteMain)
        self.tabRemoteDevDetails.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabRemoteDevDetails.sizePolicy().hasHeightForWidth())
        self.tabRemoteDevDetails.setSizePolicy(sizePolicy)
        self.tabRemoteDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.tabRemoteDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabRemoteDevDetails.setIconSize(QtCore.QSize(16, 16))
        self.tabRemoteDevDetails.setTabsClosable(False)
        self.tabRemoteDevDetails.setObjectName(_fromUtf8("tabRemoteDevDetails"))
        self.remoteDevNetworkDetails = QtGui.QWidget()
        self.remoteDevNetworkDetails.setObjectName(_fromUtf8("remoteDevNetworkDetails"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.remoteDevNetworkDetails)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frameRemoteDev = QtGui.QFrame(self.remoteDevNetworkDetails)
        self.frameRemoteDev.setToolTip(_fromUtf8(""))
        self.frameRemoteDev.setAccessibleDescription(_fromUtf8(""))
        self.frameRemoteDev.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.frameRemoteDev.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRemoteDev.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameRemoteDev.setLineWidth(1)
        self.frameRemoteDev.setObjectName(_fromUtf8("frameRemoteDev"))
        self.frame_4 = QtGui.QFrame(self.frameRemoteDev)
        self.frame_4.setGeometry(QtCore.QRect(21, 20, 381, 211))
        self.frame_4.setFrameShape(QtGui.QFrame.Panel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(10, -1, 20, 9)
        self.gridLayout_6.setHorizontalSpacing(80)
        self.gridLayout_6.setVerticalSpacing(10)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelRemoteFifo0Mac = QtGui.QLabel(self.frame_4)
        self.labelRemoteFifo0Mac.setObjectName(_fromUtf8("labelRemoteFifo0Mac"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo0Mac, 3, 0, 1, 1)
        self.labelRemoteFifo1Mac = QtGui.QLabel(self.frame_4)
        self.labelRemoteFifo1Mac.setObjectName(_fromUtf8("labelRemoteFifo1Mac"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo1Mac, 5, 0, 1, 1)
        self.labelRemoteEth0Ip = QtGui.QLabel(self.frame_4)
        self.labelRemoteEth0Ip.setObjectName(_fromUtf8("labelRemoteEth0Ip"))
        self.gridLayout_6.addWidget(self.labelRemoteEth0Ip, 0, 0, 1, 1)
        self.labelRemoteFifo0Ip = QtGui.QLabel(self.frame_4)
        self.labelRemoteFifo0Ip.setObjectName(_fromUtf8("labelRemoteFifo0Ip"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo0Ip, 2, 0, 1, 1)
        self.labelRemoteFifo1Ip = QtGui.QLabel(self.frame_4)
        self.labelRemoteFifo1Ip.setObjectName(_fromUtf8("labelRemoteFifo1Ip"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo1Ip, 4, 0, 1, 1)
        self.lineEditRemoteFifo1MacAddress = QtGui.QLineEdit(self.frame_4)
        self.lineEditRemoteFifo1MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo1MacAddress.setReadOnly(True)
        self.lineEditRemoteFifo1MacAddress.setObjectName(_fromUtf8("lineEditRemoteFifo1MacAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo1MacAddress, 5, 1, 1, 1)
        self.lineEditRemoteEth0MacAddress = QtGui.QLineEdit(self.frame_4)
        self.lineEditRemoteEth0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteEth0MacAddress.setReadOnly(True)
        self.lineEditRemoteEth0MacAddress.setObjectName(_fromUtf8("lineEditRemoteEth0MacAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteEth0MacAddress, 1, 1, 1, 1)
        self.lineEditRemoteEth0Ip = QtGui.QLineEdit(self.frame_4)
        self.lineEditRemoteEth0Ip.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteEth0Ip.setText(_fromUtf8(""))
        self.lineEditRemoteEth0Ip.setReadOnly(True)
        self.lineEditRemoteEth0Ip.setObjectName(_fromUtf8("lineEditRemoteEth0Ip"))
        self.gridLayout_6.addWidget(self.lineEditRemoteEth0Ip, 0, 1, 1, 1)
        self.lineEditRemoteFifo1IpAddress = QtGui.QLineEdit(self.frame_4)
        self.lineEditRemoteFifo1IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo1IpAddress.setReadOnly(True)
        self.lineEditRemoteFifo1IpAddress.setObjectName(_fromUtf8("lineEditRemoteFifo1IpAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo1IpAddress, 4, 1, 1, 1)
        self.lineEditRemoteFifo0MacAddress = QtGui.QLineEdit(self.frame_4)
        self.lineEditRemoteFifo0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo0MacAddress.setReadOnly(True)
        self.lineEditRemoteFifo0MacAddress.setObjectName(_fromUtf8("lineEditRemoteFifo0MacAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo0MacAddress, 3, 1, 1, 1)
        self.lineEditRemoteFifo0IpAddress = QtGui.QLineEdit(self.frame_4)
        self.lineEditRemoteFifo0IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo0IpAddress.setReadOnly(True)
        self.lineEditRemoteFifo0IpAddress.setObjectName(_fromUtf8("lineEditRemoteFifo0IpAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo0IpAddress, 2, 1, 1, 1)
        self.labelRemoteEth0Mac = QtGui.QLabel(self.frame_4)
        self.labelRemoteEth0Mac.setObjectName(_fromUtf8("labelRemoteEth0Mac"))
        self.gridLayout_6.addWidget(self.labelRemoteEth0Mac, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.labelRemoteDeviceDetails = QtGui.QLabel(self.frame_4)
        self.labelRemoteDeviceDetails.setMinimumSize(QtCore.QSize(0, 0))
        self.labelRemoteDeviceDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelRemoteDeviceDetails.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelRemoteDeviceDetails.setScaledContents(False)
        self.labelRemoteDeviceDetails.setIndent(10)
        self.labelRemoteDeviceDetails.setObjectName(_fromUtf8("labelRemoteDeviceDetails"))
        self.gridLayout_15.addWidget(self.labelRemoteDeviceDetails, 0, 0, 1, 1)
        self.pushButtonScanRemoteChild = QtGui.QPushButton(self.frameRemoteDev)
        self.pushButtonScanRemoteChild.setGeometry(QtCore.QRect(411, 20, 130, 31))
        self.pushButtonScanRemoteChild.setMaximumSize(QtCore.QSize(130, 16777215))
        self.pushButtonScanRemoteChild.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonScanRemoteChild.setObjectName(_fromUtf8("pushButtonScanRemoteChild"))
        self.frame_8 = QtGui.QFrame(self.frameRemoteDev)
        self.frame_8.setGeometry(QtCore.QRect(21, 332, 381, 101))
        self.frame_8.setFrameShape(QtGui.QFrame.Panel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_8.setLineWidth(1)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.labelRemoteBackupRouteTable = QtGui.QLabel(self.frame_8)
        self.labelRemoteBackupRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelRemoteBackupRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelRemoteBackupRouteTable.setIndent(10)
        self.labelRemoteBackupRouteTable.setObjectName(_fromUtf8("labelRemoteBackupRouteTable"))
        self.verticalLayout_10.addWidget(self.labelRemoteBackupRouteTable)
        self.textEditRemoteBackRoute = QtGui.QTextEdit(self.frame_8)
        self.textEditRemoteBackRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditRemoteBackRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditRemoteBackRoute.setReadOnly(True)
        self.textEditRemoteBackRoute.setAcceptRichText(True)
        self.textEditRemoteBackRoute.setObjectName(_fromUtf8("textEditRemoteBackRoute"))
        self.verticalLayout_10.addWidget(self.textEditRemoteBackRoute)
        self.frame_9 = QtGui.QFrame(self.frameRemoteDev)
        self.frame_9.setGeometry(QtCore.QRect(21, 230, 381, 101))
        self.frame_9.setFrameShape(QtGui.QFrame.Panel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.labelRemoteRouteTable = QtGui.QLabel(self.frame_9)
        self.labelRemoteRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelRemoteRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelRemoteRouteTable.setTextFormat(QtCore.Qt.AutoText)
        self.labelRemoteRouteTable.setIndent(10)
        self.labelRemoteRouteTable.setObjectName(_fromUtf8("labelRemoteRouteTable"))
        self.verticalLayout_11.addWidget(self.labelRemoteRouteTable)
        self.textEditRemoteRoute = QtGui.QTextEdit(self.frame_9)
        self.textEditRemoteRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditRemoteRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditRemoteRoute.setReadOnly(True)
        self.textEditRemoteRoute.setAcceptRichText(True)
        self.textEditRemoteRoute.setObjectName(_fromUtf8("textEditRemoteRoute"))
        self.verticalLayout_11.addWidget(self.textEditRemoteRoute)
        self.layoutWidget_3 = QtGui.QWidget(self.frameRemoteDev)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 500, 381, 25))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEditRemoteFtpBrowse = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEditRemoteFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFtpBrowse.setObjectName(_fromUtf8("lineEditRemoteFtpBrowse"))
        self.horizontalLayout_7.addWidget(self.lineEditRemoteFtpBrowse)
        self.pushButtonRemoteFtpBrowse = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonRemoteFtpBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonRemoteFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteFtpBrowse.setObjectName(_fromUtf8("pushButtonRemoteFtpBrowse"))
        self.horizontalLayout_7.addWidget(self.pushButtonRemoteFtpBrowse)
        self.pushButtonRemoteFtpApply = QtGui.QPushButton(self.layoutWidget_3)
        self.pushButtonRemoteFtpApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemoteFtpApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteFtpApply.setObjectName(_fromUtf8("pushButtonRemoteFtpApply"))
        self.horizontalLayout_7.addWidget(self.pushButtonRemoteFtpApply)
        self.layoutWidget_4 = QtGui.QWidget(self.frameRemoteDev)
        self.layoutWidget_4.setGeometry(QtCore.QRect(21, 460, 379, 25))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEditRemoteXmlBrowse = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEditRemoteXmlBrowse.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditRemoteXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteXmlBrowse.setText(_fromUtf8(""))
        self.lineEditRemoteXmlBrowse.setObjectName(_fromUtf8("lineEditRemoteXmlBrowse"))
        self.horizontalLayout_8.addWidget(self.lineEditRemoteXmlBrowse)
        self.pushButtonRemoteXmlBrowse = QtGui.QPushButton(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemoteXmlBrowse.sizePolicy().hasHeightForWidth())
        self.pushButtonRemoteXmlBrowse.setSizePolicy(sizePolicy)
        self.pushButtonRemoteXmlBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonRemoteXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteXmlBrowse.setObjectName(_fromUtf8("pushButtonRemoteXmlBrowse"))
        self.horizontalLayout_8.addWidget(self.pushButtonRemoteXmlBrowse)
        self.pushButtonRemoteXmlApply = QtGui.QPushButton(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemoteXmlApply.sizePolicy().hasHeightForWidth())
        self.pushButtonRemoteXmlApply.setSizePolicy(sizePolicy)
        self.pushButtonRemoteXmlApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemoteXmlApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteXmlApply.setObjectName(_fromUtf8("pushButtonRemoteXmlApply"))
        self.horizontalLayout_8.addWidget(self.pushButtonRemoteXmlApply)
        self.pushButton_2 = QtGui.QPushButton(self.frameRemoteDev)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 60, 131, 31))
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_9.addWidget(self.frameRemoteDev)
        self.tabRemoteDevDetails.addTab(self.remoteDevNetworkDetails, _fromUtf8(""))
        self.remoteDevSoftwareDetails = QtGui.QWidget()
        self.remoteDevSoftwareDetails.setObjectName(_fromUtf8("remoteDevSoftwareDetails"))
        self.frameRemoteSoftware = QtGui.QFrame(self.remoteDevSoftwareDetails)
        self.frameRemoteSoftware.setGeometry(QtCore.QRect(10, 20, 411, 621))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRemoteSoftware.sizePolicy().hasHeightForWidth())
        self.frameRemoteSoftware.setSizePolicy(sizePolicy)
        self.frameRemoteSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameRemoteSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameRemoteSoftware.setObjectName(_fromUtf8("frameRemoteSoftware"))
        self.frameLocalDefSoftware_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalDefSoftware_3.setGeometry(QtCore.QRect(20, 30, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDefSoftware_3.sizePolicy().hasHeightForWidth())
        self.frameLocalDefSoftware_3.setSizePolicy(sizePolicy)
        self.frameLocalDefSoftware_3.setAutoFillBackground(False)
        self.frameLocalDefSoftware_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDefSoftware_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDefSoftware_3.setLineWidth(1)
        self.frameLocalDefSoftware_3.setObjectName(_fromUtf8("frameLocalDefSoftware_3"))
        self.gridLayout_28 = QtGui.QGridLayout(self.frameLocalDefSoftware_3)
        self.gridLayout_28.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_28.setHorizontalSpacing(80)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.labelLocalDefSoftVersion_3 = QtGui.QLabel(self.frameLocalDefSoftware_3)
        self.labelLocalDefSoftVersion_3.setObjectName(_fromUtf8("labelLocalDefSoftVersion_3"))
        self.gridLayout_28.addWidget(self.labelLocalDefSoftVersion_3, 0, 0, 1, 1)
        self.lineEditLocalDefSoftVersion_3 = QtGui.QLineEdit(self.frameLocalDefSoftware_3)
        self.lineEditLocalDefSoftVersion_3.setObjectName(_fromUtf8("lineEditLocalDefSoftVersion_3"))
        self.gridLayout_28.addWidget(self.lineEditLocalDefSoftVersion_3, 0, 1, 1, 1)
        self.labelLocalDefSoftCrc_3 = QtGui.QLabel(self.frameLocalDefSoftware_3)
        self.labelLocalDefSoftCrc_3.setObjectName(_fromUtf8("labelLocalDefSoftCrc_3"))
        self.gridLayout_28.addWidget(self.labelLocalDefSoftCrc_3, 1, 0, 1, 1)
        self.lineEditLocalDefSoftCrc_3 = QtGui.QLineEdit(self.frameLocalDefSoftware_3)
        self.lineEditLocalDefSoftCrc_3.setObjectName(_fromUtf8("lineEditLocalDefSoftCrc_3"))
        self.gridLayout_28.addWidget(self.lineEditLocalDefSoftCrc_3, 1, 1, 1, 1)
        self.labelLocalDefaultSoftware_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalDefaultSoftware_3.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.labelLocalDefaultSoftware_3.setScaledContents(False)
        self.labelLocalDefaultSoftware_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDefaultSoftware_3.setObjectName(_fromUtf8("labelLocalDefaultSoftware_3"))
        self.frameLocalUpdSoftware_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalUpdSoftware_3.setGeometry(QtCore.QRect(20, 130, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalUpdSoftware_3.sizePolicy().hasHeightForWidth())
        self.frameLocalUpdSoftware_3.setSizePolicy(sizePolicy)
        self.frameLocalUpdSoftware_3.setAutoFillBackground(False)
        self.frameLocalUpdSoftware_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalUpdSoftware_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalUpdSoftware_3.setLineWidth(1)
        self.frameLocalUpdSoftware_3.setObjectName(_fromUtf8("frameLocalUpdSoftware_3"))
        self.gridLayout_29 = QtGui.QGridLayout(self.frameLocalUpdSoftware_3)
        self.gridLayout_29.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_29.setHorizontalSpacing(80)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.labelLocalUpdSoftVersion_3 = QtGui.QLabel(self.frameLocalUpdSoftware_3)
        self.labelLocalUpdSoftVersion_3.setObjectName(_fromUtf8("labelLocalUpdSoftVersion_3"))
        self.gridLayout_29.addWidget(self.labelLocalUpdSoftVersion_3, 0, 0, 1, 1)
        self.lineEditLocalUpdSoftVersion_3 = QtGui.QLineEdit(self.frameLocalUpdSoftware_3)
        self.lineEditLocalUpdSoftVersion_3.setObjectName(_fromUtf8("lineEditLocalUpdSoftVersion_3"))
        self.gridLayout_29.addWidget(self.lineEditLocalUpdSoftVersion_3, 0, 1, 1, 1)
        self.labelLocalUpdSoftCrc_3 = QtGui.QLabel(self.frameLocalUpdSoftware_3)
        self.labelLocalUpdSoftCrc_3.setObjectName(_fromUtf8("labelLocalUpdSoftCrc_3"))
        self.gridLayout_29.addWidget(self.labelLocalUpdSoftCrc_3, 1, 0, 1, 1)
        self.lineEditLocalUpdSoftCrc_3 = QtGui.QLineEdit(self.frameLocalUpdSoftware_3)
        self.lineEditLocalUpdSoftCrc_3.setObjectName(_fromUtf8("lineEditLocalUpdSoftCrc_3"))
        self.gridLayout_29.addWidget(self.lineEditLocalUpdSoftCrc_3, 1, 1, 1, 1)
        self.labelLocalUpdateSoftware_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalUpdateSoftware_3.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.labelLocalUpdateSoftware_3.setScaledContents(False)
        self.labelLocalUpdateSoftware_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalUpdateSoftware_3.setObjectName(_fromUtf8("labelLocalUpdateSoftware_3"))
        self.frameLocalDspSoftware_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalDspSoftware_3.setGeometry(QtCore.QRect(20, 230, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspSoftware_3.sizePolicy().hasHeightForWidth())
        self.frameLocalDspSoftware_3.setSizePolicy(sizePolicy)
        self.frameLocalDspSoftware_3.setAutoFillBackground(False)
        self.frameLocalDspSoftware_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspSoftware_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspSoftware_3.setLineWidth(1)
        self.frameLocalDspSoftware_3.setObjectName(_fromUtf8("frameLocalDspSoftware_3"))
        self.gridLayout_30 = QtGui.QGridLayout(self.frameLocalDspSoftware_3)
        self.gridLayout_30.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_30.setHorizontalSpacing(80)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.labelLocalDspSoftVersion_3 = QtGui.QLabel(self.frameLocalDspSoftware_3)
        self.labelLocalDspSoftVersion_3.setObjectName(_fromUtf8("labelLocalDspSoftVersion_3"))
        self.gridLayout_30.addWidget(self.labelLocalDspSoftVersion_3, 0, 0, 1, 1)
        self.lineEditLocalDspSoftVersion_3 = QtGui.QLineEdit(self.frameLocalDspSoftware_3)
        self.lineEditLocalDspSoftVersion_3.setObjectName(_fromUtf8("lineEditLocalDspSoftVersion_3"))
        self.gridLayout_30.addWidget(self.lineEditLocalDspSoftVersion_3, 0, 1, 1, 1)
        self.labelLocalDspSoftCrc_3 = QtGui.QLabel(self.frameLocalDspSoftware_3)
        self.labelLocalDspSoftCrc_3.setObjectName(_fromUtf8("labelLocalDspSoftCrc_3"))
        self.gridLayout_30.addWidget(self.labelLocalDspSoftCrc_3, 1, 0, 1, 1)
        self.lineEditLocalDspSoftCrc_3 = QtGui.QLineEdit(self.frameLocalDspSoftware_3)
        self.lineEditLocalDspSoftCrc_3.setObjectName(_fromUtf8("lineEditLocalDspSoftCrc_3"))
        self.gridLayout_30.addWidget(self.lineEditLocalDspSoftCrc_3, 1, 1, 1, 1)
        self.labelLocalDspSoftware_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalDspSoftware_3.setGeometry(QtCore.QRect(30, 220, 81, 21))
        self.labelLocalDspSoftware_3.setScaledContents(False)
        self.labelLocalDspSoftware_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspSoftware_3.setObjectName(_fromUtf8("labelLocalDspSoftware_3"))
        self.frameLocalDspConfig_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalDspConfig_3.setGeometry(QtCore.QRect(20, 330, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspConfig_3.sizePolicy().hasHeightForWidth())
        self.frameLocalDspConfig_3.setSizePolicy(sizePolicy)
        self.frameLocalDspConfig_3.setAutoFillBackground(False)
        self.frameLocalDspConfig_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspConfig_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspConfig_3.setLineWidth(1)
        self.frameLocalDspConfig_3.setObjectName(_fromUtf8("frameLocalDspConfig_3"))
        self.gridLayout_31 = QtGui.QGridLayout(self.frameLocalDspConfig_3)
        self.gridLayout_31.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_31.setHorizontalSpacing(80)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.labelLocalDspConfVersion_3 = QtGui.QLabel(self.frameLocalDspConfig_3)
        self.labelLocalDspConfVersion_3.setObjectName(_fromUtf8("labelLocalDspConfVersion_3"))
        self.gridLayout_31.addWidget(self.labelLocalDspConfVersion_3, 0, 0, 1, 1)
        self.lineEditLocalDspConfVersion_3 = QtGui.QLineEdit(self.frameLocalDspConfig_3)
        self.lineEditLocalDspConfVersion_3.setObjectName(_fromUtf8("lineEditLocalDspConfVersion_3"))
        self.gridLayout_31.addWidget(self.lineEditLocalDspConfVersion_3, 0, 1, 1, 1)
        self.labelLocalDspConfCrc_3 = QtGui.QLabel(self.frameLocalDspConfig_3)
        self.labelLocalDspConfCrc_3.setObjectName(_fromUtf8("labelLocalDspConfCrc_3"))
        self.gridLayout_31.addWidget(self.labelLocalDspConfCrc_3, 1, 0, 1, 1)
        self.lineEditLocalDspConfCrc_3 = QtGui.QLineEdit(self.frameLocalDspConfig_3)
        self.lineEditLocalDspConfCrc_3.setObjectName(_fromUtf8("lineEditLocalDspConfCrc_3"))
        self.gridLayout_31.addWidget(self.lineEditLocalDspConfCrc_3, 1, 1, 1, 1)
        self.labelLocalDspConfig_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalDspConfig_3.setGeometry(QtCore.QRect(30, 320, 71, 21))
        self.labelLocalDspConfig_3.setScaledContents(False)
        self.labelLocalDspConfig_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspConfig_3.setObjectName(_fromUtf8("labelLocalDspConfig_3"))
        self.labelLocalDevSoftwareDetails_3 = QtGui.QLabel(self.remoteDevSoftwareDetails)
        self.labelLocalDevSoftwareDetails_3.setGeometry(QtCore.QRect(120, 10, 191, 21))
        self.labelLocalDevSoftwareDetails_3.setScaledContents(False)
        self.labelLocalDevSoftwareDetails_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDevSoftwareDetails_3.setObjectName(_fromUtf8("labelLocalDevSoftwareDetails_3"))
        self.tabRemoteDevDetails.addTab(self.remoteDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_14.addWidget(self.tabRemoteDevDetails, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frameRemoteMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.remoteModems)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_9.addWidget(self.splitter)
        self.verticalLayout_4.addWidget(self.MainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabLocalDevDetails.setCurrentIndex(0)
        self.tabRemoteDevDetails.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.treeWidget, self.pushButtonPc)
        MainWindow.setTabOrder(self.pushButtonPc, self.lineEditPcPhysicalAddress)
        MainWindow.setTabOrder(self.lineEditPcPhysicalAddress, self.lineEditPcIpAddress)
        MainWindow.setTabOrder(self.lineEditPcIpAddress, self.lineEditPcSubnetMask)
        MainWindow.setTabOrder(self.lineEditPcSubnetMask, self.lineEditPcDefaultGateway)
        MainWindow.setTabOrder(self.lineEditPcDefaultGateway, self.pushButtonRefreshPcIp)
        MainWindow.setTabOrder(self.pushButtonRefreshPcIp, self.pushButtonCancelPcIp)
        MainWindow.setTabOrder(self.pushButtonCancelPcIp, self.pushButtonApplyPcIp)
        MainWindow.setTabOrder(self.pushButtonApplyPcIp, self.lineEditLocalEth0MacAddress)
        MainWindow.setTabOrder(self.lineEditLocalEth0MacAddress, self.tabLocalDevDetails)
        MainWindow.setTabOrder(self.tabLocalDevDetails, self.lineEditLocalEth0Ip)
        MainWindow.setTabOrder(self.lineEditLocalEth0Ip, self.lineEditFifo1IpAddress)
        MainWindow.setTabOrder(self.lineEditFifo1IpAddress, self.lineEditLocalFifo0MacAddress)
        MainWindow.setTabOrder(self.lineEditLocalFifo0MacAddress, self.lineEditFifo0IpAddress)
        MainWindow.setTabOrder(self.lineEditFifo0IpAddress, self.pushButtonScanRemote)
        MainWindow.setTabOrder(self.pushButtonScanRemote, self.textEditLocalBackRoute)
        MainWindow.setTabOrder(self.textEditLocalBackRoute, self.textEditLocalRoute)
        MainWindow.setTabOrder(self.textEditLocalRoute, self.pushButtonReset)
        MainWindow.setTabOrder(self.pushButtonReset, self.lineEditLocalXmlBrowse)
        MainWindow.setTabOrder(self.lineEditLocalXmlBrowse, self.pushButtonLocalXmlBrowse)
        MainWindow.setTabOrder(self.pushButtonLocalXmlBrowse, self.pushButtonLocalXmlApply)
        MainWindow.setTabOrder(self.pushButtonLocalXmlApply, self.lineEditLocalFtpBrowse)
        MainWindow.setTabOrder(self.lineEditLocalFtpBrowse, self.pushButtonLocalFtpBrowse)
        MainWindow.setTabOrder(self.pushButtonLocalFtpBrowse, self.pushButtonLocalFtpApply)
        MainWindow.setTabOrder(self.pushButtonLocalFtpApply, self.lineEditLocalDefSoftVersion)
        MainWindow.setTabOrder(self.lineEditLocalDefSoftVersion, self.lineEditLocalDefSoftCrc)
        MainWindow.setTabOrder(self.lineEditLocalDefSoftCrc, self.lineEditLocalUpdSoftVersion)
        MainWindow.setTabOrder(self.lineEditLocalUpdSoftVersion, self.lineEditLocalUpdSoftCrc)
        MainWindow.setTabOrder(self.lineEditLocalUpdSoftCrc, self.lineEditLocalDspSoftVersion)
        MainWindow.setTabOrder(self.lineEditLocalDspSoftVersion, self.lineEditLocalDspSoftCrc)
        MainWindow.setTabOrder(self.lineEditLocalDspSoftCrc, self.lineEditLocalDspConfVersion)
        MainWindow.setTabOrder(self.lineEditLocalDspConfVersion, self.lineEditLocalDspConfCrc)
        MainWindow.setTabOrder(self.lineEditLocalDspConfCrc, self.tabRemoteDevDetails)
        MainWindow.setTabOrder(self.tabRemoteDevDetails, self.lineEditRemoteFifo1MacAddress)
        MainWindow.setTabOrder(self.lineEditRemoteFifo1MacAddress, self.lineEditRemoteEth0MacAddress)
        MainWindow.setTabOrder(self.lineEditRemoteEth0MacAddress, self.lineEditRemoteEth0Ip)
        MainWindow.setTabOrder(self.lineEditRemoteEth0Ip, self.lineEditRemoteFifo1IpAddress)
        MainWindow.setTabOrder(self.lineEditRemoteFifo1IpAddress, self.lineEditRemoteFifo0MacAddress)
        MainWindow.setTabOrder(self.lineEditRemoteFifo0MacAddress, self.lineEditRemoteFifo0IpAddress)
        MainWindow.setTabOrder(self.lineEditRemoteFifo0IpAddress, self.pushButtonScanRemoteChild)
        MainWindow.setTabOrder(self.pushButtonScanRemoteChild, self.textEditRemoteBackRoute)
        MainWindow.setTabOrder(self.textEditRemoteBackRoute, self.textEditRemoteRoute)
        MainWindow.setTabOrder(self.textEditRemoteRoute, self.lineEditRemoteFtpBrowse)
        MainWindow.setTabOrder(self.lineEditRemoteFtpBrowse, self.pushButtonRemoteFtpBrowse)
        MainWindow.setTabOrder(self.pushButtonRemoteFtpBrowse, self.pushButtonRemoteFtpApply)
        MainWindow.setTabOrder(self.pushButtonRemoteFtpApply, self.lineEditRemoteXmlBrowse)
        MainWindow.setTabOrder(self.lineEditRemoteXmlBrowse, self.pushButtonRemoteXmlBrowse)
        MainWindow.setTabOrder(self.pushButtonRemoteXmlBrowse, self.pushButtonRemoteXmlApply)
        MainWindow.setTabOrder(self.pushButtonRemoteXmlApply, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.lineEditLocalDefSoftVersion_3)
        MainWindow.setTabOrder(self.lineEditLocalDefSoftVersion_3, self.lineEditLocalDefSoftCrc_3)
        MainWindow.setTabOrder(self.lineEditLocalDefSoftCrc_3, self.lineEditLocalUpdSoftVersion_3)
        MainWindow.setTabOrder(self.lineEditLocalUpdSoftVersion_3, self.lineEditLocalUpdSoftCrc_3)
        MainWindow.setTabOrder(self.lineEditLocalUpdSoftCrc_3, self.lineEditLocalDspSoftVersion_3)
        MainWindow.setTabOrder(self.lineEditLocalDspSoftVersion_3, self.lineEditLocalDspSoftCrc_3)
        MainWindow.setTabOrder(self.lineEditLocalDspSoftCrc_3, self.lineEditLocalDspConfVersion_3)
        MainWindow.setTabOrder(self.lineEditLocalDspConfVersion_3, self.lineEditLocalDspConfCrc_3)
        MainWindow.setTabOrder(self.lineEditLocalDspConfCrc_3, self.lineEditLocalFifo1MacAddress)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Network Devices", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "PC", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "TopSide Modem 2", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "dev1 00:01:02:03:04:05:06 192:168:125:100 jhi", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Subsea Modem 2.2", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "dev-22 00:00:00:00:00:00 192.168.222.101", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "TopSide Modem 1", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Subsea Modem 1.1", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Modem 1.2 jefjkwe[ofjsdjvlsadjfpoajwepfjsdaf\'sdpojfpa", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButtonRefreshPcIp.setText(_translate("MainWindow", "Refresh", None))
        self.pushButtonCancelPcIp.setText(_translate("MainWindow", "Cancel", None))
        self.pushButtonApplyPcIp.setText(_translate("MainWindow", "Apply", None))
        self.tcpIpDetailsLabel.setText(_translate("MainWindow", "TCP/IP Details", None))
        self.labelPcSubnetMask.setText(_translate("MainWindow", "Subnet Mask", None))
        self.labelPcIpAddress.setText(_translate("MainWindow", "IP Address", None))
        self.labelPcDefaultGateway.setText(_translate("MainWindow", "Default Gateway", None))
        self.labelPcPhysicalAddress.setText(_translate("MainWindow", "Physical Address", None))
        self.pushButtonPc.setText(_translate("MainWindow", "Search Local Devices", None))
        self.labelLocalFifo0Mac.setText(_translate("MainWindow", "Fifo0 MAC Address", None))
        self.labelLocalFifo1Mac.setText(_translate("MainWindow", "Fifo1 MAC Address", None))
        self.labelLocalEth0Ip.setText(_translate("MainWindow", "Eth0 IP Address     ", None))
        self.labelLocalFifo0Ip.setText(_translate("MainWindow", "Fifo0 IP Address", None))
        self.labelLocalFifo1Ip.setText(_translate("MainWindow", "Fifo1 IP Address", None))
        self.labelLocalEth0Mac.setText(_translate("MainWindow", "Eth0 MAC Address", None))
        self.labelLocalDeviceDetails.setText(_translate("MainWindow", "Local Device Details", None))
        self.pushButtonScanRemote.setText(_translate("MainWindow", "Search Remote Devices", None))
        self.labelLocalBackupRouteTable.setText(_translate("MainWindow", "Backup Route Table", None))
        self.textEditLocalBackRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.labelLocalRouteTable.setText(_translate("MainWindow", "Route Table", None))
        self.textEditLocalRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset", None))
        self.label.setText(_translate("MainWindow", "Config .XML File", None))
        self.pushButtonLocalXmlBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonLocalXmlApply.setText(_translate("MainWindow", "Apply", None))
        self.label_2.setText(_translate("MainWindow", "Config .FTP File", None))
        self.pushButtonLocalFtpBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonLocalFtpApply.setText(_translate("MainWindow", "Apply", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.labelLocalDefSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDefSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDefaultSoftware.setText(_translate("MainWindow", "Default Software", None))
        self.labelLocalUpdSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalUpdSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalUpdateSoftware.setText(_translate("MainWindow", "Update Software", None))
        self.labelLocalDspSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspSoftware.setText(_translate("MainWindow", "DSP Software", None))
        self.labelLocalDspConfVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspConfCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspConfig.setText(_translate("MainWindow", "DSP Config", None))
        self.labelLocalDevSoftwareDetails.setText(_translate("MainWindow", "Local Device Software Setails", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.labelRemoteFifo0Mac.setText(_translate("MainWindow", "Fifo0 MAC Address", None))
        self.labelRemoteFifo1Mac.setText(_translate("MainWindow", "Fifo1 MAC Address", None))
        self.labelRemoteEth0Ip.setText(_translate("MainWindow", "Eth0 IP Address     ", None))
        self.labelRemoteFifo0Ip.setText(_translate("MainWindow", "Fifo0 IP Address", None))
        self.labelRemoteFifo1Ip.setText(_translate("MainWindow", "Fifo1 IP Address", None))
        self.labelRemoteEth0Mac.setText(_translate("MainWindow", "Eth0 MAC Address", None))
        self.labelRemoteDeviceDetails.setText(_translate("MainWindow", "Remote Device Details", None))
        self.pushButtonScanRemoteChild.setText(_translate("MainWindow", "Search Remote Devices", None))
        self.labelRemoteBackupRouteTable.setText(_translate("MainWindow", "Backup Route Table", None))
        self.textEditRemoteBackRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.labelRemoteRouteTable.setText(_translate("MainWindow", "Route Table", None))
        self.textEditRemoteRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "Config .FTP File", None))
        self.pushButtonRemoteFtpBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonRemoteFtpApply.setText(_translate("MainWindow", "Apply", None))
        self.label_6.setText(_translate("MainWindow", "Config .XML File", None))
        self.pushButtonRemoteXmlBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonRemoteXmlApply.setText(_translate("MainWindow", "Apply", None))
        self.pushButton_2.setText(_translate("MainWindow", "Restart Modem", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.labelLocalDefSoftVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDefSoftCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDefaultSoftware_3.setText(_translate("MainWindow", "Default Software", None))
        self.labelLocalUpdSoftVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalUpdSoftCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalUpdateSoftware_3.setText(_translate("MainWindow", "Update Software", None))
        self.labelLocalDspSoftVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspSoftCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspSoftware_3.setText(_translate("MainWindow", "DSP Software", None))
        self.labelLocalDspConfVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspConfCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspConfig_3.setText(_translate("MainWindow", "DSP Config", None))
        self.labelLocalDevSoftwareDetails_3.setText(_translate("MainWindow", "Local Device Software Setails", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevSoftwareDetails), _translate("MainWindow", "Software Details", None))

