# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\myPython\githubrepository\discovery\mainwindowV02.1\treegui_v2.1.1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(967, 771)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.MainFrame = QtGui.QFrame(self.centralwidget)
        self.MainFrame.setStyleSheet(_fromUtf8(""))
        self.MainFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainFrame.setObjectName(_fromUtf8("MainFrame"))
        self.gridLayout_17 = QtGui.QGridLayout(self.MainFrame)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.splitter = QtGui.QSplitter(self.MainFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.scrollArea_4 = QtGui.QScrollArea(self.splitter)
        self.scrollArea_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_4.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_9 = QtGui.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 300, 727))
        self.scrollAreaWidgetContents_9.setObjectName(_fromUtf8("scrollAreaWidgetContents_9"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents_9)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.scrollAreaWidgetContents_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.treeWidget.setFrameShape(QtGui.QFrame.Box)
        self.treeWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setAutoScroll(True)
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.treeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.treeWidget.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item_1.setFont(0, font)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setMinimumSectionSize(100)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_9)
        self.frameStackedWidget = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameStackedWidget.sizePolicy().hasHeightForWidth())
        self.frameStackedWidget.setSizePolicy(sizePolicy)
        self.frameStackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameStackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.frameStackedWidget.setObjectName(_fromUtf8("frameStackedWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameStackedWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.frameStackedWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pcDetails = QtGui.QWidget()
        self.pcDetails.setObjectName(_fromUtf8("pcDetails"))
        self.gridLayout_10 = QtGui.QGridLayout(self.pcDetails)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.framePcMain = QtGui.QFrame(self.pcDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcMain.sizePolicy().hasHeightForWidth())
        self.framePcMain.setSizePolicy(sizePolicy)
        self.framePcMain.setStyleSheet(_fromUtf8("background-color: rgb(245, 245, 245);"))
        self.framePcMain.setFrameShape(QtGui.QFrame.Box)
        self.framePcMain.setFrameShadow(QtGui.QFrame.Sunken)
        self.framePcMain.setObjectName(_fromUtf8("framePcMain"))
        self.gridLayout_26 = QtGui.QGridLayout(self.framePcMain)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.scrollArea = QtGui.QScrollArea(self.framePcMain)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 568, 693))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.pushButtonPc = QtGui.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButtonPc.setGeometry(QtCore.QRect(20, 20, 150, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPc.sizePolicy().hasHeightForWidth())
        self.pushButtonPc.setSizePolicy(sizePolicy)
        self.pushButtonPc.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonPc.setDefault(False)
        self.pushButtonPc.setObjectName(_fromUtf8("pushButtonPc"))
        self.framePcAddressDetails = QtGui.QFrame(self.scrollAreaWidgetContents_4)
        self.framePcAddressDetails.setGeometry(QtCore.QRect(20, 90, 383, 361))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePcAddressDetails.sizePolicy().hasHeightForWidth())
        self.framePcAddressDetails.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.framePcAddressDetails.setPalette(palette)
        self.framePcAddressDetails.setStyleSheet(_fromUtf8(" QFrame #framePcAddressDetails  {border: 1px solid rgb(210, 210, 210)} ;\n"
"background-color: rgb(240, 240, 240);"))
        self.framePcAddressDetails.setFrameShape(QtGui.QFrame.Box)
        self.framePcAddressDetails.setFrameShadow(QtGui.QFrame.Plain)
        self.framePcAddressDetails.setLineWidth(1)
        self.framePcAddressDetails.setObjectName(_fromUtf8("framePcAddressDetails"))
        self.gridLayout_18 = QtGui.QGridLayout(self.framePcAddressDetails)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setSpacing(5)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setMargin(9)
        self.gridLayout_19.setSpacing(9)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.radioButtonDefaultIp = QtGui.QRadioButton(self.framePcAddressDetails)
        self.radioButtonDefaultIp.setChecked(True)
        self.radioButtonDefaultIp.setObjectName(_fromUtf8("radioButtonDefaultIp"))
        self.gridLayout_19.addWidget(self.radioButtonDefaultIp, 1, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.framePcAddressDetails)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_19.addWidget(self.line_6, 3, 0, 1, 1)
        self.radioButtonManualIp = QtGui.QRadioButton(self.framePcAddressDetails)
        self.radioButtonManualIp.setObjectName(_fromUtf8("radioButtonManualIp"))
        self.gridLayout_19.addWidget(self.radioButtonManualIp, 2, 0, 1, 1)
        self.radioButtonDhcpIp = QtGui.QRadioButton(self.framePcAddressDetails)
        self.radioButtonDhcpIp.setObjectName(_fromUtf8("radioButtonDhcpIp"))
        self.gridLayout_19.addWidget(self.radioButtonDhcpIp, 0, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_19, 1, 0, 1, 2)
        self.tcpIpDetailsLabel = QtGui.QLabel(self.framePcAddressDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tcpIpDetailsLabel.sizePolicy().hasHeightForWidth())
        self.tcpIpDetailsLabel.setSizePolicy(sizePolicy)
        self.tcpIpDetailsLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.tcpIpDetailsLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tcpIpDetailsLabel.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.tcpIpDetailsLabel.setIndent(10)
        self.tcpIpDetailsLabel.setObjectName(_fromUtf8("tcpIpDetailsLabel"))
        self.gridLayout_18.addWidget(self.tcpIpDetailsLabel, 3, 0, 1, 2)
        self.IpSelectionOptionsLabel = QtGui.QLabel(self.framePcAddressDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IpSelectionOptionsLabel.sizePolicy().hasHeightForWidth())
        self.IpSelectionOptionsLabel.setSizePolicy(sizePolicy)
        self.IpSelectionOptionsLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.IpSelectionOptionsLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.IpSelectionOptionsLabel.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.IpSelectionOptionsLabel.setLineWidth(1)
        self.IpSelectionOptionsLabel.setIndent(10)
        self.IpSelectionOptionsLabel.setObjectName(_fromUtf8("IpSelectionOptionsLabel"))
        self.gridLayout_18.addWidget(self.IpSelectionOptionsLabel, 0, 0, 1, 2)
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setMargin(9)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.labelPcPhysicalAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcPhysicalAddress.setObjectName(_fromUtf8("labelPcPhysicalAddress"))
        self.gridLayout_24.addWidget(self.labelPcPhysicalAddress, 0, 0, 1, 1)
        self.labelPcSubnetMask = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcSubnetMask.setObjectName(_fromUtf8("labelPcSubnetMask"))
        self.gridLayout_24.addWidget(self.labelPcSubnetMask, 2, 0, 1, 1)
        self.pushButtonCancelPcIp = QtGui.QPushButton(self.framePcAddressDetails)
        self.pushButtonCancelPcIp.setEnabled(True)
        self.pushButtonCancelPcIp.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonCancelPcIp.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButtonCancelPcIp.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonCancelPcIp.setAutoDefault(False)
        self.pushButtonCancelPcIp.setDefault(False)
        self.pushButtonCancelPcIp.setFlat(False)
        self.pushButtonCancelPcIp.setObjectName(_fromUtf8("pushButtonCancelPcIp"))
        self.gridLayout_24.addWidget(self.pushButtonCancelPcIp, 5, 3, 1, 1)
        self.labelPcDefaultGateway = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcDefaultGateway.setObjectName(_fromUtf8("labelPcDefaultGateway"))
        self.gridLayout_24.addWidget(self.labelPcDefaultGateway, 3, 0, 1, 1)
        self.pushButtonApplyPcIp = QtGui.QPushButton(self.framePcAddressDetails)
        self.pushButtonApplyPcIp.setEnabled(False)
        self.pushButtonApplyPcIp.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonApplyPcIp.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonApplyPcIp.setAutoDefault(False)
        self.pushButtonApplyPcIp.setDefault(False)
        self.pushButtonApplyPcIp.setObjectName(_fromUtf8("pushButtonApplyPcIp"))
        self.gridLayout_24.addWidget(self.pushButtonApplyPcIp, 5, 4, 1, 1)
        self.pushButtonRefreshPcIp = QtGui.QPushButton(self.framePcAddressDetails)
        self.pushButtonRefreshPcIp.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonRefreshPcIp.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRefreshPcIp.setObjectName(_fromUtf8("pushButtonRefreshPcIp"))
        self.gridLayout_24.addWidget(self.pushButtonRefreshPcIp, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem, 5, 1, 1, 1)
        self.labelPcIpAddress = QtGui.QLabel(self.framePcAddressDetails)
        self.labelPcIpAddress.setObjectName(_fromUtf8("labelPcIpAddress"))
        self.gridLayout_24.addWidget(self.labelPcIpAddress, 1, 0, 1, 1)
        self.lineEditPcDefaultGateway = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcDefaultGateway.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditPcDefaultGateway.setStyleSheet(_fromUtf8(""))
        self.lineEditPcDefaultGateway.setReadOnly(True)
        self.lineEditPcDefaultGateway.setObjectName(_fromUtf8("lineEditPcDefaultGateway"))
        self.gridLayout_24.addWidget(self.lineEditPcDefaultGateway, 3, 3, 1, 2)
        self.lineEditPcIpAddress = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcIpAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditPcIpAddress.setStyleSheet(_fromUtf8(""))
        self.lineEditPcIpAddress.setText(_fromUtf8(""))
        self.lineEditPcIpAddress.setReadOnly(True)
        self.lineEditPcIpAddress.setObjectName(_fromUtf8("lineEditPcIpAddress"))
        self.gridLayout_24.addWidget(self.lineEditPcIpAddress, 1, 3, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_24.addItem(spacerItem1, 4, 3, 1, 1)
        self.lineEditPcPhysicalAddress = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcPhysicalAddress.setEnabled(True)
        self.lineEditPcPhysicalAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditPcPhysicalAddress.setStyleSheet(_fromUtf8(""))
        self.lineEditPcPhysicalAddress.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditPcPhysicalAddress.setText(_fromUtf8(""))
        self.lineEditPcPhysicalAddress.setReadOnly(True)
        self.lineEditPcPhysicalAddress.setObjectName(_fromUtf8("lineEditPcPhysicalAddress"))
        self.gridLayout_24.addWidget(self.lineEditPcPhysicalAddress, 0, 3, 1, 2)
        self.lineEditPcSubnetMask = QtGui.QLineEdit(self.framePcAddressDetails)
        self.lineEditPcSubnetMask.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditPcSubnetMask.setStyleSheet(_fromUtf8(""))
        self.lineEditPcSubnetMask.setText(_fromUtf8(""))
        self.lineEditPcSubnetMask.setReadOnly(True)
        self.lineEditPcSubnetMask.setObjectName(_fromUtf8("lineEditPcSubnetMask"))
        self.gridLayout_24.addWidget(self.lineEditPcSubnetMask, 2, 3, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem2, 5, 5, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_24, 4, 0, 2, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_26.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.framePcMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pcDetails)
        self.localModems = QtGui.QWidget()
        self.localModems.setObjectName(_fromUtf8("localModems"))
        self.gridLayout_5 = QtGui.QGridLayout(self.localModems)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frameLocalMain = QtGui.QFrame(self.localModems)
        self.frameLocalMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameLocalMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frameLocalMain.setObjectName(_fromUtf8("frameLocalMain"))
        self.gridLayout_25 = QtGui.QGridLayout(self.frameLocalMain)
        self.gridLayout_25.setMargin(0)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.tabLocalDevDetails = QtGui.QTabWidget(self.frameLocalMain)
        self.tabLocalDevDetails.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabLocalDevDetails.sizePolicy().hasHeightForWidth())
        self.tabLocalDevDetails.setSizePolicy(sizePolicy)
        self.tabLocalDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(237, 233, 255);\n"
"background-color: rgb(245, 245, 245);"))
        self.tabLocalDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabLocalDevDetails.setIconSize(QtCore.QSize(16, 16))
        self.tabLocalDevDetails.setTabsClosable(False)
        self.tabLocalDevDetails.setObjectName(_fromUtf8("tabLocalDevDetails"))
        self.localDevNetworkDetails = QtGui.QWidget()
        self.localDevNetworkDetails.setObjectName(_fromUtf8("localDevNetworkDetails"))
        self.gridLayout = QtGui.QGridLayout(self.localDevNetworkDetails)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea_2 = QtGui.QScrollArea(self.localDevNetworkDetails)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 564, 669))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.layoutWidget_3 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 371, 544))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frameLocalNetwork = QtGui.QFrame(self.layoutWidget_3)
        self.frameLocalNetwork.setStyleSheet(_fromUtf8(" QFrame #frameLocalNetwork  {border: 1px solid rgb(210, 210, 210)} ;\n"
"background-color: rgb(240, 240, 240);"))
        self.frameLocalNetwork.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalNetwork.setFrameShadow(QtGui.QFrame.Plain)
        self.frameLocalNetwork.setObjectName(_fromUtf8("frameLocalNetwork"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frameLocalNetwork)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelLocalDeviceDetails = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalDeviceDetails.setMinimumSize(QtCore.QSize(0, 25))
        self.labelLocalDeviceDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLocalDeviceDetails.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelLocalDeviceDetails.setScaledContents(False)
        self.labelLocalDeviceDetails.setIndent(10)
        self.labelLocalDeviceDetails.setObjectName(_fromUtf8("labelLocalDeviceDetails"))
        self.gridLayout_7.addWidget(self.labelLocalDeviceDetails, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 20, 9)
        self.gridLayout_2.setHorizontalSpacing(80)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelLocalEth0Ip = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalEth0Ip.setObjectName(_fromUtf8("labelLocalEth0Ip"))
        self.gridLayout_2.addWidget(self.labelLocalEth0Ip, 1, 0, 1, 1)
        self.labelLocalFifo0Ip = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalFifo0Ip.setObjectName(_fromUtf8("labelLocalFifo0Ip"))
        self.gridLayout_2.addWidget(self.labelLocalFifo0Ip, 7, 0, 1, 1)
        self.labelLocalFifo1Ip = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalFifo1Ip.setObjectName(_fromUtf8("labelLocalFifo1Ip"))
        self.gridLayout_2.addWidget(self.labelLocalFifo1Ip, 11, 0, 1, 1)
        self.lineEditLocalEth0Ip = QtGui.QLineEdit(self.frameLocalNetwork)
        self.lineEditLocalEth0Ip.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditLocalEth0Ip.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalEth0Ip.setText(_fromUtf8(""))
        self.lineEditLocalEth0Ip.setReadOnly(True)
        self.lineEditLocalEth0Ip.setObjectName(_fromUtf8("lineEditLocalEth0Ip"))
        self.gridLayout_2.addWidget(self.lineEditLocalEth0Ip, 1, 1, 1, 1)
        self.lineEditFifo1IpAddress = QtGui.QLineEdit(self.frameLocalNetwork)
        self.lineEditFifo1IpAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditFifo1IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditFifo1IpAddress.setReadOnly(True)
        self.lineEditFifo1IpAddress.setObjectName(_fromUtf8("lineEditFifo1IpAddress"))
        self.gridLayout_2.addWidget(self.lineEditFifo1IpAddress, 11, 1, 1, 1)
        self.lineEditFifo0IpAddress = QtGui.QLineEdit(self.frameLocalNetwork)
        self.lineEditFifo0IpAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditFifo0IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditFifo0IpAddress.setReadOnly(True)
        self.lineEditFifo0IpAddress.setObjectName(_fromUtf8("lineEditFifo0IpAddress"))
        self.gridLayout_2.addWidget(self.lineEditFifo0IpAddress, 7, 1, 1, 1)
        self.labelLocalFifo0Mac = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalFifo0Mac.setObjectName(_fromUtf8("labelLocalFifo0Mac"))
        self.gridLayout_2.addWidget(self.labelLocalFifo0Mac, 6, 0, 1, 1)
        self.lineEditLocalEth0MacAddress = QtGui.QLineEdit(self.frameLocalNetwork)
        self.lineEditLocalEth0MacAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditLocalEth0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalEth0MacAddress.setReadOnly(True)
        self.lineEditLocalEth0MacAddress.setObjectName(_fromUtf8("lineEditLocalEth0MacAddress"))
        self.gridLayout_2.addWidget(self.lineEditLocalEth0MacAddress, 0, 1, 1, 1)
        self.labelLocalEth0Mac = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalEth0Mac.setObjectName(_fromUtf8("labelLocalEth0Mac"))
        self.gridLayout_2.addWidget(self.labelLocalEth0Mac, 0, 0, 1, 1)
        self.lineEditLocalFifo0MacAddress = QtGui.QLineEdit(self.frameLocalNetwork)
        self.lineEditLocalFifo0MacAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditLocalFifo0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalFifo0MacAddress.setReadOnly(True)
        self.lineEditLocalFifo0MacAddress.setObjectName(_fromUtf8("lineEditLocalFifo0MacAddress"))
        self.gridLayout_2.addWidget(self.lineEditLocalFifo0MacAddress, 6, 1, 1, 1)
        self.labelLocalEth0Mask = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalEth0Mask.setObjectName(_fromUtf8("labelLocalEth0Mask"))
        self.gridLayout_2.addWidget(self.labelLocalEth0Mask, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.frameLocalNetwork)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 2)
        self.line_2 = QtGui.QFrame(self.frameLocalNetwork)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 9, 0, 1, 2)
        self.lineEditLocalEth0Mask = QtGui.QLineEdit(self.frameLocalNetwork)
        self.lineEditLocalEth0Mask.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditLocalEth0Mask.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalEth0Mask.setObjectName(_fromUtf8("lineEditLocalEth0Mask"))
        self.gridLayout_2.addWidget(self.lineEditLocalEth0Mask, 2, 1, 1, 1)
        self.labelLocalFifo1Mac = QtGui.QLabel(self.frameLocalNetwork)
        self.labelLocalFifo1Mac.setObjectName(_fromUtf8("labelLocalFifo1Mac"))
        self.gridLayout_2.addWidget(self.labelLocalFifo1Mac, 10, 0, 1, 1)
        self.lineEditLocalFifo1MacAddress = QtGui.QLineEdit(self.frameLocalNetwork)
        self.lineEditLocalFifo1MacAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditLocalFifo1MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalFifo1MacAddress.setReadOnly(True)
        self.lineEditLocalFifo1MacAddress.setObjectName(_fromUtf8("lineEditLocalFifo1MacAddress"))
        self.gridLayout_2.addWidget(self.lineEditLocalFifo1MacAddress, 10, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frameLocalNetwork)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem3)
        self.frame_3 = QtGui.QFrame(self.layoutWidget_3)
        self.frame_3.setStyleSheet(_fromUtf8(" QFrame #frame_3 {border: 1px solid rgb(210, 210, 210)} ;\n"
"background-color: rgb(240, 240, 240);"))
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelLocalRouteTable = QtGui.QLabel(self.frame_3)
        self.labelLocalRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelLocalRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelLocalRouteTable.setTextFormat(QtCore.Qt.AutoText)
        self.labelLocalRouteTable.setIndent(10)
        self.labelLocalRouteTable.setObjectName(_fromUtf8("labelLocalRouteTable"))
        self.verticalLayout_3.addWidget(self.labelLocalRouteTable)
        self.textEditLocalRoute = QtGui.QTextEdit(self.frame_3)
        self.textEditLocalRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditLocalRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditLocalRoute.setReadOnly(True)
        self.textEditLocalRoute.setAcceptRichText(True)
        self.textEditLocalRoute.setObjectName(_fromUtf8("textEditLocalRoute"))
        self.verticalLayout_3.addWidget(self.textEditLocalRoute)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_2 = QtGui.QFrame(self.layoutWidget_3)
        self.frame_2.setStyleSheet(_fromUtf8(" QFrame #frame_2  {border: 1px solid rgb(210, 210, 210)} ;\n"
"background-color: rgb(240, 240, 240);"))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelLocalBackupRouteTable = QtGui.QLabel(self.frame_2)
        self.labelLocalBackupRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelLocalBackupRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelLocalBackupRouteTable.setIndent(10)
        self.labelLocalBackupRouteTable.setObjectName(_fromUtf8("labelLocalBackupRouteTable"))
        self.verticalLayout_5.addWidget(self.labelLocalBackupRouteTable)
        self.textEditLocalBackRoute = QtGui.QTextEdit(self.frame_2)
        self.textEditLocalBackRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditLocalBackRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditLocalBackRoute.setReadOnly(True)
        self.textEditLocalBackRoute.setAcceptRichText(True)
        self.textEditLocalBackRoute.setObjectName(_fromUtf8("textEditLocalBackRoute"))
        self.verticalLayout_5.addWidget(self.textEditLocalBackRoute)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.pushButtonReset = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonReset.setGeometry(QtCore.QRect(390, 50, 151, 31))
        self.pushButtonReset.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.pushButtonScanRemote = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonScanRemote.setGeometry(QtCore.QRect(390, 10, 150, 31))
        self.pushButtonScanRemote.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonScanRemote.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonScanRemote.setObjectName(_fromUtf8("pushButtonScanRemote"))
        self.layoutWidget_2 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 520, 451, 111))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditLocalXmlBrowse = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditLocalXmlBrowse.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditLocalXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalXmlBrowse.setText(_fromUtf8(""))
        self.lineEditLocalXmlBrowse.setObjectName(_fromUtf8("lineEditLocalXmlBrowse"))
        self.gridLayout_8.addWidget(self.lineEditLocalXmlBrowse, 0, 1, 1, 1)
        self.pushButtonLocalXmlBrowse = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLocalXmlBrowse.sizePolicy().hasHeightForWidth())
        self.pushButtonLocalXmlBrowse.setSizePolicy(sizePolicy)
        self.pushButtonLocalXmlBrowse.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonLocalXmlBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonLocalXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalXmlBrowse.setObjectName(_fromUtf8("pushButtonLocalXmlBrowse"))
        self.gridLayout_8.addWidget(self.pushButtonLocalXmlBrowse, 0, 2, 1, 1)
        self.pushButtonLocalXmlApply = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLocalXmlApply.sizePolicy().hasHeightForWidth())
        self.pushButtonLocalXmlApply.setSizePolicy(sizePolicy)
        self.pushButtonLocalXmlApply.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonLocalXmlApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonLocalXmlApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalXmlApply.setObjectName(_fromUtf8("pushButtonLocalXmlApply"))
        self.gridLayout_8.addWidget(self.pushButtonLocalXmlApply, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditLocalFtpBrowse = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditLocalFtpBrowse.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditLocalFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLocalFtpBrowse.setObjectName(_fromUtf8("lineEditLocalFtpBrowse"))
        self.gridLayout_8.addWidget(self.lineEditLocalFtpBrowse, 1, 1, 1, 1)
        self.pushButtonLocalFtpBrowse = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonLocalFtpBrowse.setMinimumSize(QtCore.QSize(30, 28))
        self.pushButtonLocalFtpBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonLocalFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalFtpBrowse.setObjectName(_fromUtf8("pushButtonLocalFtpBrowse"))
        self.gridLayout_8.addWidget(self.pushButtonLocalFtpBrowse, 1, 2, 1, 1)
        self.pushButtonLocalFtpApply = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButtonLocalFtpApply.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonLocalFtpApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonLocalFtpApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonLocalFtpApply.setObjectName(_fromUtf8("pushButtonLocalFtpApply"))
        self.gridLayout_8.addWidget(self.pushButtonLocalFtpApply, 1, 3, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabLocalDevDetails.addTab(self.localDevNetworkDetails, _fromUtf8(""))
        self.localDevSoftwareDetails = QtGui.QWidget()
        self.localDevSoftwareDetails.setObjectName(_fromUtf8("localDevSoftwareDetails"))
        self.frameLocalSoftware = QtGui.QFrame(self.localDevSoftwareDetails)
        self.frameLocalSoftware.setGeometry(QtCore.QRect(10, 20, 411, 621))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalSoftware.setSizePolicy(sizePolicy)
        self.frameLocalSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalSoftware.setObjectName(_fromUtf8("frameLocalSoftware"))
        self.frameLocalDefSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDefSoftware.setGeometry(QtCore.QRect(20, 30, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDefSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDefSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDefSoftware.setAutoFillBackground(False)
        self.frameLocalDefSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDefSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDefSoftware.setLineWidth(1)
        self.frameLocalDefSoftware.setObjectName(_fromUtf8("frameLocalDefSoftware"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frameLocalDefSoftware)
        self.gridLayout_20.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_20.setHorizontalSpacing(80)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.labelLocalDefSoftVersion = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftVersion.setObjectName(_fromUtf8("labelLocalDefSoftVersion"))
        self.gridLayout_20.addWidget(self.labelLocalDefSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalDefSoftVersion = QtGui.QLineEdit(self.frameLocalDefSoftware)
        self.lineEditLocalDefSoftVersion.setObjectName(_fromUtf8("lineEditLocalDefSoftVersion"))
        self.gridLayout_20.addWidget(self.lineEditLocalDefSoftVersion, 0, 1, 1, 1)
        self.labelLocalDefSoftCrc = QtGui.QLabel(self.frameLocalDefSoftware)
        self.labelLocalDefSoftCrc.setObjectName(_fromUtf8("labelLocalDefSoftCrc"))
        self.gridLayout_20.addWidget(self.labelLocalDefSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalDefSoftCrc = QtGui.QLineEdit(self.frameLocalDefSoftware)
        self.lineEditLocalDefSoftCrc.setObjectName(_fromUtf8("lineEditLocalDefSoftCrc"))
        self.gridLayout_20.addWidget(self.lineEditLocalDefSoftCrc, 1, 1, 1, 1)
        self.labelLocalDefaultSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDefaultSoftware.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.labelLocalDefaultSoftware.setScaledContents(False)
        self.labelLocalDefaultSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDefaultSoftware.setObjectName(_fromUtf8("labelLocalDefaultSoftware"))
        self.frameLocalUpdSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalUpdSoftware.setGeometry(QtCore.QRect(20, 130, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalUpdSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalUpdSoftware.setSizePolicy(sizePolicy)
        self.frameLocalUpdSoftware.setAutoFillBackground(False)
        self.frameLocalUpdSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalUpdSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalUpdSoftware.setLineWidth(1)
        self.frameLocalUpdSoftware.setObjectName(_fromUtf8("frameLocalUpdSoftware"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frameLocalUpdSoftware)
        self.gridLayout_21.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_21.setHorizontalSpacing(80)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.labelLocalUpdSoftVersion = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftVersion.setObjectName(_fromUtf8("labelLocalUpdSoftVersion"))
        self.gridLayout_21.addWidget(self.labelLocalUpdSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalUpdSoftVersion = QtGui.QLineEdit(self.frameLocalUpdSoftware)
        self.lineEditLocalUpdSoftVersion.setObjectName(_fromUtf8("lineEditLocalUpdSoftVersion"))
        self.gridLayout_21.addWidget(self.lineEditLocalUpdSoftVersion, 0, 1, 1, 1)
        self.labelLocalUpdSoftCrc = QtGui.QLabel(self.frameLocalUpdSoftware)
        self.labelLocalUpdSoftCrc.setObjectName(_fromUtf8("labelLocalUpdSoftCrc"))
        self.gridLayout_21.addWidget(self.labelLocalUpdSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalUpdSoftCrc = QtGui.QLineEdit(self.frameLocalUpdSoftware)
        self.lineEditLocalUpdSoftCrc.setObjectName(_fromUtf8("lineEditLocalUpdSoftCrc"))
        self.gridLayout_21.addWidget(self.lineEditLocalUpdSoftCrc, 1, 1, 1, 1)
        self.labelLocalUpdateSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalUpdateSoftware.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.labelLocalUpdateSoftware.setScaledContents(False)
        self.labelLocalUpdateSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalUpdateSoftware.setObjectName(_fromUtf8("labelLocalUpdateSoftware"))
        self.frameLocalDspSoftware = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspSoftware.setGeometry(QtCore.QRect(20, 230, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspSoftware.sizePolicy().hasHeightForWidth())
        self.frameLocalDspSoftware.setSizePolicy(sizePolicy)
        self.frameLocalDspSoftware.setAutoFillBackground(False)
        self.frameLocalDspSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspSoftware.setLineWidth(1)
        self.frameLocalDspSoftware.setObjectName(_fromUtf8("frameLocalDspSoftware"))
        self.gridLayout_22 = QtGui.QGridLayout(self.frameLocalDspSoftware)
        self.gridLayout_22.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_22.setHorizontalSpacing(80)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.labelLocalDspSoftVersion = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftVersion.setObjectName(_fromUtf8("labelLocalDspSoftVersion"))
        self.gridLayout_22.addWidget(self.labelLocalDspSoftVersion, 0, 0, 1, 1)
        self.lineEditLocalDspSoftVersion = QtGui.QLineEdit(self.frameLocalDspSoftware)
        self.lineEditLocalDspSoftVersion.setObjectName(_fromUtf8("lineEditLocalDspSoftVersion"))
        self.gridLayout_22.addWidget(self.lineEditLocalDspSoftVersion, 0, 1, 1, 1)
        self.labelLocalDspSoftCrc = QtGui.QLabel(self.frameLocalDspSoftware)
        self.labelLocalDspSoftCrc.setObjectName(_fromUtf8("labelLocalDspSoftCrc"))
        self.gridLayout_22.addWidget(self.labelLocalDspSoftCrc, 1, 0, 1, 1)
        self.lineEditLocalDspSoftCrc = QtGui.QLineEdit(self.frameLocalDspSoftware)
        self.lineEditLocalDspSoftCrc.setObjectName(_fromUtf8("lineEditLocalDspSoftCrc"))
        self.gridLayout_22.addWidget(self.lineEditLocalDspSoftCrc, 1, 1, 1, 1)
        self.labelLocalDspSoftware = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspSoftware.setGeometry(QtCore.QRect(30, 220, 81, 21))
        self.labelLocalDspSoftware.setScaledContents(False)
        self.labelLocalDspSoftware.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspSoftware.setObjectName(_fromUtf8("labelLocalDspSoftware"))
        self.frameLocalDspConfig = QtGui.QFrame(self.frameLocalSoftware)
        self.frameLocalDspConfig.setGeometry(QtCore.QRect(20, 330, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspConfig.sizePolicy().hasHeightForWidth())
        self.frameLocalDspConfig.setSizePolicy(sizePolicy)
        self.frameLocalDspConfig.setAutoFillBackground(False)
        self.frameLocalDspConfig.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspConfig.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspConfig.setLineWidth(1)
        self.frameLocalDspConfig.setObjectName(_fromUtf8("frameLocalDspConfig"))
        self.gridLayout_23 = QtGui.QGridLayout(self.frameLocalDspConfig)
        self.gridLayout_23.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_23.setHorizontalSpacing(80)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.labelLocalDspConfVersion = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfVersion.setObjectName(_fromUtf8("labelLocalDspConfVersion"))
        self.gridLayout_23.addWidget(self.labelLocalDspConfVersion, 0, 0, 1, 1)
        self.lineEditLocalDspConfVersion = QtGui.QLineEdit(self.frameLocalDspConfig)
        self.lineEditLocalDspConfVersion.setObjectName(_fromUtf8("lineEditLocalDspConfVersion"))
        self.gridLayout_23.addWidget(self.lineEditLocalDspConfVersion, 0, 1, 1, 1)
        self.labelLocalDspConfCrc = QtGui.QLabel(self.frameLocalDspConfig)
        self.labelLocalDspConfCrc.setObjectName(_fromUtf8("labelLocalDspConfCrc"))
        self.gridLayout_23.addWidget(self.labelLocalDspConfCrc, 1, 0, 1, 1)
        self.lineEditLocalDspConfCrc = QtGui.QLineEdit(self.frameLocalDspConfig)
        self.lineEditLocalDspConfCrc.setObjectName(_fromUtf8("lineEditLocalDspConfCrc"))
        self.gridLayout_23.addWidget(self.lineEditLocalDspConfCrc, 1, 1, 1, 1)
        self.labelLocalDspConfig = QtGui.QLabel(self.frameLocalSoftware)
        self.labelLocalDspConfig.setGeometry(QtCore.QRect(30, 320, 71, 21))
        self.labelLocalDspConfig.setScaledContents(False)
        self.labelLocalDspConfig.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspConfig.setObjectName(_fromUtf8("labelLocalDspConfig"))
        self.labelLocalDevSoftwareDetails = QtGui.QLabel(self.localDevSoftwareDetails)
        self.labelLocalDevSoftwareDetails.setGeometry(QtCore.QRect(120, 10, 191, 21))
        self.labelLocalDevSoftwareDetails.setScaledContents(False)
        self.labelLocalDevSoftwareDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDevSoftwareDetails.setObjectName(_fromUtf8("labelLocalDevSoftwareDetails"))
        self.tabLocalDevDetails.addTab(self.localDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_25.addWidget(self.tabLocalDevDetails, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frameLocalMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.localModems)
        self.remoteModems = QtGui.QWidget()
        self.remoteModems.setObjectName(_fromUtf8("remoteModems"))
        self.gridLayout_16 = QtGui.QGridLayout(self.remoteModems)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.frameRemoteMain = QtGui.QFrame(self.remoteModems)
        self.frameRemoteMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameRemoteMain.setFrameShadow(QtGui.QFrame.Raised)
        self.frameRemoteMain.setObjectName(_fromUtf8("frameRemoteMain"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frameRemoteMain)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setHorizontalSpacing(6)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tabRemoteDevDetails = QtGui.QTabWidget(self.frameRemoteMain)
        self.tabRemoteDevDetails.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabRemoteDevDetails.sizePolicy().hasHeightForWidth())
        self.tabRemoteDevDetails.setSizePolicy(sizePolicy)
        self.tabRemoteDevDetails.setStyleSheet(_fromUtf8("background-color: rgb(245, 245, 245);"))
        self.tabRemoteDevDetails.setTabPosition(QtGui.QTabWidget.North)
        self.tabRemoteDevDetails.setIconSize(QtCore.QSize(16, 16))
        self.tabRemoteDevDetails.setTabsClosable(False)
        self.tabRemoteDevDetails.setObjectName(_fromUtf8("tabRemoteDevDetails"))
        self.remoteDevNetworkDetails = QtGui.QWidget()
        self.remoteDevNetworkDetails.setObjectName(_fromUtf8("remoteDevNetworkDetails"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.remoteDevNetworkDetails)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea_3 = QtGui.QScrollArea(self.remoteDevNetworkDetails)
        self.scrollArea_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_3.setWidgetResizable(False)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_6 = QtGui.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 564, 669))
        self.scrollAreaWidgetContents_6.setObjectName(_fromUtf8("scrollAreaWidgetContents_6"))
        self.layoutWidget_4 = QtGui.QWidget(self.scrollAreaWidgetContents_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 371, 547))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frameRemoteNetwork = QtGui.QFrame(self.layoutWidget_4)
        self.frameRemoteNetwork.setStyleSheet(_fromUtf8(" QFrame #frameRemoteNetwork  {border: 1px solid rgb(210, 210, 210)} ;\n"
"background-color: rgb(240, 240, 240);"))
        self.frameRemoteNetwork.setFrameShape(QtGui.QFrame.Panel)
        self.frameRemoteNetwork.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameRemoteNetwork.setObjectName(_fromUtf8("frameRemoteNetwork"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frameRemoteNetwork)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(10, -1, 20, 9)
        self.gridLayout_6.setHorizontalSpacing(80)
        self.gridLayout_6.setVerticalSpacing(10)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lineEditRemoteFifo0IpAddress = QtGui.QLineEdit(self.frameRemoteNetwork)
        self.lineEditRemoteFifo0IpAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteFifo0IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo0IpAddress.setReadOnly(True)
        self.lineEditRemoteFifo0IpAddress.setObjectName(_fromUtf8("lineEditRemoteFifo0IpAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo0IpAddress, 6, 1, 1, 1)
        self.labelRemoteEth0Ip = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteEth0Ip.setObjectName(_fromUtf8("labelRemoteEth0Ip"))
        self.gridLayout_6.addWidget(self.labelRemoteEth0Ip, 1, 0, 1, 1)
        self.labelRemoteFifo0Ip = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteFifo0Ip.setObjectName(_fromUtf8("labelRemoteFifo0Ip"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo0Ip, 6, 0, 1, 1)
        self.labelRemoteFifo1Ip = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteFifo1Ip.setObjectName(_fromUtf8("labelRemoteFifo1Ip"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo1Ip, 10, 0, 1, 1)
        self.lineEditRemoteEth0Ip = QtGui.QLineEdit(self.frameRemoteNetwork)
        self.lineEditRemoteEth0Ip.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteEth0Ip.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteEth0Ip.setText(_fromUtf8(""))
        self.lineEditRemoteEth0Ip.setReadOnly(True)
        self.lineEditRemoteEth0Ip.setObjectName(_fromUtf8("lineEditRemoteEth0Ip"))
        self.gridLayout_6.addWidget(self.lineEditRemoteEth0Ip, 1, 1, 1, 1)
        self.lineEditRemoteFifo1IpAddress = QtGui.QLineEdit(self.frameRemoteNetwork)
        self.lineEditRemoteFifo1IpAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteFifo1IpAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo1IpAddress.setReadOnly(True)
        self.lineEditRemoteFifo1IpAddress.setObjectName(_fromUtf8("lineEditRemoteFifo1IpAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo1IpAddress, 10, 1, 1, 1)
        self.lineEditRemoteEth0MacAddress = QtGui.QLineEdit(self.frameRemoteNetwork)
        self.lineEditRemoteEth0MacAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteEth0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteEth0MacAddress.setReadOnly(True)
        self.lineEditRemoteEth0MacAddress.setObjectName(_fromUtf8("lineEditRemoteEth0MacAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteEth0MacAddress, 0, 1, 1, 1)
        self.labelRemoteEth0Mask = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteEth0Mask.setObjectName(_fromUtf8("labelRemoteEth0Mask"))
        self.gridLayout_6.addWidget(self.labelRemoteEth0Mask, 2, 0, 1, 1)
        self.labelRemoteEth0Mac = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteEth0Mac.setObjectName(_fromUtf8("labelRemoteEth0Mac"))
        self.gridLayout_6.addWidget(self.labelRemoteEth0Mac, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.frameRemoteNetwork)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 4, 0, 1, 2)
        self.line_4 = QtGui.QFrame(self.frameRemoteNetwork)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_6.addWidget(self.line_4, 8, 0, 1, 2)
        self.lineEditRemoteEth0Mask = QtGui.QLineEdit(self.frameRemoteNetwork)
        self.lineEditRemoteEth0Mask.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteEth0Mask.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteEth0Mask.setObjectName(_fromUtf8("lineEditRemoteEth0Mask"))
        self.gridLayout_6.addWidget(self.lineEditRemoteEth0Mask, 2, 1, 1, 1)
        self.labelRemoteFifo0Mac = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteFifo0Mac.setObjectName(_fromUtf8("labelRemoteFifo0Mac"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo0Mac, 5, 0, 1, 1)
        self.lineEditRemoteFifo0MacAddress = QtGui.QLineEdit(self.frameRemoteNetwork)
        self.lineEditRemoteFifo0MacAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteFifo0MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo0MacAddress.setReadOnly(True)
        self.lineEditRemoteFifo0MacAddress.setObjectName(_fromUtf8("lineEditRemoteFifo0MacAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo0MacAddress, 5, 1, 1, 1)
        self.labelRemoteFifo1Mac = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteFifo1Mac.setObjectName(_fromUtf8("labelRemoteFifo1Mac"))
        self.gridLayout_6.addWidget(self.labelRemoteFifo1Mac, 9, 0, 1, 1)
        self.lineEditRemoteFifo1MacAddress = QtGui.QLineEdit(self.frameRemoteNetwork)
        self.lineEditRemoteFifo1MacAddress.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteFifo1MacAddress.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFifo1MacAddress.setReadOnly(True)
        self.lineEditRemoteFifo1MacAddress.setObjectName(_fromUtf8("lineEditRemoteFifo1MacAddress"))
        self.gridLayout_6.addWidget(self.lineEditRemoteFifo1MacAddress, 9, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.labelRemoteDeviceDetails = QtGui.QLabel(self.frameRemoteNetwork)
        self.labelRemoteDeviceDetails.setMinimumSize(QtCore.QSize(0, 25))
        self.labelRemoteDeviceDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelRemoteDeviceDetails.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelRemoteDeviceDetails.setScaledContents(False)
        self.labelRemoteDeviceDetails.setIndent(10)
        self.labelRemoteDeviceDetails.setObjectName(_fromUtf8("labelRemoteDeviceDetails"))
        self.gridLayout_15.addWidget(self.labelRemoteDeviceDetails, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frameRemoteNetwork)
        spacerItem4 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem4)
        self.frame_9 = QtGui.QFrame(self.layoutWidget_4)
        self.frame_9.setStyleSheet(_fromUtf8(" QFrame #frame_9  {border: 1px solid rgb(210, 210, 210)} ;\n"
"background-color: rgb(240, 240, 240);"))
        self.frame_9.setFrameShape(QtGui.QFrame.Panel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.labelRemoteRouteTable = QtGui.QLabel(self.frame_9)
        self.labelRemoteRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelRemoteRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelRemoteRouteTable.setTextFormat(QtCore.Qt.AutoText)
        self.labelRemoteRouteTable.setIndent(10)
        self.labelRemoteRouteTable.setObjectName(_fromUtf8("labelRemoteRouteTable"))
        self.verticalLayout_11.addWidget(self.labelRemoteRouteTable)
        self.textEditRemoteRoute = QtGui.QTextEdit(self.frame_9)
        self.textEditRemoteRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditRemoteRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditRemoteRoute.setReadOnly(True)
        self.textEditRemoteRoute.setAcceptRichText(True)
        self.textEditRemoteRoute.setObjectName(_fromUtf8("textEditRemoteRoute"))
        self.verticalLayout_11.addWidget(self.textEditRemoteRoute)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_8 = QtGui.QFrame(self.layoutWidget_4)
        self.frame_8.setStyleSheet(_fromUtf8(" QFrame #frame_8  {border: 1px solid rgb(210, 210, 210)} ;\n"
"background-color: rgb(240, 240, 240);"))
        self.frame_8.setFrameShape(QtGui.QFrame.Panel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_8.setLineWidth(1)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.labelRemoteBackupRouteTable = QtGui.QLabel(self.frame_8)
        self.labelRemoteBackupRouteTable.setMinimumSize(QtCore.QSize(0, 20))
        self.labelRemoteBackupRouteTable.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 230);"))
        self.labelRemoteBackupRouteTable.setIndent(10)
        self.labelRemoteBackupRouteTable.setObjectName(_fromUtf8("labelRemoteBackupRouteTable"))
        self.verticalLayout_10.addWidget(self.labelRemoteBackupRouteTable)
        self.textEditRemoteBackRoute = QtGui.QTextEdit(self.frame_8)
        self.textEditRemoteBackRoute.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.textEditRemoteBackRoute.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditRemoteBackRoute.setReadOnly(True)
        self.textEditRemoteBackRoute.setAcceptRichText(True)
        self.textEditRemoteBackRoute.setObjectName(_fromUtf8("textEditRemoteBackRoute"))
        self.verticalLayout_10.addWidget(self.textEditRemoteBackRoute)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.pushButtonScanRemoteChild = QtGui.QPushButton(self.scrollAreaWidgetContents_6)
        self.pushButtonScanRemoteChild.setGeometry(QtCore.QRect(390, 10, 150, 31))
        self.pushButtonScanRemoteChild.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonScanRemoteChild.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonScanRemoteChild.setObjectName(_fromUtf8("pushButtonScanRemoteChild"))
        self.layoutWidget_5 = QtGui.QWidget(self.scrollAreaWidgetContents_6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 520, 451, 111))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEditRemoteXmlBrowse = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditRemoteXmlBrowse.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteXmlBrowse.setText(_fromUtf8(""))
        self.lineEditRemoteXmlBrowse.setObjectName(_fromUtf8("lineEditRemoteXmlBrowse"))
        self.gridLayout_9.addWidget(self.lineEditRemoteXmlBrowse, 0, 1, 1, 1)
        self.pushButtonRemoteXmlBrowse = QtGui.QPushButton(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemoteXmlBrowse.sizePolicy().hasHeightForWidth())
        self.pushButtonRemoteXmlBrowse.setSizePolicy(sizePolicy)
        self.pushButtonRemoteXmlBrowse.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonRemoteXmlBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonRemoteXmlBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteXmlBrowse.setObjectName(_fromUtf8("pushButtonRemoteXmlBrowse"))
        self.gridLayout_9.addWidget(self.pushButtonRemoteXmlBrowse, 0, 2, 1, 1)
        self.pushButtonRemoteXmlApply = QtGui.QPushButton(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemoteXmlApply.sizePolicy().hasHeightForWidth())
        self.pushButtonRemoteXmlApply.setSizePolicy(sizePolicy)
        self.pushButtonRemoteXmlApply.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonRemoteXmlApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemoteXmlApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteXmlApply.setObjectName(_fromUtf8("pushButtonRemoteXmlApply"))
        self.gridLayout_9.addWidget(self.pushButtonRemoteXmlApply, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEditRemoteFtpBrowse = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditRemoteFtpBrowse.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditRemoteFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditRemoteFtpBrowse.setObjectName(_fromUtf8("lineEditRemoteFtpBrowse"))
        self.gridLayout_9.addWidget(self.lineEditRemoteFtpBrowse, 1, 1, 1, 1)
        self.pushButtonRemoteFtpBrowse = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButtonRemoteFtpBrowse.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonRemoteFtpBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonRemoteFtpBrowse.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteFtpBrowse.setObjectName(_fromUtf8("pushButtonRemoteFtpBrowse"))
        self.gridLayout_9.addWidget(self.pushButtonRemoteFtpBrowse, 1, 2, 1, 1)
        self.pushButtonRemoteFtpApply = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButtonRemoteFtpApply.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButtonRemoteFtpApply.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRemoteFtpApply.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonRemoteFtpApply.setObjectName(_fromUtf8("pushButtonRemoteFtpApply"))
        self.gridLayout_9.addWidget(self.pushButtonRemoteFtpApply, 1, 3, 1, 1)
        self.pushButtonResetRemote = QtGui.QPushButton(self.scrollAreaWidgetContents_6)
        self.pushButtonResetRemote.setGeometry(QtCore.QRect(390, 50, 151, 31))
        self.pushButtonResetRemote.setStyleSheet(_fromUtf8("background-color: rgba(224, 231, 245, 255);"))
        self.pushButtonResetRemote.setObjectName(_fromUtf8("pushButtonResetRemote"))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_9.addWidget(self.scrollArea_3)
        self.tabRemoteDevDetails.addTab(self.remoteDevNetworkDetails, _fromUtf8(""))
        self.remoteDevSoftwareDetails = QtGui.QWidget()
        self.remoteDevSoftwareDetails.setObjectName(_fromUtf8("remoteDevSoftwareDetails"))
        self.frameRemoteSoftware = QtGui.QFrame(self.remoteDevSoftwareDetails)
        self.frameRemoteSoftware.setGeometry(QtCore.QRect(10, 20, 411, 621))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRemoteSoftware.sizePolicy().hasHeightForWidth())
        self.frameRemoteSoftware.setSizePolicy(sizePolicy)
        self.frameRemoteSoftware.setFrameShape(QtGui.QFrame.Box)
        self.frameRemoteSoftware.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameRemoteSoftware.setObjectName(_fromUtf8("frameRemoteSoftware"))
        self.frameLocalDefSoftware_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalDefSoftware_3.setGeometry(QtCore.QRect(20, 30, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDefSoftware_3.sizePolicy().hasHeightForWidth())
        self.frameLocalDefSoftware_3.setSizePolicy(sizePolicy)
        self.frameLocalDefSoftware_3.setAutoFillBackground(False)
        self.frameLocalDefSoftware_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDefSoftware_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDefSoftware_3.setLineWidth(1)
        self.frameLocalDefSoftware_3.setObjectName(_fromUtf8("frameLocalDefSoftware_3"))
        self.gridLayout_28 = QtGui.QGridLayout(self.frameLocalDefSoftware_3)
        self.gridLayout_28.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_28.setHorizontalSpacing(80)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.labelLocalDefSoftVersion_3 = QtGui.QLabel(self.frameLocalDefSoftware_3)
        self.labelLocalDefSoftVersion_3.setObjectName(_fromUtf8("labelLocalDefSoftVersion_3"))
        self.gridLayout_28.addWidget(self.labelLocalDefSoftVersion_3, 0, 0, 1, 1)
        self.lineEditLocalDefSoftVersion_3 = QtGui.QLineEdit(self.frameLocalDefSoftware_3)
        self.lineEditLocalDefSoftVersion_3.setObjectName(_fromUtf8("lineEditLocalDefSoftVersion_3"))
        self.gridLayout_28.addWidget(self.lineEditLocalDefSoftVersion_3, 0, 1, 1, 1)
        self.labelLocalDefSoftCrc_3 = QtGui.QLabel(self.frameLocalDefSoftware_3)
        self.labelLocalDefSoftCrc_3.setObjectName(_fromUtf8("labelLocalDefSoftCrc_3"))
        self.gridLayout_28.addWidget(self.labelLocalDefSoftCrc_3, 1, 0, 1, 1)
        self.lineEditLocalDefSoftCrc_3 = QtGui.QLineEdit(self.frameLocalDefSoftware_3)
        self.lineEditLocalDefSoftCrc_3.setObjectName(_fromUtf8("lineEditLocalDefSoftCrc_3"))
        self.gridLayout_28.addWidget(self.lineEditLocalDefSoftCrc_3, 1, 1, 1, 1)
        self.labelLocalDefaultSoftware_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalDefaultSoftware_3.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.labelLocalDefaultSoftware_3.setScaledContents(False)
        self.labelLocalDefaultSoftware_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDefaultSoftware_3.setObjectName(_fromUtf8("labelLocalDefaultSoftware_3"))
        self.frameLocalUpdSoftware_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalUpdSoftware_3.setGeometry(QtCore.QRect(20, 130, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalUpdSoftware_3.sizePolicy().hasHeightForWidth())
        self.frameLocalUpdSoftware_3.setSizePolicy(sizePolicy)
        self.frameLocalUpdSoftware_3.setAutoFillBackground(False)
        self.frameLocalUpdSoftware_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalUpdSoftware_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalUpdSoftware_3.setLineWidth(1)
        self.frameLocalUpdSoftware_3.setObjectName(_fromUtf8("frameLocalUpdSoftware_3"))
        self.gridLayout_29 = QtGui.QGridLayout(self.frameLocalUpdSoftware_3)
        self.gridLayout_29.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_29.setHorizontalSpacing(80)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.labelLocalUpdSoftVersion_3 = QtGui.QLabel(self.frameLocalUpdSoftware_3)
        self.labelLocalUpdSoftVersion_3.setObjectName(_fromUtf8("labelLocalUpdSoftVersion_3"))
        self.gridLayout_29.addWidget(self.labelLocalUpdSoftVersion_3, 0, 0, 1, 1)
        self.lineEditLocalUpdSoftVersion_3 = QtGui.QLineEdit(self.frameLocalUpdSoftware_3)
        self.lineEditLocalUpdSoftVersion_3.setObjectName(_fromUtf8("lineEditLocalUpdSoftVersion_3"))
        self.gridLayout_29.addWidget(self.lineEditLocalUpdSoftVersion_3, 0, 1, 1, 1)
        self.labelLocalUpdSoftCrc_3 = QtGui.QLabel(self.frameLocalUpdSoftware_3)
        self.labelLocalUpdSoftCrc_3.setObjectName(_fromUtf8("labelLocalUpdSoftCrc_3"))
        self.gridLayout_29.addWidget(self.labelLocalUpdSoftCrc_3, 1, 0, 1, 1)
        self.lineEditLocalUpdSoftCrc_3 = QtGui.QLineEdit(self.frameLocalUpdSoftware_3)
        self.lineEditLocalUpdSoftCrc_3.setObjectName(_fromUtf8("lineEditLocalUpdSoftCrc_3"))
        self.gridLayout_29.addWidget(self.lineEditLocalUpdSoftCrc_3, 1, 1, 1, 1)
        self.labelLocalUpdateSoftware_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalUpdateSoftware_3.setGeometry(QtCore.QRect(30, 120, 101, 21))
        self.labelLocalUpdateSoftware_3.setScaledContents(False)
        self.labelLocalUpdateSoftware_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalUpdateSoftware_3.setObjectName(_fromUtf8("labelLocalUpdateSoftware_3"))
        self.frameLocalDspSoftware_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalDspSoftware_3.setGeometry(QtCore.QRect(20, 230, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspSoftware_3.sizePolicy().hasHeightForWidth())
        self.frameLocalDspSoftware_3.setSizePolicy(sizePolicy)
        self.frameLocalDspSoftware_3.setAutoFillBackground(False)
        self.frameLocalDspSoftware_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspSoftware_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspSoftware_3.setLineWidth(1)
        self.frameLocalDspSoftware_3.setObjectName(_fromUtf8("frameLocalDspSoftware_3"))
        self.gridLayout_30 = QtGui.QGridLayout(self.frameLocalDspSoftware_3)
        self.gridLayout_30.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_30.setHorizontalSpacing(80)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.labelLocalDspSoftVersion_3 = QtGui.QLabel(self.frameLocalDspSoftware_3)
        self.labelLocalDspSoftVersion_3.setObjectName(_fromUtf8("labelLocalDspSoftVersion_3"))
        self.gridLayout_30.addWidget(self.labelLocalDspSoftVersion_3, 0, 0, 1, 1)
        self.lineEditLocalDspSoftVersion_3 = QtGui.QLineEdit(self.frameLocalDspSoftware_3)
        self.lineEditLocalDspSoftVersion_3.setObjectName(_fromUtf8("lineEditLocalDspSoftVersion_3"))
        self.gridLayout_30.addWidget(self.lineEditLocalDspSoftVersion_3, 0, 1, 1, 1)
        self.labelLocalDspSoftCrc_3 = QtGui.QLabel(self.frameLocalDspSoftware_3)
        self.labelLocalDspSoftCrc_3.setObjectName(_fromUtf8("labelLocalDspSoftCrc_3"))
        self.gridLayout_30.addWidget(self.labelLocalDspSoftCrc_3, 1, 0, 1, 1)
        self.lineEditLocalDspSoftCrc_3 = QtGui.QLineEdit(self.frameLocalDspSoftware_3)
        self.lineEditLocalDspSoftCrc_3.setObjectName(_fromUtf8("lineEditLocalDspSoftCrc_3"))
        self.gridLayout_30.addWidget(self.lineEditLocalDspSoftCrc_3, 1, 1, 1, 1)
        self.labelLocalDspSoftware_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalDspSoftware_3.setGeometry(QtCore.QRect(30, 220, 81, 21))
        self.labelLocalDspSoftware_3.setScaledContents(False)
        self.labelLocalDspSoftware_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspSoftware_3.setObjectName(_fromUtf8("labelLocalDspSoftware_3"))
        self.frameLocalDspConfig_3 = QtGui.QFrame(self.frameRemoteSoftware)
        self.frameLocalDspConfig_3.setGeometry(QtCore.QRect(20, 330, 321, 68))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLocalDspConfig_3.sizePolicy().hasHeightForWidth())
        self.frameLocalDspConfig_3.setSizePolicy(sizePolicy)
        self.frameLocalDspConfig_3.setAutoFillBackground(False)
        self.frameLocalDspConfig_3.setFrameShape(QtGui.QFrame.Box)
        self.frameLocalDspConfig_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameLocalDspConfig_3.setLineWidth(1)
        self.frameLocalDspConfig_3.setObjectName(_fromUtf8("frameLocalDspConfig_3"))
        self.gridLayout_31 = QtGui.QGridLayout(self.frameLocalDspConfig_3)
        self.gridLayout_31.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_31.setHorizontalSpacing(80)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.labelLocalDspConfVersion_3 = QtGui.QLabel(self.frameLocalDspConfig_3)
        self.labelLocalDspConfVersion_3.setObjectName(_fromUtf8("labelLocalDspConfVersion_3"))
        self.gridLayout_31.addWidget(self.labelLocalDspConfVersion_3, 0, 0, 1, 1)
        self.lineEditLocalDspConfVersion_3 = QtGui.QLineEdit(self.frameLocalDspConfig_3)
        self.lineEditLocalDspConfVersion_3.setObjectName(_fromUtf8("lineEditLocalDspConfVersion_3"))
        self.gridLayout_31.addWidget(self.lineEditLocalDspConfVersion_3, 0, 1, 1, 1)
        self.labelLocalDspConfCrc_3 = QtGui.QLabel(self.frameLocalDspConfig_3)
        self.labelLocalDspConfCrc_3.setObjectName(_fromUtf8("labelLocalDspConfCrc_3"))
        self.gridLayout_31.addWidget(self.labelLocalDspConfCrc_3, 1, 0, 1, 1)
        self.lineEditLocalDspConfCrc_3 = QtGui.QLineEdit(self.frameLocalDspConfig_3)
        self.lineEditLocalDspConfCrc_3.setObjectName(_fromUtf8("lineEditLocalDspConfCrc_3"))
        self.gridLayout_31.addWidget(self.lineEditLocalDspConfCrc_3, 1, 1, 1, 1)
        self.labelLocalDspConfig_3 = QtGui.QLabel(self.frameRemoteSoftware)
        self.labelLocalDspConfig_3.setGeometry(QtCore.QRect(30, 320, 71, 21))
        self.labelLocalDspConfig_3.setScaledContents(False)
        self.labelLocalDspConfig_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDspConfig_3.setObjectName(_fromUtf8("labelLocalDspConfig_3"))
        self.labelLocalDevSoftwareDetails_3 = QtGui.QLabel(self.remoteDevSoftwareDetails)
        self.labelLocalDevSoftwareDetails_3.setGeometry(QtCore.QRect(120, 10, 191, 21))
        self.labelLocalDevSoftwareDetails_3.setScaledContents(False)
        self.labelLocalDevSoftwareDetails_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLocalDevSoftwareDetails_3.setObjectName(_fromUtf8("labelLocalDevSoftwareDetails_3"))
        self.tabRemoteDevDetails.addTab(self.remoteDevSoftwareDetails, _fromUtf8(""))
        self.gridLayout_14.addWidget(self.tabRemoteDevDetails, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frameRemoteMain, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.remoteModems)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_17.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.MainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabLocalDevDetails.setCurrentIndex(0)
        self.tabRemoteDevDetails.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Network Devices", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "PC", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "TopSide Modem 2", None))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "dev1 00:01:02:03:04:05:06 192:168:125:100 jhi", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "Subsea Modem 2.2", None))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "dev-22 00:00:00:00:00:00 192.168.222.101", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "TopSide Modem 1", None))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "Subsea Modem 1.1", None))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "Modem 1.2 jefjkwe[ofjsdjvlsadjfpoajwepfjsdaf\'sdpojfpa", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButtonPc.setText(_translate("MainWindow", "Search Local Devices", None))
        self.radioButtonDefaultIp.setText(_translate("MainWindow", "Default IP Address", None))
        self.radioButtonManualIp.setText(_translate("MainWindow", "Manual IP Address", None))
        self.radioButtonDhcpIp.setText(_translate("MainWindow", "DHCP IP Address ", None))
        self.tcpIpDetailsLabel.setText(_translate("MainWindow", "TCP/IP Details", None))
        self.IpSelectionOptionsLabel.setText(_translate("MainWindow", "IP Selection Options", None))
        self.labelPcPhysicalAddress.setText(_translate("MainWindow", "Physical Address", None))
        self.labelPcSubnetMask.setText(_translate("MainWindow", "Subnet Mask", None))
        self.pushButtonCancelPcIp.setText(_translate("MainWindow", "Cancel", None))
        self.labelPcDefaultGateway.setText(_translate("MainWindow", "Default Gateway", None))
        self.pushButtonApplyPcIp.setText(_translate("MainWindow", "Apply", None))
        self.pushButtonRefreshPcIp.setText(_translate("MainWindow", "Refresh", None))
        self.labelPcIpAddress.setText(_translate("MainWindow", "IP Address", None))
        self.labelLocalDeviceDetails.setText(_translate("MainWindow", "Local Device Details", None))
        self.labelLocalEth0Ip.setText(_translate("MainWindow", "Eth0 IP Address     ", None))
        self.labelLocalFifo0Ip.setText(_translate("MainWindow", "Fifo0 IP Address", None))
        self.labelLocalFifo1Ip.setText(_translate("MainWindow", "Fifo1 IP Address", None))
        self.labelLocalFifo0Mac.setText(_translate("MainWindow", "Fifo0 MAC Address", None))
        self.labelLocalEth0Mac.setText(_translate("MainWindow", "Eth0 MAC Address", None))
        self.labelLocalEth0Mask.setText(_translate("MainWindow", "Eth0 Subnet Mask", None))
        self.labelLocalFifo1Mac.setText(_translate("MainWindow", "Fifo1 MAC Address", None))
        self.labelLocalRouteTable.setText(_translate("MainWindow", "Route Table", None))
        self.textEditLocalRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.labelLocalBackupRouteTable.setText(_translate("MainWindow", "Backup Route Table", None))
        self.textEditLocalBackRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset", None))
        self.pushButtonScanRemote.setText(_translate("MainWindow", "Search Remote Devices", None))
        self.label.setText(_translate("MainWindow", "Config .XML File", None))
        self.pushButtonLocalXmlBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonLocalXmlApply.setText(_translate("MainWindow", "Apply", None))
        self.label_2.setText(_translate("MainWindow", "Config .FTP File", None))
        self.pushButtonLocalFtpBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonLocalFtpApply.setText(_translate("MainWindow", "Apply", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.labelLocalDefSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDefSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDefaultSoftware.setText(_translate("MainWindow", "Default Software", None))
        self.labelLocalUpdSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalUpdSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalUpdateSoftware.setText(_translate("MainWindow", "Update Software", None))
        self.labelLocalDspSoftVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspSoftCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspSoftware.setText(_translate("MainWindow", "DSP Software", None))
        self.labelLocalDspConfVersion.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspConfCrc.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspConfig.setText(_translate("MainWindow", "DSP Config", None))
        self.labelLocalDevSoftwareDetails.setText(_translate("MainWindow", "Local Device Software Setails", None))
        self.tabLocalDevDetails.setTabText(self.tabLocalDevDetails.indexOf(self.localDevSoftwareDetails), _translate("MainWindow", "Software Details", None))
        self.labelRemoteEth0Ip.setText(_translate("MainWindow", "Eth0 IP Address     ", None))
        self.labelRemoteFifo0Ip.setText(_translate("MainWindow", "Fifo0 IP Address", None))
        self.labelRemoteFifo1Ip.setText(_translate("MainWindow", "Fifo1 IP Address", None))
        self.labelRemoteEth0Mask.setText(_translate("MainWindow", "Eth0 Subnet Mask", None))
        self.labelRemoteEth0Mac.setText(_translate("MainWindow", "Eth0 MAC Address", None))
        self.labelRemoteFifo0Mac.setText(_translate("MainWindow", "Fifo0 MAC Address", None))
        self.labelRemoteFifo1Mac.setText(_translate("MainWindow", "Fifo1 MAC Address", None))
        self.labelRemoteDeviceDetails.setText(_translate("MainWindow", "Remote Device Details", None))
        self.labelRemoteRouteTable.setText(_translate("MainWindow", "Route Table", None))
        self.textEditRemoteRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.labelRemoteBackupRouteTable.setText(_translate("MainWindow", "Backup Route Table", None))
        self.textEditRemoteBackRoute.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.pushButtonScanRemoteChild.setText(_translate("MainWindow", "Search Remote Devices", None))
        self.label_6.setText(_translate("MainWindow", "Config .XML File", None))
        self.pushButtonRemoteXmlBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonRemoteXmlApply.setText(_translate("MainWindow", "Apply", None))
        self.label_5.setText(_translate("MainWindow", "Config .FTP File", None))
        self.pushButtonRemoteFtpBrowse.setText(_translate("MainWindow", "...", None))
        self.pushButtonRemoteFtpApply.setText(_translate("MainWindow", "Apply", None))
        self.pushButtonResetRemote.setText(_translate("MainWindow", "Reset", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevNetworkDetails), _translate("MainWindow", "Network Details", None))
        self.labelLocalDefSoftVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDefSoftCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDefaultSoftware_3.setText(_translate("MainWindow", "Default Software", None))
        self.labelLocalUpdSoftVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalUpdSoftCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalUpdateSoftware_3.setText(_translate("MainWindow", "Update Software", None))
        self.labelLocalDspSoftVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspSoftCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspSoftware_3.setText(_translate("MainWindow", "DSP Software", None))
        self.labelLocalDspConfVersion_3.setText(_translate("MainWindow", "Version", None))
        self.labelLocalDspConfCrc_3.setText(_translate("MainWindow", "Software CRC ", None))
        self.labelLocalDspConfig_3.setText(_translate("MainWindow", "DSP Config", None))
        self.labelLocalDevSoftwareDetails_3.setText(_translate("MainWindow", "Local Device Software Setails", None))
        self.tabRemoteDevDetails.setTabText(self.tabRemoteDevDetails.indexOf(self.remoteDevSoftwareDetails), _translate("MainWindow", "Software Details", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

